PLUGINOBJECTS = colourspace.o
PLUGINNAME = colourspace
PATHTOROOT = ../

# ColourSpace needs spdlog, fmt (via spdlog), and CImg headers.
# Pass their locations via CXXFLAGS_ADD on the make command line, e.g.:
#   make CXXFLAGS_ADD="-I/path/to/spdlog/include -I/path/to/CImg"
# Add -DSPDLOG_FMT_EXTERNAL -I/path/to/fmt/include if using an external fmt.

include ../Makefile.master
