language: cpp
compiler:
  - gcc
  - clang
script:
  - make -C HostSupport DEBUGFLAGS=-O3 BITS=64
  - make -C Examples DEBUGFLAGS=-O3 BITS=64
  - make -C Support/Plugins DEBUGFLAGS=-O3 BITS=64
  - make -C Support/PropTester DEBUGFLAGS=-O3 BITS=64

