language: cpp
compiler:
  - gcc
  - clang
script:
  - make -C HostSupport DEBUGFLAG=-O3 BITS=64
  - make -C Examples DEBUGFLAG=-O3 BITS=64
  - make -C Support/Plugins DEBUGFLAG=-O3 BITS=64
  - make -C Support/PropTester DEBUGFLAG=-O3 BITS=64

