os:
  - linux
  - osx

language: cpp

compiler:
  - gcc
  - clang

matrix:
  exclude:
    - os: osx
      compiler: gcc
  fast_finish: true

# Travis CI has 1.5 cores per VM, take advantage of it
# But first, the makefiles have to be fixed: all plugins are using the same .o's
#env:
#  - MAKEFLAGS="-j 2"

script:
  - make $MAKEFLAGS -C HostSupport
  - make $MAKEFLAGS -C Examples CONFIG=debug
  - make $MAKEFLAGS -C Support/Plugins CONFIG=debug
  - make $MAKEFLAGS -C Support/PropTester CONFIG=debug
