// Copyright OpenFX and contributors to the OpenFX project.
// SPDX-License-Identifier: BSD-3-Clause
// NOTE: This file is auto-generated by gen-props.py. DO NOT EDIT.

#pragma once

#include <array>
#include <vector>
#include "ofxPropsAccess.h"
#include "ofxPropsMetadata.h"

namespace openfx {

// Type-safe property set accessor classes for HOSTS
//
// These wrapper classes provide convenient, type-safe access to property sets.
// - For plugins: getters for host-written properties, setters for plugin-written properties
// - For hosts: setters for host-written properties, getters for plugin-written properties
//
// Usage:
//   PropertyAccessor accessor(handle, propSuite);
//   EffectDescriptor desc(accessor);
//   desc.setLabel("My Effect");  // Type-safe setter
//   auto label = desc.label();    // Type-safe getter

// Base class for property set accessors
class PropertySetAccessor {
protected:
    PropertyAccessor& props_;
public:
    explicit PropertySetAccessor(PropertyAccessor& p) : props_(p) {}

    // Access to underlying PropertyAccessor for advanced use
    PropertyAccessor& props() { return props_; }
    const PropertyAccessor& props() const { return props_; }
};

// Property set accessor for: ClipDescriptor
class ClipDescriptor : public PropertySetAccessor {
public:
    using PropertySetAccessor::PropertySetAccessor;

    const char* type() const {
        return props_.get<PropId::OfxPropType>(0);
    }

    const char* name() const {
        return props_.get<PropId::OfxPropName>(0);
    }

    const char* label() const {
        return props_.get<PropId::OfxPropLabel>(0);
    }

    const char* shortLabel() const {
        return props_.get<PropId::OfxPropShortLabel>(0);
    }

    const char* longLabel() const {
        return props_.get<PropId::OfxPropLongLabel>(0);
    }

    const char* supportedComponents(int index = 0) const {
        return props_.get<PropId::OfxImageEffectPropSupportedComponents>(index);
    }

    bool temporalClipAccess() const {
        return props_.get<PropId::OfxImageEffectPropTemporalClipAccess>(0);
    }

    bool optional() const {
        return props_.get<PropId::OfxImageClipPropOptional>(0);
    }

    const char* fieldExtraction() const {
        return props_.get<PropId::OfxImageClipPropFieldExtraction>(0);
    }

    bool isMask() const {
        return props_.get<PropId::OfxImageClipPropIsMask>(0);
    }

    bool supportsTiles() const {
        return props_.get<PropId::OfxImageEffectPropSupportsTiles>(0);
    }

};

// Property set accessor for: ClipInstance
class ClipInstance : public PropertySetAccessor {
public:
    using PropertySetAccessor::PropertySetAccessor;

    void setType(const char* value) {
        props_.set<PropId::OfxPropType>(value, 0);
    }

    void setName(const char* value) {
        props_.set<PropId::OfxPropName>(value, 0);
    }

    void setLabel(const char* value) {
        props_.set<PropId::OfxPropLabel>(value, 0);
    }

    void setShortLabel(const char* value) {
        props_.set<PropId::OfxPropShortLabel>(value, 0);
    }

    void setLongLabel(const char* value) {
        props_.set<PropId::OfxPropLongLabel>(value, 0);
    }

    void setSupportedComponents(const char* value, int index = 0) {
        props_.set<PropId::OfxImageEffectPropSupportedComponents>(value, index);
    }

    void setTemporalClipAccess(bool value) {
        props_.set<PropId::OfxImageEffectPropTemporalClipAccess>(value, 0);
    }

    void setColourspace(const char* value) {
        props_.set<PropId::OfxImageClipPropColourspace>(value, 0);
    }

    void setPreferredColourspaces(const char* value, int index = 0) {
        props_.set<PropId::OfxImageClipPropPreferredColourspaces>(value, index);
    }

    void setOptional(bool value) {
        props_.set<PropId::OfxImageClipPropOptional>(value, 0);
    }

    void setFieldExtraction(const char* value) {
        props_.set<PropId::OfxImageClipPropFieldExtraction>(value, 0);
    }

    void setIsMask(bool value) {
        props_.set<PropId::OfxImageClipPropIsMask>(value, 0);
    }

    void setSupportsTiles(bool value) {
        props_.set<PropId::OfxImageEffectPropSupportsTiles>(value, 0);
    }

    void setPixelDepth(const char* value) {
        props_.set<PropId::OfxImageEffectPropPixelDepth>(value, 0);
    }

    void setComponents(const char* value) {
        props_.set<PropId::OfxImageEffectPropComponents>(value, 0);
    }

    void setUnmappedPixelDepth(const char* value) {
        props_.set<PropId::OfxImageClipPropUnmappedPixelDepth>(value, 0);
    }

    void setUnmappedComponents(const char* value) {
        props_.set<PropId::OfxImageClipPropUnmappedComponents>(value, 0);
    }

    void setPreMultiplication(const char* value) {
        props_.set<PropId::OfxImageEffectPropPreMultiplication>(value, 0);
    }

    void setPixelAspectRatio(double value) {
        props_.set<PropId::OfxImagePropPixelAspectRatio>(value, 0);
    }

    void setFrameRate(double value) {
        props_.set<PropId::OfxImageEffectPropFrameRate>(value, 0);
    }

    void setFrameRange(const std::array<double, 2>& values) {
        props_.setAll<PropId::OfxImageEffectPropFrameRange>(values);
    }

    void setFieldOrder(const char* value) {
        props_.set<PropId::OfxImageClipPropFieldOrder>(value, 0);
    }

    void setConnected(bool value) {
        props_.set<PropId::OfxImageClipPropConnected>(value, 0);
    }

    void setUnmappedFrameRange(const std::array<double, 2>& values) {
        props_.setAll<PropId::OfxImageEffectPropUnmappedFrameRange>(values);
    }

    void setUnmappedFrameRate(double value) {
        props_.set<PropId::OfxImageEffectPropUnmappedFrameRate>(value, 0);
    }

    void setContinuousSamples(bool value) {
        props_.set<PropId::OfxImageClipPropContinuousSamples>(value, 0);
    }

};

// Property set accessor for: EffectDescriptor
class EffectDescriptor : public PropertySetAccessor {
public:
    using PropertySetAccessor::PropertySetAccessor;

    const char* type() const {
        return props_.get<PropId::OfxPropType>(0);
    }

    const char* label() const {
        return props_.get<PropId::OfxPropLabel>(0);
    }

    const char* shortLabel() const {
        return props_.get<PropId::OfxPropShortLabel>(0);
    }

    const char* longLabel() const {
        return props_.get<PropId::OfxPropLongLabel>(0);
    }

    int version(int index = 0) const {
        return props_.get<PropId::OfxPropVersion>(index);
    }

    const char* versionLabel() const {
        return props_.get<PropId::OfxPropVersionLabel>(0);
    }

    const char* pluginDescription() const {
        return props_.get<PropId::OfxPropPluginDescription>(0);
    }

    const char* supportedContexts(int index = 0) const {
        return props_.get<PropId::OfxImageEffectPropSupportedContexts>(index);
    }

    const char* imageEffectPluginPropGrouping() const {
        return props_.get<PropId::OfxImageEffectPluginPropGrouping>(0);
    }

    bool imageEffectPluginPropSingleInstance() const {
        return props_.get<PropId::OfxImageEffectPluginPropSingleInstance>(0);
    }

    const char* imageEffectPluginRenderThreadSafety() const {
        return props_.get<PropId::OfxImageEffectPluginRenderThreadSafety>(0);
    }

    bool imageEffectPluginPropHostFrameThreading() const {
        return props_.get<PropId::OfxImageEffectPluginPropHostFrameThreading>(0);
    }

    void* imageEffectPluginPropOverlayInteractV1() const {
        return props_.get<PropId::OfxImageEffectPluginPropOverlayInteractV1>(0);
    }

    const char* openCLSupported() const {
        return props_.get<PropId::OfxImageEffectPropOpenCLSupported>(0);
    }

    bool supportsMultiResolution() const {
        return props_.get<PropId::OfxImageEffectPropSupportsMultiResolution>(0);
    }

    bool supportsTiles() const {
        return props_.get<PropId::OfxImageEffectPropSupportsTiles>(0);
    }

    bool temporalClipAccess() const {
        return props_.get<PropId::OfxImageEffectPropTemporalClipAccess>(0);
    }

    const char* supportedPixelDepths(int index = 0) const {
        return props_.get<PropId::OfxImageEffectPropSupportedPixelDepths>(index);
    }

    bool imageEffectPluginPropFieldRenderTwiceAlways() const {
        return props_.get<PropId::OfxImageEffectPluginPropFieldRenderTwiceAlways>(0);
    }

    bool multipleClipDepths() const {
        return props_.get<PropId::OfxImageEffectPropMultipleClipDepths>(0);
    }

    bool supportsMultipleClipPARs() const {
        return props_.get<PropId::OfxImageEffectPropSupportsMultipleClipPARs>(0);
    }

    const char* clipPreferencesSlaveParam(int index = 0) const {
        return props_.get<PropId::OfxImageEffectPropClipPreferencesSlaveParam>(index);
    }

    const char* openGLRenderSupported() const {
        return props_.get<PropId::OfxImageEffectPropOpenGLRenderSupported>(0);
    }

    void setFilePath(const char* value) {
        props_.set<PropId::OfxPluginPropFilePath>(value, 0);
    }

    const char* pixelDepth(int index = 0) const {
        return props_.get<PropId::OfxOpenGLPropPixelDepth>(index);
    }

    void* imageEffectPluginPropOverlayInteractV2() const {
        return props_.get<PropId::OfxImageEffectPluginPropOverlayInteractV2>(0);
    }

    const char* colourManagementAvailableConfigs(int index = 0) const {
        return props_.get<PropId::OfxImageEffectPropColourManagementAvailableConfigs>(index);
    }

    const char* colourManagementStyle() const {
        return props_.get<PropId::OfxImageEffectPropColourManagementStyle>(0);
    }

    const char* noSpatialAwareness() const {
        return props_.get<PropId::OfxImageEffectPropNoSpatialAwareness>(0);
    }

};

// Property set accessor for: EffectInstance
class EffectInstance : public PropertySetAccessor {
public:
    using PropertySetAccessor::PropertySetAccessor;

    void setType(const char* value) {
        props_.set<PropId::OfxPropType>(value, 0);
    }

    void setContext(const char* value) {
        props_.set<PropId::OfxImageEffectPropContext>(value, 0);
    }

    void setInstanceData(void* value) {
        props_.set<PropId::OfxPropInstanceData>(value, 0);
    }

    void setProjectSize(const std::array<double, 2>& values) {
        props_.setAll<PropId::OfxImageEffectPropProjectSize>(values);
    }

    void setProjectOffset(const std::array<double, 2>& values) {
        props_.setAll<PropId::OfxImageEffectPropProjectOffset>(values);
    }

    void setProjectExtent(const std::array<double, 2>& values) {
        props_.setAll<PropId::OfxImageEffectPropProjectExtent>(values);
    }

    void setPixelAspectRatio(double value) {
        props_.set<PropId::OfxImageEffectPropPixelAspectRatio>(value, 0);
    }

    void setImageEffectInstancePropEffectDuration(double value) {
        props_.set<PropId::OfxImageEffectInstancePropEffectDuration>(value, 0);
    }

    void setImageEffectInstancePropSequentialRender(bool value) {
        props_.set<PropId::OfxImageEffectInstancePropSequentialRender>(value, 0);
    }

    void setSupportsTiles(bool value) {
        props_.set<PropId::OfxImageEffectPropSupportsTiles>(value, 0);
    }

    void setOpenGLRenderSupported(const char* value) {
        props_.set<PropId::OfxImageEffectPropOpenGLRenderSupported>(value, 0);
    }

    void setFrameRate(double value) {
        props_.set<PropId::OfxImageEffectPropFrameRate>(value, 0);
    }

    void setIsInteractive(bool value) {
        props_.set<PropId::OfxPropIsInteractive>(value, 0);
    }

    void setOCIOConfig(const char* value) {
        props_.set<PropId::OfxImageEffectPropOCIOConfig>(value, 0);
    }

    void setOCIODisplay(const char* value) {
        props_.set<PropId::OfxImageEffectPropOCIODisplay>(value, 0);
    }

    void setOCIOView(const char* value) {
        props_.set<PropId::OfxImageEffectPropOCIOView>(value, 0);
    }

    void setColourManagementConfig(const char* value) {
        props_.set<PropId::OfxImageEffectPropColourManagementConfig>(value, 0);
    }

    void setColourManagementStyle(const char* value) {
        props_.set<PropId::OfxImageEffectPropColourManagementStyle>(value, 0);
    }

    void setDisplayColourspace(const char* value) {
        props_.set<PropId::OfxImageEffectPropDisplayColourspace>(value, 0);
    }

    void setPluginHandle(void* value) {
        props_.set<PropId::OfxImageEffectPropPluginHandle>(value, 0);
    }

};

// Property set accessor for: Image
class Image : public PropertySetAccessor {
public:
    using PropertySetAccessor::PropertySetAccessor;

    void setType(const char* value) {
        props_.set<PropId::OfxPropType>(value, 0);
    }

    void setPixelDepth(const char* value) {
        props_.set<PropId::OfxImageEffectPropPixelDepth>(value, 0);
    }

    void setComponents(const char* value) {
        props_.set<PropId::OfxImageEffectPropComponents>(value, 0);
    }

    void setPreMultiplication(const char* value) {
        props_.set<PropId::OfxImageEffectPropPreMultiplication>(value, 0);
    }

    void setRenderScale(const std::array<double, 2>& values) {
        props_.setAll<PropId::OfxImageEffectPropRenderScale>(values);
    }

    void setPixelAspectRatio(double value) {
        props_.set<PropId::OfxImagePropPixelAspectRatio>(value, 0);
    }

    void setData(void* value) {
        props_.set<PropId::OfxImagePropData>(value, 0);
    }

    void setBounds(const std::array<int, 4>& values) {
        props_.setAll<PropId::OfxImagePropBounds>(values);
    }

    void setRegionOfDefinition(const std::array<int, 4>& values) {
        props_.setAll<PropId::OfxImagePropRegionOfDefinition>(values);
    }

    void setRowBytes(int value) {
        props_.set<PropId::OfxImagePropRowBytes>(value, 0);
    }

    void setField(const char* value) {
        props_.set<PropId::OfxImagePropField>(value, 0);
    }

    void setUniqueIdentifier(const char* value) {
        props_.set<PropId::OfxImagePropUniqueIdentifier>(value, 0);
    }

};

// Property set accessor for: ImageEffectHost
class ImageEffectHost : public PropertySetAccessor {
public:
    using PropertySetAccessor::PropertySetAccessor;

    void setAPIVersion(int value, int index = 0) {
        props_.set<PropId::OfxPropAPIVersion>(value, index);
    }

    void setType(const char* value) {
        props_.set<PropId::OfxPropType>(value, 0);
    }

    void setName(const char* value) {
        props_.set<PropId::OfxPropName>(value, 0);
    }

    void setLabel(const char* value) {
        props_.set<PropId::OfxPropLabel>(value, 0);
    }

    void setVersion(int value, int index = 0) {
        props_.set<PropId::OfxPropVersion>(value, index);
    }

    void setVersionLabel(const char* value) {
        props_.set<PropId::OfxPropVersionLabel>(value, 0);
    }

    void setImageEffectHostPropIsBackground(bool value) {
        props_.set<PropId::OfxImageEffectHostPropIsBackground>(value, 0);
    }

    void setSupportsOverlays(bool value) {
        props_.set<PropId::OfxImageEffectPropSupportsOverlays>(value, 0);
    }

    void setSupportsMultiResolution(bool value) {
        props_.set<PropId::OfxImageEffectPropSupportsMultiResolution>(value, 0);
    }

    void setSupportsTiles(bool value) {
        props_.set<PropId::OfxImageEffectPropSupportsTiles>(value, 0);
    }

    void setTemporalClipAccess(bool value) {
        props_.set<PropId::OfxImageEffectPropTemporalClipAccess>(value, 0);
    }

    void setSupportedComponents(const char* value, int index = 0) {
        props_.set<PropId::OfxImageEffectPropSupportedComponents>(value, index);
    }

    void setSupportedContexts(const char* value, int index = 0) {
        props_.set<PropId::OfxImageEffectPropSupportedContexts>(value, index);
    }

    void setMultipleClipDepths(bool value) {
        props_.set<PropId::OfxImageEffectPropMultipleClipDepths>(value, 0);
    }

    void setOpenCLSupported(const char* value) {
        props_.set<PropId::OfxImageEffectPropOpenCLSupported>(value, 0);
    }

    void setSupportsMultipleClipPARs(bool value) {
        props_.set<PropId::OfxImageEffectPropSupportsMultipleClipPARs>(value, 0);
    }

    void setSetableFrameRate(bool value) {
        props_.set<PropId::OfxImageEffectPropSetableFrameRate>(value, 0);
    }

    void setSetableFielding(bool value) {
        props_.set<PropId::OfxImageEffectPropSetableFielding>(value, 0);
    }

    void setParamHostPropSupportsCustomInteract(bool value) {
        props_.set<PropId::OfxParamHostPropSupportsCustomInteract>(value, 0);
    }

    void setParamHostPropSupportsStringAnimation(bool value) {
        props_.set<PropId::OfxParamHostPropSupportsStringAnimation>(value, 0);
    }

    void setParamHostPropSupportsChoiceAnimation(bool value) {
        props_.set<PropId::OfxParamHostPropSupportsChoiceAnimation>(value, 0);
    }

    void setParamHostPropSupportsBooleanAnimation(bool value) {
        props_.set<PropId::OfxParamHostPropSupportsBooleanAnimation>(value, 0);
    }

    void setParamHostPropSupportsCustomAnimation(bool value) {
        props_.set<PropId::OfxParamHostPropSupportsCustomAnimation>(value, 0);
    }

    void setParamHostPropSupportsStrChoice(bool value) {
        props_.set<PropId::OfxParamHostPropSupportsStrChoice>(value, 0);
    }

    void setParamHostPropSupportsStrChoiceAnimation(bool value) {
        props_.set<PropId::OfxParamHostPropSupportsStrChoiceAnimation>(value, 0);
    }

    void setParamHostPropMaxParameters(int value) {
        props_.set<PropId::OfxParamHostPropMaxParameters>(value, 0);
    }

    void setParamHostPropMaxPages(int value) {
        props_.set<PropId::OfxParamHostPropMaxPages>(value, 0);
    }

    void setParamHostPropPageRowColumnCount(const std::array<int, 2>& values) {
        props_.setAll<PropId::OfxParamHostPropPageRowColumnCount>(values);
    }

    void setHostOSHandle(void* value) {
        props_.set<PropId::OfxPropHostOSHandle>(value, 0);
    }

    void setParamHostPropSupportsParametricAnimation(bool value) {
        props_.set<PropId::OfxParamHostPropSupportsParametricAnimation>(value, 0);
    }

    void setImageEffectInstancePropSequentialRender(bool value) {
        props_.set<PropId::OfxImageEffectInstancePropSequentialRender>(value, 0);
    }

    void setOpenGLRenderSupported(const char* value) {
        props_.set<PropId::OfxImageEffectPropOpenGLRenderSupported>(value, 0);
    }

    void setRenderQualityDraft(bool value) {
        props_.set<PropId::OfxImageEffectPropRenderQualityDraft>(value, 0);
    }

    void setImageEffectHostPropNativeOrigin(const char* value) {
        props_.set<PropId::OfxImageEffectHostPropNativeOrigin>(value, 0);
    }

    void setColourManagementAvailableConfigs(const char* value, int index = 0) {
        props_.set<PropId::OfxImageEffectPropColourManagementAvailableConfigs>(value, index);
    }

    void setColourManagementStyle(const char* value) {
        props_.set<PropId::OfxImageEffectPropColourManagementStyle>(value, 0);
    }

};

// Property set accessor for: InteractDescriptor
class InteractDescriptor : public PropertySetAccessor {
public:
    using PropertySetAccessor::PropertySetAccessor;

    void setInteractPropHasAlpha(bool value) {
        props_.set<PropId::OfxInteractPropHasAlpha>(value, 0);
    }

    void setInteractPropBitDepth(int value) {
        props_.set<PropId::OfxInteractPropBitDepth>(value, 0);
    }

};

// Property set accessor for: InteractInstance
class InteractInstance : public PropertySetAccessor {
public:
    using PropertySetAccessor::PropertySetAccessor;

    void setEffectInstance(void* value) {
        props_.set<PropId::OfxPropEffectInstance>(value, 0);
    }

    void setInstanceData(void* value) {
        props_.set<PropId::OfxPropInstanceData>(value, 0);
    }

    void setInteractPropPixelScale(const std::array<double, 2>& values) {
        props_.setAll<PropId::OfxInteractPropPixelScale>(values);
    }

    void setInteractPropBackgroundColour(const std::array<double, 3>& values) {
        props_.setAll<PropId::OfxInteractPropBackgroundColour>(values);
    }

    void setInteractPropHasAlpha(bool value) {
        props_.set<PropId::OfxInteractPropHasAlpha>(value, 0);
    }

    void setInteractPropBitDepth(int value) {
        props_.set<PropId::OfxInteractPropBitDepth>(value, 0);
    }

    void setInteractPropSlaveToParam(const char* value, int index = 0) {
        props_.set<PropId::OfxInteractPropSlaveToParam>(value, index);
    }

    void setInteractPropSuggestedColour(const std::array<double, 3>& values) {
        props_.setAll<PropId::OfxInteractPropSuggestedColour>(values);
    }

};

// Property set accessor for: ParamDouble1D
class ParamDouble1D : public PropertySetAccessor {
public:
    using PropertySetAccessor::PropertySetAccessor;

    bool showTimeMarker() const {
        return props_.get<PropId::OfxParamPropShowTimeMarker>(0);
    }

    const char* doubleType() const {
        return props_.get<PropId::OfxParamPropDoubleType>(0);
    }

    const char* type() const {
        return props_.get<PropId::OfxPropType>(0);
    }

    const char* name() const {
        return props_.get<PropId::OfxPropName>(0);
    }

    const char* label() const {
        return props_.get<PropId::OfxPropLabel>(0);
    }

    const char* shortLabel() const {
        return props_.get<PropId::OfxPropShortLabel>(0);
    }

    const char* longLabel() const {
        return props_.get<PropId::OfxPropLongLabel>(0);
    }

    bool secret() const {
        return props_.get<PropId::OfxParamPropSecret>(0);
    }

    const char* hint() const {
        return props_.get<PropId::OfxParamPropHint>(0);
    }

    const char* scriptName() const {
        return props_.get<PropId::OfxParamPropScriptName>(0);
    }

    const char* parent() const {
        return props_.get<PropId::OfxParamPropParent>(0);
    }

    bool enabled() const {
        return props_.get<PropId::OfxParamPropEnabled>(0);
    }

    void* dataPtr() const {
        return props_.get<PropId::OfxParamPropDataPtr>(0);
    }

    std::array<const char*, 2> icon() const {
        return props_.getAll<PropId::OfxPropIcon>();
    }

    void* interactV1() const {
        return props_.get<PropId::OfxParamPropInteractV1>(0);
    }

    std::array<double, 2> interactSize() const {
        return props_.getAll<PropId::OfxParamPropInteractSize>();
    }

    double interactSizeAspect() const {
        return props_.get<PropId::OfxParamPropInteractSizeAspect>(0);
    }

    std::array<double, 2> interactMinimumSize() const {
        return props_.getAll<PropId::OfxParamPropInteractMinimumSize>();
    }

    std::array<int, 2> interactPreferedSize() const {
        return props_.getAll<PropId::OfxParamPropInteractPreferedSize>();
    }

    bool hasHostOverlayHandle() const {
        return props_.get<PropId::OfxParamPropHasHostOverlayHandle>(0);
    }

    bool useHostOverlayHandle() const {
        return props_.get<PropId::OfxParamPropUseHostOverlayHandle>(0);
    }

    // Multi-type property (supports: int, double, string, pointer)
    template<typename T>
    T default(int index = 0) const {
        return props_.get<PropId::OfxParamPropDefault, T>(index);
    }

    template<typename T>
    std::vector<T> defaultAll() const {
        return props_.getAll<PropId::OfxParamPropDefault, T>();
    }

    bool animates() const {
        return props_.get<PropId::OfxParamPropAnimates>(0);
    }

    void setIsAnimating(bool value) {
        props_.set<PropId::OfxParamPropIsAnimating>(value, 0);
    }

    void setIsAutoKeying(bool value) {
        props_.set<PropId::OfxParamPropIsAutoKeying>(value, 0);
    }

    bool persistant() const {
        return props_.get<PropId::OfxParamPropPersistant>(0);
    }

    bool evaluateOnChange() const {
        return props_.get<PropId::OfxParamPropEvaluateOnChange>(0);
    }

    bool pluginMayWrite() const {
        return props_.get<PropId::OfxParamPropPluginMayWrite>(0);
    }

    const char* cacheInvalidation() const {
        return props_.get<PropId::OfxParamPropCacheInvalidation>(0);
    }

    bool canUndo() const {
        return props_.get<PropId::OfxParamPropCanUndo>(0);
    }

    // Multi-type property (supports: int, double)
    template<typename T>
    T min(int index = 0) const {
        return props_.get<PropId::OfxParamPropMin, T>(index);
    }

    template<typename T>
    std::vector<T> minAll() const {
        return props_.getAll<PropId::OfxParamPropMin, T>();
    }

    // Multi-type property (supports: int, double)
    template<typename T>
    T max(int index = 0) const {
        return props_.get<PropId::OfxParamPropMax, T>(index);
    }

    template<typename T>
    std::vector<T> maxAll() const {
        return props_.getAll<PropId::OfxParamPropMax, T>();
    }

    // Multi-type property (supports: int, double)
    template<typename T>
    T displayMin(int index = 0) const {
        return props_.get<PropId::OfxParamPropDisplayMin, T>(index);
    }

    template<typename T>
    std::vector<T> displayMinAll() const {
        return props_.getAll<PropId::OfxParamPropDisplayMin, T>();
    }

    // Multi-type property (supports: int, double)
    template<typename T>
    T displayMax(int index = 0) const {
        return props_.get<PropId::OfxParamPropDisplayMax, T>(index);
    }

    template<typename T>
    std::vector<T> displayMaxAll() const {
        return props_.getAll<PropId::OfxParamPropDisplayMax, T>();
    }

    double increment() const {
        return props_.get<PropId::OfxParamPropIncrement>(0);
    }

    int digits() const {
        return props_.get<PropId::OfxParamPropDigits>(0);
    }

};

// Property set accessor for: ParameterSet
class ParameterSet : public PropertySetAccessor {
public:
    using PropertySetAccessor::PropertySetAccessor;

    bool paramSetNeedsSyncing() const {
        return props_.get<PropId::OfxPropParamSetNeedsSyncing>(0);
    }

    const char* paramPageOrder(int index = 0) const {
        return props_.get<PropId::OfxPluginPropParamPageOrder>(index);
    }

};

// Property set accessor for: ParamsByte
class ParamsByte : public PropertySetAccessor {
public:
    using PropertySetAccessor::PropertySetAccessor;

    const char* type() const {
        return props_.get<PropId::OfxPropType>(0);
    }

    const char* name() const {
        return props_.get<PropId::OfxPropName>(0);
    }

    const char* label() const {
        return props_.get<PropId::OfxPropLabel>(0);
    }

    const char* shortLabel() const {
        return props_.get<PropId::OfxPropShortLabel>(0);
    }

    const char* longLabel() const {
        return props_.get<PropId::OfxPropLongLabel>(0);
    }

    bool secret() const {
        return props_.get<PropId::OfxParamPropSecret>(0);
    }

    const char* hint() const {
        return props_.get<PropId::OfxParamPropHint>(0);
    }

    const char* scriptName() const {
        return props_.get<PropId::OfxParamPropScriptName>(0);
    }

    const char* parent() const {
        return props_.get<PropId::OfxParamPropParent>(0);
    }

    bool enabled() const {
        return props_.get<PropId::OfxParamPropEnabled>(0);
    }

    void* dataPtr() const {
        return props_.get<PropId::OfxParamPropDataPtr>(0);
    }

    std::array<const char*, 2> icon() const {
        return props_.getAll<PropId::OfxPropIcon>();
    }

    void* interactV1() const {
        return props_.get<PropId::OfxParamPropInteractV1>(0);
    }

    std::array<double, 2> interactSize() const {
        return props_.getAll<PropId::OfxParamPropInteractSize>();
    }

    double interactSizeAspect() const {
        return props_.get<PropId::OfxParamPropInteractSizeAspect>(0);
    }

    std::array<double, 2> interactMinimumSize() const {
        return props_.getAll<PropId::OfxParamPropInteractMinimumSize>();
    }

    std::array<int, 2> interactPreferedSize() const {
        return props_.getAll<PropId::OfxParamPropInteractPreferedSize>();
    }

    bool hasHostOverlayHandle() const {
        return props_.get<PropId::OfxParamPropHasHostOverlayHandle>(0);
    }

    bool useHostOverlayHandle() const {
        return props_.get<PropId::OfxParamPropUseHostOverlayHandle>(0);
    }

    // Multi-type property (supports: int, double, string, pointer)
    template<typename T>
    T default(int index = 0) const {
        return props_.get<PropId::OfxParamPropDefault, T>(index);
    }

    template<typename T>
    std::vector<T> defaultAll() const {
        return props_.getAll<PropId::OfxParamPropDefault, T>();
    }

    bool animates() const {
        return props_.get<PropId::OfxParamPropAnimates>(0);
    }

    void setIsAnimating(bool value) {
        props_.set<PropId::OfxParamPropIsAnimating>(value, 0);
    }

    void setIsAutoKeying(bool value) {
        props_.set<PropId::OfxParamPropIsAutoKeying>(value, 0);
    }

    bool persistant() const {
        return props_.get<PropId::OfxParamPropPersistant>(0);
    }

    bool evaluateOnChange() const {
        return props_.get<PropId::OfxParamPropEvaluateOnChange>(0);
    }

    bool pluginMayWrite() const {
        return props_.get<PropId::OfxParamPropPluginMayWrite>(0);
    }

    const char* cacheInvalidation() const {
        return props_.get<PropId::OfxParamPropCacheInvalidation>(0);
    }

    bool canUndo() const {
        return props_.get<PropId::OfxParamPropCanUndo>(0);
    }

    // Multi-type property (supports: int, double)
    template<typename T>
    T min(int index = 0) const {
        return props_.get<PropId::OfxParamPropMin, T>(index);
    }

    template<typename T>
    std::vector<T> minAll() const {
        return props_.getAll<PropId::OfxParamPropMin, T>();
    }

    // Multi-type property (supports: int, double)
    template<typename T>
    T max(int index = 0) const {
        return props_.get<PropId::OfxParamPropMax, T>(index);
    }

    template<typename T>
    std::vector<T> maxAll() const {
        return props_.getAll<PropId::OfxParamPropMax, T>();
    }

    // Multi-type property (supports: int, double)
    template<typename T>
    T displayMin(int index = 0) const {
        return props_.get<PropId::OfxParamPropDisplayMin, T>(index);
    }

    template<typename T>
    std::vector<T> displayMinAll() const {
        return props_.getAll<PropId::OfxParamPropDisplayMin, T>();
    }

    // Multi-type property (supports: int, double)
    template<typename T>
    T displayMax(int index = 0) const {
        return props_.get<PropId::OfxParamPropDisplayMax, T>(index);
    }

    template<typename T>
    std::vector<T> displayMaxAll() const {
        return props_.getAll<PropId::OfxParamPropDisplayMax, T>();
    }

};

// Property set accessor for: ParamsChoice
class ParamsChoice : public PropertySetAccessor {
public:
    using PropertySetAccessor::PropertySetAccessor;

    const char* choiceOption(int index = 0) const {
        return props_.get<PropId::OfxParamPropChoiceOption>(index);
    }

    int choiceOrder(int index = 0) const {
        return props_.get<PropId::OfxParamPropChoiceOrder>(index);
    }

    const char* type() const {
        return props_.get<PropId::OfxPropType>(0);
    }

    const char* name() const {
        return props_.get<PropId::OfxPropName>(0);
    }

    const char* label() const {
        return props_.get<PropId::OfxPropLabel>(0);
    }

    const char* shortLabel() const {
        return props_.get<PropId::OfxPropShortLabel>(0);
    }

    const char* longLabel() const {
        return props_.get<PropId::OfxPropLongLabel>(0);
    }

    bool secret() const {
        return props_.get<PropId::OfxParamPropSecret>(0);
    }

    const char* hint() const {
        return props_.get<PropId::OfxParamPropHint>(0);
    }

    const char* scriptName() const {
        return props_.get<PropId::OfxParamPropScriptName>(0);
    }

    const char* parent() const {
        return props_.get<PropId::OfxParamPropParent>(0);
    }

    bool enabled() const {
        return props_.get<PropId::OfxParamPropEnabled>(0);
    }

    void* dataPtr() const {
        return props_.get<PropId::OfxParamPropDataPtr>(0);
    }

    std::array<const char*, 2> icon() const {
        return props_.getAll<PropId::OfxPropIcon>();
    }

    void* interactV1() const {
        return props_.get<PropId::OfxParamPropInteractV1>(0);
    }

    std::array<double, 2> interactSize() const {
        return props_.getAll<PropId::OfxParamPropInteractSize>();
    }

    double interactSizeAspect() const {
        return props_.get<PropId::OfxParamPropInteractSizeAspect>(0);
    }

    std::array<double, 2> interactMinimumSize() const {
        return props_.getAll<PropId::OfxParamPropInteractMinimumSize>();
    }

    std::array<int, 2> interactPreferedSize() const {
        return props_.getAll<PropId::OfxParamPropInteractPreferedSize>();
    }

    bool hasHostOverlayHandle() const {
        return props_.get<PropId::OfxParamPropHasHostOverlayHandle>(0);
    }

    bool useHostOverlayHandle() const {
        return props_.get<PropId::OfxParamPropUseHostOverlayHandle>(0);
    }

    // Multi-type property (supports: int, double, string, pointer)
    template<typename T>
    T default(int index = 0) const {
        return props_.get<PropId::OfxParamPropDefault, T>(index);
    }

    template<typename T>
    std::vector<T> defaultAll() const {
        return props_.getAll<PropId::OfxParamPropDefault, T>();
    }

    bool animates() const {
        return props_.get<PropId::OfxParamPropAnimates>(0);
    }

    void setIsAnimating(bool value) {
        props_.set<PropId::OfxParamPropIsAnimating>(value, 0);
    }

    void setIsAutoKeying(bool value) {
        props_.set<PropId::OfxParamPropIsAutoKeying>(value, 0);
    }

    bool persistant() const {
        return props_.get<PropId::OfxParamPropPersistant>(0);
    }

    bool evaluateOnChange() const {
        return props_.get<PropId::OfxParamPropEvaluateOnChange>(0);
    }

    bool pluginMayWrite() const {
        return props_.get<PropId::OfxParamPropPluginMayWrite>(0);
    }

    const char* cacheInvalidation() const {
        return props_.get<PropId::OfxParamPropCacheInvalidation>(0);
    }

    bool canUndo() const {
        return props_.get<PropId::OfxParamPropCanUndo>(0);
    }

};

// Property set accessor for: ParamsCustom
class ParamsCustom : public PropertySetAccessor {
public:
    using PropertySetAccessor::PropertySetAccessor;

    void* customCallbackV1() const {
        return props_.get<PropId::OfxParamPropCustomCallbackV1>(0);
    }

    const char* type() const {
        return props_.get<PropId::OfxPropType>(0);
    }

    const char* name() const {
        return props_.get<PropId::OfxPropName>(0);
    }

    const char* label() const {
        return props_.get<PropId::OfxPropLabel>(0);
    }

    const char* shortLabel() const {
        return props_.get<PropId::OfxPropShortLabel>(0);
    }

    const char* longLabel() const {
        return props_.get<PropId::OfxPropLongLabel>(0);
    }

    bool secret() const {
        return props_.get<PropId::OfxParamPropSecret>(0);
    }

    const char* hint() const {
        return props_.get<PropId::OfxParamPropHint>(0);
    }

    const char* scriptName() const {
        return props_.get<PropId::OfxParamPropScriptName>(0);
    }

    const char* parent() const {
        return props_.get<PropId::OfxParamPropParent>(0);
    }

    bool enabled() const {
        return props_.get<PropId::OfxParamPropEnabled>(0);
    }

    void* dataPtr() const {
        return props_.get<PropId::OfxParamPropDataPtr>(0);
    }

    std::array<const char*, 2> icon() const {
        return props_.getAll<PropId::OfxPropIcon>();
    }

    void* interactV1() const {
        return props_.get<PropId::OfxParamPropInteractV1>(0);
    }

    std::array<double, 2> interactSize() const {
        return props_.getAll<PropId::OfxParamPropInteractSize>();
    }

    double interactSizeAspect() const {
        return props_.get<PropId::OfxParamPropInteractSizeAspect>(0);
    }

    std::array<double, 2> interactMinimumSize() const {
        return props_.getAll<PropId::OfxParamPropInteractMinimumSize>();
    }

    std::array<int, 2> interactPreferedSize() const {
        return props_.getAll<PropId::OfxParamPropInteractPreferedSize>();
    }

    bool hasHostOverlayHandle() const {
        return props_.get<PropId::OfxParamPropHasHostOverlayHandle>(0);
    }

    bool useHostOverlayHandle() const {
        return props_.get<PropId::OfxParamPropUseHostOverlayHandle>(0);
    }

    // Multi-type property (supports: int, double, string, pointer)
    template<typename T>
    T default(int index = 0) const {
        return props_.get<PropId::OfxParamPropDefault, T>(index);
    }

    template<typename T>
    std::vector<T> defaultAll() const {
        return props_.getAll<PropId::OfxParamPropDefault, T>();
    }

    bool animates() const {
        return props_.get<PropId::OfxParamPropAnimates>(0);
    }

    void setIsAnimating(bool value) {
        props_.set<PropId::OfxParamPropIsAnimating>(value, 0);
    }

    void setIsAutoKeying(bool value) {
        props_.set<PropId::OfxParamPropIsAutoKeying>(value, 0);
    }

    bool persistant() const {
        return props_.get<PropId::OfxParamPropPersistant>(0);
    }

    bool evaluateOnChange() const {
        return props_.get<PropId::OfxParamPropEvaluateOnChange>(0);
    }

    bool pluginMayWrite() const {
        return props_.get<PropId::OfxParamPropPluginMayWrite>(0);
    }

    const char* cacheInvalidation() const {
        return props_.get<PropId::OfxParamPropCacheInvalidation>(0);
    }

    bool canUndo() const {
        return props_.get<PropId::OfxParamPropCanUndo>(0);
    }

};

// Property set accessor for: ParamsDouble2D3D
class ParamsDouble2D3D : public PropertySetAccessor {
public:
    using PropertySetAccessor::PropertySetAccessor;

    const char* doubleType() const {
        return props_.get<PropId::OfxParamPropDoubleType>(0);
    }

    const char* type() const {
        return props_.get<PropId::OfxPropType>(0);
    }

    const char* name() const {
        return props_.get<PropId::OfxPropName>(0);
    }

    const char* label() const {
        return props_.get<PropId::OfxPropLabel>(0);
    }

    const char* shortLabel() const {
        return props_.get<PropId::OfxPropShortLabel>(0);
    }

    const char* longLabel() const {
        return props_.get<PropId::OfxPropLongLabel>(0);
    }

    bool secret() const {
        return props_.get<PropId::OfxParamPropSecret>(0);
    }

    const char* hint() const {
        return props_.get<PropId::OfxParamPropHint>(0);
    }

    const char* scriptName() const {
        return props_.get<PropId::OfxParamPropScriptName>(0);
    }

    const char* parent() const {
        return props_.get<PropId::OfxParamPropParent>(0);
    }

    bool enabled() const {
        return props_.get<PropId::OfxParamPropEnabled>(0);
    }

    void* dataPtr() const {
        return props_.get<PropId::OfxParamPropDataPtr>(0);
    }

    std::array<const char*, 2> icon() const {
        return props_.getAll<PropId::OfxPropIcon>();
    }

    void* interactV1() const {
        return props_.get<PropId::OfxParamPropInteractV1>(0);
    }

    std::array<double, 2> interactSize() const {
        return props_.getAll<PropId::OfxParamPropInteractSize>();
    }

    double interactSizeAspect() const {
        return props_.get<PropId::OfxParamPropInteractSizeAspect>(0);
    }

    std::array<double, 2> interactMinimumSize() const {
        return props_.getAll<PropId::OfxParamPropInteractMinimumSize>();
    }

    std::array<int, 2> interactPreferedSize() const {
        return props_.getAll<PropId::OfxParamPropInteractPreferedSize>();
    }

    bool hasHostOverlayHandle() const {
        return props_.get<PropId::OfxParamPropHasHostOverlayHandle>(0);
    }

    bool useHostOverlayHandle() const {
        return props_.get<PropId::OfxParamPropUseHostOverlayHandle>(0);
    }

    // Multi-type property (supports: int, double, string, pointer)
    template<typename T>
    T default(int index = 0) const {
        return props_.get<PropId::OfxParamPropDefault, T>(index);
    }

    template<typename T>
    std::vector<T> defaultAll() const {
        return props_.getAll<PropId::OfxParamPropDefault, T>();
    }

    bool animates() const {
        return props_.get<PropId::OfxParamPropAnimates>(0);
    }

    void setIsAnimating(bool value) {
        props_.set<PropId::OfxParamPropIsAnimating>(value, 0);
    }

    void setIsAutoKeying(bool value) {
        props_.set<PropId::OfxParamPropIsAutoKeying>(value, 0);
    }

    bool persistant() const {
        return props_.get<PropId::OfxParamPropPersistant>(0);
    }

    bool evaluateOnChange() const {
        return props_.get<PropId::OfxParamPropEvaluateOnChange>(0);
    }

    bool pluginMayWrite() const {
        return props_.get<PropId::OfxParamPropPluginMayWrite>(0);
    }

    const char* cacheInvalidation() const {
        return props_.get<PropId::OfxParamPropCacheInvalidation>(0);
    }

    bool canUndo() const {
        return props_.get<PropId::OfxParamPropCanUndo>(0);
    }

    // Multi-type property (supports: int, double)
    template<typename T>
    T min(int index = 0) const {
        return props_.get<PropId::OfxParamPropMin, T>(index);
    }

    template<typename T>
    std::vector<T> minAll() const {
        return props_.getAll<PropId::OfxParamPropMin, T>();
    }

    // Multi-type property (supports: int, double)
    template<typename T>
    T max(int index = 0) const {
        return props_.get<PropId::OfxParamPropMax, T>(index);
    }

    template<typename T>
    std::vector<T> maxAll() const {
        return props_.getAll<PropId::OfxParamPropMax, T>();
    }

    // Multi-type property (supports: int, double)
    template<typename T>
    T displayMin(int index = 0) const {
        return props_.get<PropId::OfxParamPropDisplayMin, T>(index);
    }

    template<typename T>
    std::vector<T> displayMinAll() const {
        return props_.getAll<PropId::OfxParamPropDisplayMin, T>();
    }

    // Multi-type property (supports: int, double)
    template<typename T>
    T displayMax(int index = 0) const {
        return props_.get<PropId::OfxParamPropDisplayMax, T>(index);
    }

    template<typename T>
    std::vector<T> displayMaxAll() const {
        return props_.getAll<PropId::OfxParamPropDisplayMax, T>();
    }

    double increment() const {
        return props_.get<PropId::OfxParamPropIncrement>(0);
    }

    int digits() const {
        return props_.get<PropId::OfxParamPropDigits>(0);
    }

};

// Property set accessor for: ParamsGroup
class ParamsGroup : public PropertySetAccessor {
public:
    using PropertySetAccessor::PropertySetAccessor;

    bool groupOpen() const {
        return props_.get<PropId::OfxParamPropGroupOpen>(0);
    }

    const char* type() const {
        return props_.get<PropId::OfxPropType>(0);
    }

    const char* name() const {
        return props_.get<PropId::OfxPropName>(0);
    }

    const char* label() const {
        return props_.get<PropId::OfxPropLabel>(0);
    }

    const char* shortLabel() const {
        return props_.get<PropId::OfxPropShortLabel>(0);
    }

    const char* longLabel() const {
        return props_.get<PropId::OfxPropLongLabel>(0);
    }

    bool secret() const {
        return props_.get<PropId::OfxParamPropSecret>(0);
    }

    const char* hint() const {
        return props_.get<PropId::OfxParamPropHint>(0);
    }

    const char* scriptName() const {
        return props_.get<PropId::OfxParamPropScriptName>(0);
    }

    const char* parent() const {
        return props_.get<PropId::OfxParamPropParent>(0);
    }

    bool enabled() const {
        return props_.get<PropId::OfxParamPropEnabled>(0);
    }

    void* dataPtr() const {
        return props_.get<PropId::OfxParamPropDataPtr>(0);
    }

    std::array<const char*, 2> icon() const {
        return props_.getAll<PropId::OfxPropIcon>();
    }

};

// Property set accessor for: ParamsInt2D3D
class ParamsInt2D3D : public PropertySetAccessor {
public:
    using PropertySetAccessor::PropertySetAccessor;

    const char* dimensionLabel() const {
        return props_.get<PropId::OfxParamPropDimensionLabel>(0);
    }

    const char* type() const {
        return props_.get<PropId::OfxPropType>(0);
    }

    const char* name() const {
        return props_.get<PropId::OfxPropName>(0);
    }

    const char* label() const {
        return props_.get<PropId::OfxPropLabel>(0);
    }

    const char* shortLabel() const {
        return props_.get<PropId::OfxPropShortLabel>(0);
    }

    const char* longLabel() const {
        return props_.get<PropId::OfxPropLongLabel>(0);
    }

    bool secret() const {
        return props_.get<PropId::OfxParamPropSecret>(0);
    }

    const char* hint() const {
        return props_.get<PropId::OfxParamPropHint>(0);
    }

    const char* scriptName() const {
        return props_.get<PropId::OfxParamPropScriptName>(0);
    }

    const char* parent() const {
        return props_.get<PropId::OfxParamPropParent>(0);
    }

    bool enabled() const {
        return props_.get<PropId::OfxParamPropEnabled>(0);
    }

    void* dataPtr() const {
        return props_.get<PropId::OfxParamPropDataPtr>(0);
    }

    std::array<const char*, 2> icon() const {
        return props_.getAll<PropId::OfxPropIcon>();
    }

    void* interactV1() const {
        return props_.get<PropId::OfxParamPropInteractV1>(0);
    }

    std::array<double, 2> interactSize() const {
        return props_.getAll<PropId::OfxParamPropInteractSize>();
    }

    double interactSizeAspect() const {
        return props_.get<PropId::OfxParamPropInteractSizeAspect>(0);
    }

    std::array<double, 2> interactMinimumSize() const {
        return props_.getAll<PropId::OfxParamPropInteractMinimumSize>();
    }

    std::array<int, 2> interactPreferedSize() const {
        return props_.getAll<PropId::OfxParamPropInteractPreferedSize>();
    }

    bool hasHostOverlayHandle() const {
        return props_.get<PropId::OfxParamPropHasHostOverlayHandle>(0);
    }

    bool useHostOverlayHandle() const {
        return props_.get<PropId::OfxParamPropUseHostOverlayHandle>(0);
    }

    // Multi-type property (supports: int, double, string, pointer)
    template<typename T>
    T default(int index = 0) const {
        return props_.get<PropId::OfxParamPropDefault, T>(index);
    }

    template<typename T>
    std::vector<T> defaultAll() const {
        return props_.getAll<PropId::OfxParamPropDefault, T>();
    }

    bool animates() const {
        return props_.get<PropId::OfxParamPropAnimates>(0);
    }

    void setIsAnimating(bool value) {
        props_.set<PropId::OfxParamPropIsAnimating>(value, 0);
    }

    void setIsAutoKeying(bool value) {
        props_.set<PropId::OfxParamPropIsAutoKeying>(value, 0);
    }

    bool persistant() const {
        return props_.get<PropId::OfxParamPropPersistant>(0);
    }

    bool evaluateOnChange() const {
        return props_.get<PropId::OfxParamPropEvaluateOnChange>(0);
    }

    bool pluginMayWrite() const {
        return props_.get<PropId::OfxParamPropPluginMayWrite>(0);
    }

    const char* cacheInvalidation() const {
        return props_.get<PropId::OfxParamPropCacheInvalidation>(0);
    }

    bool canUndo() const {
        return props_.get<PropId::OfxParamPropCanUndo>(0);
    }

    // Multi-type property (supports: int, double)
    template<typename T>
    T min(int index = 0) const {
        return props_.get<PropId::OfxParamPropMin, T>(index);
    }

    template<typename T>
    std::vector<T> minAll() const {
        return props_.getAll<PropId::OfxParamPropMin, T>();
    }

    // Multi-type property (supports: int, double)
    template<typename T>
    T max(int index = 0) const {
        return props_.get<PropId::OfxParamPropMax, T>(index);
    }

    template<typename T>
    std::vector<T> maxAll() const {
        return props_.getAll<PropId::OfxParamPropMax, T>();
    }

    // Multi-type property (supports: int, double)
    template<typename T>
    T displayMin(int index = 0) const {
        return props_.get<PropId::OfxParamPropDisplayMin, T>(index);
    }

    template<typename T>
    std::vector<T> displayMinAll() const {
        return props_.getAll<PropId::OfxParamPropDisplayMin, T>();
    }

    // Multi-type property (supports: int, double)
    template<typename T>
    T displayMax(int index = 0) const {
        return props_.get<PropId::OfxParamPropDisplayMax, T>(index);
    }

    template<typename T>
    std::vector<T> displayMaxAll() const {
        return props_.getAll<PropId::OfxParamPropDisplayMax, T>();
    }

};

// Property set accessor for: ParamsNormalizedSpatial
class ParamsNormalizedSpatial : public PropertySetAccessor {
public:
    using PropertySetAccessor::PropertySetAccessor;

    const char* defaultCoordinateSystem() const {
        return props_.get<PropId::OfxParamPropDefaultCoordinateSystem>(0);
    }

    const char* type() const {
        return props_.get<PropId::OfxPropType>(0);
    }

    const char* name() const {
        return props_.get<PropId::OfxPropName>(0);
    }

    const char* label() const {
        return props_.get<PropId::OfxPropLabel>(0);
    }

    const char* shortLabel() const {
        return props_.get<PropId::OfxPropShortLabel>(0);
    }

    const char* longLabel() const {
        return props_.get<PropId::OfxPropLongLabel>(0);
    }

    bool secret() const {
        return props_.get<PropId::OfxParamPropSecret>(0);
    }

    const char* hint() const {
        return props_.get<PropId::OfxParamPropHint>(0);
    }

    const char* scriptName() const {
        return props_.get<PropId::OfxParamPropScriptName>(0);
    }

    const char* parent() const {
        return props_.get<PropId::OfxParamPropParent>(0);
    }

    bool enabled() const {
        return props_.get<PropId::OfxParamPropEnabled>(0);
    }

    void* dataPtr() const {
        return props_.get<PropId::OfxParamPropDataPtr>(0);
    }

    std::array<const char*, 2> icon() const {
        return props_.getAll<PropId::OfxPropIcon>();
    }

    void* interactV1() const {
        return props_.get<PropId::OfxParamPropInteractV1>(0);
    }

    std::array<double, 2> interactSize() const {
        return props_.getAll<PropId::OfxParamPropInteractSize>();
    }

    double interactSizeAspect() const {
        return props_.get<PropId::OfxParamPropInteractSizeAspect>(0);
    }

    std::array<double, 2> interactMinimumSize() const {
        return props_.getAll<PropId::OfxParamPropInteractMinimumSize>();
    }

    std::array<int, 2> interactPreferedSize() const {
        return props_.getAll<PropId::OfxParamPropInteractPreferedSize>();
    }

    bool hasHostOverlayHandle() const {
        return props_.get<PropId::OfxParamPropHasHostOverlayHandle>(0);
    }

    bool useHostOverlayHandle() const {
        return props_.get<PropId::OfxParamPropUseHostOverlayHandle>(0);
    }

    // Multi-type property (supports: int, double, string, pointer)
    template<typename T>
    T default(int index = 0) const {
        return props_.get<PropId::OfxParamPropDefault, T>(index);
    }

    template<typename T>
    std::vector<T> defaultAll() const {
        return props_.getAll<PropId::OfxParamPropDefault, T>();
    }

    bool animates() const {
        return props_.get<PropId::OfxParamPropAnimates>(0);
    }

    void setIsAnimating(bool value) {
        props_.set<PropId::OfxParamPropIsAnimating>(value, 0);
    }

    void setIsAutoKeying(bool value) {
        props_.set<PropId::OfxParamPropIsAutoKeying>(value, 0);
    }

    bool persistant() const {
        return props_.get<PropId::OfxParamPropPersistant>(0);
    }

    bool evaluateOnChange() const {
        return props_.get<PropId::OfxParamPropEvaluateOnChange>(0);
    }

    bool pluginMayWrite() const {
        return props_.get<PropId::OfxParamPropPluginMayWrite>(0);
    }

    const char* cacheInvalidation() const {
        return props_.get<PropId::OfxParamPropCacheInvalidation>(0);
    }

    bool canUndo() const {
        return props_.get<PropId::OfxParamPropCanUndo>(0);
    }

    // Multi-type property (supports: int, double)
    template<typename T>
    T min(int index = 0) const {
        return props_.get<PropId::OfxParamPropMin, T>(index);
    }

    template<typename T>
    std::vector<T> minAll() const {
        return props_.getAll<PropId::OfxParamPropMin, T>();
    }

    // Multi-type property (supports: int, double)
    template<typename T>
    T max(int index = 0) const {
        return props_.get<PropId::OfxParamPropMax, T>(index);
    }

    template<typename T>
    std::vector<T> maxAll() const {
        return props_.getAll<PropId::OfxParamPropMax, T>();
    }

    // Multi-type property (supports: int, double)
    template<typename T>
    T displayMin(int index = 0) const {
        return props_.get<PropId::OfxParamPropDisplayMin, T>(index);
    }

    template<typename T>
    std::vector<T> displayMinAll() const {
        return props_.getAll<PropId::OfxParamPropDisplayMin, T>();
    }

    // Multi-type property (supports: int, double)
    template<typename T>
    T displayMax(int index = 0) const {
        return props_.get<PropId::OfxParamPropDisplayMax, T>(index);
    }

    template<typename T>
    std::vector<T> displayMaxAll() const {
        return props_.getAll<PropId::OfxParamPropDisplayMax, T>();
    }

    double increment() const {
        return props_.get<PropId::OfxParamPropIncrement>(0);
    }

    int digits() const {
        return props_.get<PropId::OfxParamPropDigits>(0);
    }

};

// Property set accessor for: ParamsPage
class ParamsPage : public PropertySetAccessor {
public:
    using PropertySetAccessor::PropertySetAccessor;

    const char* pageChild(int index = 0) const {
        return props_.get<PropId::OfxParamPropPageChild>(index);
    }

    const char* type() const {
        return props_.get<PropId::OfxPropType>(0);
    }

    const char* name() const {
        return props_.get<PropId::OfxPropName>(0);
    }

    const char* label() const {
        return props_.get<PropId::OfxPropLabel>(0);
    }

    const char* shortLabel() const {
        return props_.get<PropId::OfxPropShortLabel>(0);
    }

    const char* longLabel() const {
        return props_.get<PropId::OfxPropLongLabel>(0);
    }

    bool secret() const {
        return props_.get<PropId::OfxParamPropSecret>(0);
    }

    const char* hint() const {
        return props_.get<PropId::OfxParamPropHint>(0);
    }

    const char* scriptName() const {
        return props_.get<PropId::OfxParamPropScriptName>(0);
    }

    const char* parent() const {
        return props_.get<PropId::OfxParamPropParent>(0);
    }

    bool enabled() const {
        return props_.get<PropId::OfxParamPropEnabled>(0);
    }

    void* dataPtr() const {
        return props_.get<PropId::OfxParamPropDataPtr>(0);
    }

    std::array<const char*, 2> icon() const {
        return props_.getAll<PropId::OfxPropIcon>();
    }

};

// Property set accessor for: ParamsParametric
class ParamsParametric : public PropertySetAccessor {
public:
    using PropertySetAccessor::PropertySetAccessor;

    bool animates() const {
        return props_.get<PropId::OfxParamPropAnimates>(0);
    }

    bool isAnimating() const {
        return props_.get<PropId::OfxParamPropIsAnimating>(0);
    }

    bool isAutoKeying() const {
        return props_.get<PropId::OfxParamPropIsAutoKeying>(0);
    }

    bool persistant() const {
        return props_.get<PropId::OfxParamPropPersistant>(0);
    }

    bool evaluateOnChange() const {
        return props_.get<PropId::OfxParamPropEvaluateOnChange>(0);
    }

    bool pluginMayWrite() const {
        return props_.get<PropId::OfxParamPropPluginMayWrite>(0);
    }

    const char* cacheInvalidation() const {
        return props_.get<PropId::OfxParamPropCacheInvalidation>(0);
    }

    bool canUndo() const {
        return props_.get<PropId::OfxParamPropCanUndo>(0);
    }

    int parametricDimension() const {
        return props_.get<PropId::OfxParamPropParametricDimension>(0);
    }

    double parametricUIColour(int index = 0) const {
        return props_.get<PropId::OfxParamPropParametricUIColour>(index);
    }

    void* parametricInteractBackground() const {
        return props_.get<PropId::OfxParamPropParametricInteractBackground>(0);
    }

    std::array<double, 2> parametricRange() const {
        return props_.getAll<PropId::OfxParamPropParametricRange>();
    }

    const char* type() const {
        return props_.get<PropId::OfxPropType>(0);
    }

    const char* name() const {
        return props_.get<PropId::OfxPropName>(0);
    }

    const char* label() const {
        return props_.get<PropId::OfxPropLabel>(0);
    }

    const char* shortLabel() const {
        return props_.get<PropId::OfxPropShortLabel>(0);
    }

    const char* longLabel() const {
        return props_.get<PropId::OfxPropLongLabel>(0);
    }

    bool secret() const {
        return props_.get<PropId::OfxParamPropSecret>(0);
    }

    const char* hint() const {
        return props_.get<PropId::OfxParamPropHint>(0);
    }

    const char* scriptName() const {
        return props_.get<PropId::OfxParamPropScriptName>(0);
    }

    const char* parent() const {
        return props_.get<PropId::OfxParamPropParent>(0);
    }

    bool enabled() const {
        return props_.get<PropId::OfxParamPropEnabled>(0);
    }

    void* dataPtr() const {
        return props_.get<PropId::OfxParamPropDataPtr>(0);
    }

    std::array<const char*, 2> icon() const {
        return props_.getAll<PropId::OfxPropIcon>();
    }

    void* interactV1() const {
        return props_.get<PropId::OfxParamPropInteractV1>(0);
    }

    std::array<double, 2> interactSize() const {
        return props_.getAll<PropId::OfxParamPropInteractSize>();
    }

    double interactSizeAspect() const {
        return props_.get<PropId::OfxParamPropInteractSizeAspect>(0);
    }

    std::array<double, 2> interactMinimumSize() const {
        return props_.getAll<PropId::OfxParamPropInteractMinimumSize>();
    }

    std::array<int, 2> interactPreferedSize() const {
        return props_.getAll<PropId::OfxParamPropInteractPreferedSize>();
    }

    bool hasHostOverlayHandle() const {
        return props_.get<PropId::OfxParamPropHasHostOverlayHandle>(0);
    }

    bool useHostOverlayHandle() const {
        return props_.get<PropId::OfxParamPropUseHostOverlayHandle>(0);
    }

    // Multi-type property (supports: int, double, string, pointer)
    template<typename T>
    T default(int index = 0) const {
        return props_.get<PropId::OfxParamPropDefault, T>(index);
    }

    template<typename T>
    std::vector<T> defaultAll() const {
        return props_.getAll<PropId::OfxParamPropDefault, T>();
    }

};

// Property set accessor for: ParamsStrChoice
class ParamsStrChoice : public PropertySetAccessor {
public:
    using PropertySetAccessor::PropertySetAccessor;

    const char* choiceOption(int index = 0) const {
        return props_.get<PropId::OfxParamPropChoiceOption>(index);
    }

    bool choiceEnum() const {
        return props_.get<PropId::OfxParamPropChoiceEnum>(0);
    }

    const char* type() const {
        return props_.get<PropId::OfxPropType>(0);
    }

    const char* name() const {
        return props_.get<PropId::OfxPropName>(0);
    }

    const char* label() const {
        return props_.get<PropId::OfxPropLabel>(0);
    }

    const char* shortLabel() const {
        return props_.get<PropId::OfxPropShortLabel>(0);
    }

    const char* longLabel() const {
        return props_.get<PropId::OfxPropLongLabel>(0);
    }

    bool secret() const {
        return props_.get<PropId::OfxParamPropSecret>(0);
    }

    const char* hint() const {
        return props_.get<PropId::OfxParamPropHint>(0);
    }

    const char* scriptName() const {
        return props_.get<PropId::OfxParamPropScriptName>(0);
    }

    const char* parent() const {
        return props_.get<PropId::OfxParamPropParent>(0);
    }

    bool enabled() const {
        return props_.get<PropId::OfxParamPropEnabled>(0);
    }

    void* dataPtr() const {
        return props_.get<PropId::OfxParamPropDataPtr>(0);
    }

    std::array<const char*, 2> icon() const {
        return props_.getAll<PropId::OfxPropIcon>();
    }

    void* interactV1() const {
        return props_.get<PropId::OfxParamPropInteractV1>(0);
    }

    std::array<double, 2> interactSize() const {
        return props_.getAll<PropId::OfxParamPropInteractSize>();
    }

    double interactSizeAspect() const {
        return props_.get<PropId::OfxParamPropInteractSizeAspect>(0);
    }

    std::array<double, 2> interactMinimumSize() const {
        return props_.getAll<PropId::OfxParamPropInteractMinimumSize>();
    }

    std::array<int, 2> interactPreferedSize() const {
        return props_.getAll<PropId::OfxParamPropInteractPreferedSize>();
    }

    bool hasHostOverlayHandle() const {
        return props_.get<PropId::OfxParamPropHasHostOverlayHandle>(0);
    }

    bool useHostOverlayHandle() const {
        return props_.get<PropId::OfxParamPropUseHostOverlayHandle>(0);
    }

    // Multi-type property (supports: int, double, string, pointer)
    template<typename T>
    T default(int index = 0) const {
        return props_.get<PropId::OfxParamPropDefault, T>(index);
    }

    template<typename T>
    std::vector<T> defaultAll() const {
        return props_.getAll<PropId::OfxParamPropDefault, T>();
    }

    bool animates() const {
        return props_.get<PropId::OfxParamPropAnimates>(0);
    }

    void setIsAnimating(bool value) {
        props_.set<PropId::OfxParamPropIsAnimating>(value, 0);
    }

    void setIsAutoKeying(bool value) {
        props_.set<PropId::OfxParamPropIsAutoKeying>(value, 0);
    }

    bool persistant() const {
        return props_.get<PropId::OfxParamPropPersistant>(0);
    }

    bool evaluateOnChange() const {
        return props_.get<PropId::OfxParamPropEvaluateOnChange>(0);
    }

    bool pluginMayWrite() const {
        return props_.get<PropId::OfxParamPropPluginMayWrite>(0);
    }

    const char* cacheInvalidation() const {
        return props_.get<PropId::OfxParamPropCacheInvalidation>(0);
    }

    bool canUndo() const {
        return props_.get<PropId::OfxParamPropCanUndo>(0);
    }

};

// Property set accessor for: ParamsString
class ParamsString : public PropertySetAccessor {
public:
    using PropertySetAccessor::PropertySetAccessor;

    const char* stringMode() const {
        return props_.get<PropId::OfxParamPropStringMode>(0);
    }

    bool stringFilePathExists() const {
        return props_.get<PropId::OfxParamPropStringFilePathExists>(0);
    }

    const char* type() const {
        return props_.get<PropId::OfxPropType>(0);
    }

    const char* name() const {
        return props_.get<PropId::OfxPropName>(0);
    }

    const char* label() const {
        return props_.get<PropId::OfxPropLabel>(0);
    }

    const char* shortLabel() const {
        return props_.get<PropId::OfxPropShortLabel>(0);
    }

    const char* longLabel() const {
        return props_.get<PropId::OfxPropLongLabel>(0);
    }

    bool secret() const {
        return props_.get<PropId::OfxParamPropSecret>(0);
    }

    const char* hint() const {
        return props_.get<PropId::OfxParamPropHint>(0);
    }

    const char* scriptName() const {
        return props_.get<PropId::OfxParamPropScriptName>(0);
    }

    const char* parent() const {
        return props_.get<PropId::OfxParamPropParent>(0);
    }

    bool enabled() const {
        return props_.get<PropId::OfxParamPropEnabled>(0);
    }

    void* dataPtr() const {
        return props_.get<PropId::OfxParamPropDataPtr>(0);
    }

    std::array<const char*, 2> icon() const {
        return props_.getAll<PropId::OfxPropIcon>();
    }

    void* interactV1() const {
        return props_.get<PropId::OfxParamPropInteractV1>(0);
    }

    std::array<double, 2> interactSize() const {
        return props_.getAll<PropId::OfxParamPropInteractSize>();
    }

    double interactSizeAspect() const {
        return props_.get<PropId::OfxParamPropInteractSizeAspect>(0);
    }

    std::array<double, 2> interactMinimumSize() const {
        return props_.getAll<PropId::OfxParamPropInteractMinimumSize>();
    }

    std::array<int, 2> interactPreferedSize() const {
        return props_.getAll<PropId::OfxParamPropInteractPreferedSize>();
    }

    bool hasHostOverlayHandle() const {
        return props_.get<PropId::OfxParamPropHasHostOverlayHandle>(0);
    }

    bool useHostOverlayHandle() const {
        return props_.get<PropId::OfxParamPropUseHostOverlayHandle>(0);
    }

    // Multi-type property (supports: int, double, string, pointer)
    template<typename T>
    T default(int index = 0) const {
        return props_.get<PropId::OfxParamPropDefault, T>(index);
    }

    template<typename T>
    std::vector<T> defaultAll() const {
        return props_.getAll<PropId::OfxParamPropDefault, T>();
    }

    bool animates() const {
        return props_.get<PropId::OfxParamPropAnimates>(0);
    }

    void setIsAnimating(bool value) {
        props_.set<PropId::OfxParamPropIsAnimating>(value, 0);
    }

    void setIsAutoKeying(bool value) {
        props_.set<PropId::OfxParamPropIsAutoKeying>(value, 0);
    }

    bool persistant() const {
        return props_.get<PropId::OfxParamPropPersistant>(0);
    }

    bool evaluateOnChange() const {
        return props_.get<PropId::OfxParamPropEvaluateOnChange>(0);
    }

    bool pluginMayWrite() const {
        return props_.get<PropId::OfxParamPropPluginMayWrite>(0);
    }

    const char* cacheInvalidation() const {
        return props_.get<PropId::OfxParamPropCacheInvalidation>(0);
    }

    bool canUndo() const {
        return props_.get<PropId::OfxParamPropCanUndo>(0);
    }

    // Multi-type property (supports: int, double)
    template<typename T>
    T min(int index = 0) const {
        return props_.get<PropId::OfxParamPropMin, T>(index);
    }

    template<typename T>
    std::vector<T> minAll() const {
        return props_.getAll<PropId::OfxParamPropMin, T>();
    }

    // Multi-type property (supports: int, double)
    template<typename T>
    T max(int index = 0) const {
        return props_.get<PropId::OfxParamPropMax, T>(index);
    }

    template<typename T>
    std::vector<T> maxAll() const {
        return props_.getAll<PropId::OfxParamPropMax, T>();
    }

    // Multi-type property (supports: int, double)
    template<typename T>
    T displayMin(int index = 0) const {
        return props_.get<PropId::OfxParamPropDisplayMin, T>(index);
    }

    template<typename T>
    std::vector<T> displayMinAll() const {
        return props_.getAll<PropId::OfxParamPropDisplayMin, T>();
    }

    // Multi-type property (supports: int, double)
    template<typename T>
    T displayMax(int index = 0) const {
        return props_.get<PropId::OfxParamPropDisplayMax, T>(index);
    }

    template<typename T>
    std::vector<T> displayMaxAll() const {
        return props_.getAll<PropId::OfxParamPropDisplayMax, T>();
    }

};

} // namespace openfx
