// Copyright OpenFX and contributors to the OpenFX project.
// SPDX-License-Identifier: BSD-3-Clause
// NOTE: This file is auto-generated by gen-props.py. DO NOT EDIT.

#pragma once

#include <array>
#include <string_view>

#include <ofxImageEffect.h>
#include <ofxGPURender.h>
#include <ofxColour.h>
#include <ofxDrawSuite.h>
#include <ofxParametricParam.h>
#include <ofxKeySyms.h>
#include <ofxOld.h>

#include "ofxSpan.h"

namespace openfx {
enum class PropType {
   Int,
   Double,
   Enum,
   Bool,
   String,
   Pointer
};

// Each prop has a PropId::<propname> enum, a runtime-accessible PropDef struct, and a compile-time PropTraits<id>.
// These can be used by Support/include/PropsAccess.h for type-safe property access.

//Property ID enum for compile-time lookup and type safety
enum class PropId {
  OfxImageClipPropColourspace, // 0
  OfxImageClipPropConnected, // 1
  OfxImageClipPropContinuousSamples, // 2
  OfxImageClipPropFieldExtraction, // 3
  OfxImageClipPropFieldOrder, // 4
  OfxImageClipPropIsMask, // 5
  OfxImageClipPropOptional, // 6
  OfxImageClipPropPreferredColourspaces, // 7
  OfxImageClipPropUnmappedComponents, // 8
  OfxImageClipPropUnmappedPixelDepth, // 9
  OfxImageEffectFrameVarying, // 10
  OfxImageEffectHostPropIsBackground, // 11
  OfxImageEffectHostPropNativeOrigin, // 12
  OfxImageEffectInstancePropEffectDuration, // 13
  OfxImageEffectInstancePropSequentialRender, // 14
  OfxImageEffectPluginPropFieldRenderTwiceAlways, // 15
  OfxImageEffectPluginPropGrouping, // 16
  OfxImageEffectPluginPropHostFrameThreading, // 17
  OfxImageEffectPluginPropOverlayInteractV1, // 18
  OfxImageEffectPluginPropOverlayInteractV2, // 19
  OfxImageEffectPluginPropSingleInstance, // 20
  OfxImageEffectPluginRenderThreadSafety, // 21
  OfxImageEffectPropClipPreferencesSlaveParam, // 22
  OfxImageEffectPropColourManagementAvailableConfigs, // 23
  OfxImageEffectPropColourManagementConfig, // 24
  OfxImageEffectPropColourManagementStyle, // 25
  OfxImageEffectPropComponents, // 26
  OfxImageEffectPropContext, // 27
  OfxImageEffectPropCudaEnabled, // 28
  OfxImageEffectPropCudaRenderSupported, // 29
  OfxImageEffectPropCudaStream, // 30
  OfxImageEffectPropCudaStreamSupported, // 31
  OfxImageEffectPropDisplayColourspace, // 32
  OfxImageEffectPropFieldToRender, // 33
  OfxImageEffectPropFrameRange, // 34
  OfxImageEffectPropFrameRate, // 35
  OfxImageEffectPropFrameStep, // 36
  OfxImageEffectPropInAnalysis, // 37
  OfxImageEffectPropInteractiveRenderStatus, // 38
  OfxImageEffectPropMetalCommandQueue, // 39
  OfxImageEffectPropMetalEnabled, // 40
  OfxImageEffectPropMetalRenderSupported, // 41
  OfxImageEffectPropMultipleClipDepths, // 42
  OfxImageEffectPropNoSpatialAwareness, // 43
  OfxImageEffectPropOCIOConfig, // 44
  OfxImageEffectPropOCIODisplay, // 45
  OfxImageEffectPropOCIOView, // 46
  OfxImageEffectPropOpenCLCommandQueue, // 47
  OfxImageEffectPropOpenCLEnabled, // 48
  OfxImageEffectPropOpenCLImage, // 49
  OfxImageEffectPropOpenCLRenderSupported, // 50
  OfxImageEffectPropOpenCLSupported, // 51
  OfxImageEffectPropOpenGLEnabled, // 52
  OfxImageEffectPropOpenGLRenderSupported, // 53
  OfxImageEffectPropOpenGLTextureIndex, // 54
  OfxImageEffectPropOpenGLTextureTarget, // 55
  OfxImageEffectPropPixelAspectRatio, // 56
  OfxImageEffectPropPixelDepth, // 57
  OfxImageEffectPropPluginHandle, // 58
  OfxImageEffectPropPreMultiplication, // 59
  OfxImageEffectPropProjectExtent, // 60
  OfxImageEffectPropProjectOffset, // 61
  OfxImageEffectPropProjectSize, // 62
  OfxImageEffectPropRegionOfDefinition, // 63
  OfxImageEffectPropRegionOfInterest, // 64
  OfxImageEffectPropRenderQualityDraft, // 65
  OfxImageEffectPropRenderScale, // 66
  OfxImageEffectPropRenderWindow, // 67
  OfxImageEffectPropSequentialRenderStatus, // 68
  OfxImageEffectPropSetableFielding, // 69
  OfxImageEffectPropSetableFrameRate, // 70
  OfxImageEffectPropSupportedComponents, // 71
  OfxImageEffectPropSupportedContexts, // 72
  OfxImageEffectPropSupportedPixelDepths, // 73
  OfxImageEffectPropSupportsMultiResolution, // 74
  OfxImageEffectPropSupportsMultipleClipPARs, // 75
  OfxImageEffectPropSupportsOverlays, // 76
  OfxImageEffectPropSupportsTiles, // 77
  OfxImageEffectPropTemporalClipAccess, // 78
  OfxImageEffectPropUnmappedFrameRange, // 79
  OfxImageEffectPropUnmappedFrameRate, // 80
  OfxImagePropBounds, // 81
  OfxImagePropData, // 82
  OfxImagePropField, // 83
  OfxImagePropPixelAspectRatio, // 84
  OfxImagePropRegionOfDefinition, // 85
  OfxImagePropRowBytes, // 86
  OfxImagePropUniqueIdentifier, // 87
  OfxInteractPropBackgroundColour, // 88
  OfxInteractPropBitDepth, // 89
  OfxInteractPropDrawContext, // 90
  OfxInteractPropHasAlpha, // 91
  OfxInteractPropPenPosition, // 92
  OfxInteractPropPenPressure, // 93
  OfxInteractPropPenViewportPosition, // 94
  OfxInteractPropPixelScale, // 95
  OfxInteractPropSlaveToParam, // 96
  OfxInteractPropSuggestedColour, // 97
  OfxInteractPropViewport, // 98
  OfxOpenGLPropPixelDepth, // 99
  OfxParamHostPropMaxPages, // 100
  OfxParamHostPropMaxParameters, // 101
  OfxParamHostPropPageRowColumnCount, // 102
  OfxParamHostPropSupportsBooleanAnimation, // 103
  OfxParamHostPropSupportsChoiceAnimation, // 104
  OfxParamHostPropSupportsCustomAnimation, // 105
  OfxParamHostPropSupportsCustomInteract, // 106
  OfxParamHostPropSupportsParametricAnimation, // 107
  OfxParamHostPropSupportsStrChoice, // 108
  OfxParamHostPropSupportsStrChoiceAnimation, // 109
  OfxParamHostPropSupportsStringAnimation, // 110
  OfxParamPropAnimates, // 111
  OfxParamPropCacheInvalidation, // 112
  OfxParamPropCanUndo, // 113
  OfxParamPropChoiceEnum, // 114
  OfxParamPropChoiceOption, // 115
  OfxParamPropChoiceOrder, // 116
  OfxParamPropCustomCallbackV1, // 117
  OfxParamPropCustomValue, // 118
  OfxParamPropDataPtr, // 119
  OfxParamPropDefault, // 120
  OfxParamPropDefaultCoordinateSystem, // 121
  OfxParamPropDigits, // 122
  OfxParamPropDimensionLabel, // 123
  OfxParamPropDisplayMax, // 124
  OfxParamPropDisplayMin, // 125
  OfxParamPropDoubleType, // 126
  OfxParamPropEnabled, // 127
  OfxParamPropEvaluateOnChange, // 128
  OfxParamPropGroupOpen, // 129
  OfxParamPropHasHostOverlayHandle, // 130
  OfxParamPropHint, // 131
  OfxParamPropIncrement, // 132
  OfxParamPropInteractMinimumSize, // 133
  OfxParamPropInteractPreferedSize, // 134
  OfxParamPropInteractSize, // 135
  OfxParamPropInteractSizeAspect, // 136
  OfxParamPropInteractV1, // 137
  OfxParamPropInterpolationAmount, // 138
  OfxParamPropInterpolationTime, // 139
  OfxParamPropIsAnimating, // 140
  OfxParamPropIsAutoKeying, // 141
  OfxParamPropMax, // 142
  OfxParamPropMin, // 143
  OfxParamPropPageChild, // 144
  OfxParamPropParametricDimension, // 145
  OfxParamPropParametricInteractBackground, // 146
  OfxParamPropParametricRange, // 147
  OfxParamPropParametricUIColour, // 148
  OfxParamPropParent, // 149
  OfxParamPropPersistant, // 150
  OfxParamPropPluginMayWrite, // 151
  OfxParamPropScriptName, // 152
  OfxParamPropSecret, // 153
  OfxParamPropShowTimeMarker, // 154
  OfxParamPropStringFilePathExists, // 155
  OfxParamPropStringMode, // 156
  OfxParamPropType, // 157
  OfxPluginPropFilePath, // 158
  OfxPluginPropParamPageOrder, // 159
  OfxPropAPIVersion, // 160
  OfxPropChangeReason, // 161
  OfxPropEffectInstance, // 162
  OfxPropHostOSHandle, // 163
  OfxPropIcon, // 164
  OfxPropInstanceData, // 165
  OfxPropIsInteractive, // 166
  OfxPropLabel, // 167
  OfxPropLongLabel, // 168
  OfxPropName, // 169
  OfxPropParamSetNeedsSyncing, // 170
  OfxPropPluginDescription, // 171
  OfxPropShortLabel, // 172
  OfxPropTime, // 173
  OfxPropType, // 174
  OfxPropVersion, // 175
  OfxPropVersionLabel, // 176
  OfxParamPropUseHostOverlayHandle, // 177 (orig name: OfxParamPropUseHostOverlayHandle)
  OfxPropKeyString, // 178 (orig name: OfxPropKeyString)
  OfxPropKeySym, // 179 (orig name: OfxPropKeySym)
  NProps // 180
}; // PropId

// Separate arrays for enum-values for enum props, to keep everything constexpr
namespace prop_enum_values {
constexpr std::array OfxImageClipPropFieldExtraction =
  {"OfxImageFieldNone","OfxImageFieldLower","OfxImageFieldUpper","OfxImageFieldBoth","OfxImageFieldSingle","OfxImageFieldDoubled"};
constexpr std::array OfxImageClipPropFieldOrder =
  {"OfxImageFieldNone","OfxImageFieldLower","OfxImageFieldUpper"};
constexpr std::array OfxImageClipPropUnmappedComponents =
  {"OfxImageComponentNone","OfxImageComponentRGBA","OfxImageComponentRGB","OfxImageComponentAlpha"};
constexpr std::array OfxImageClipPropUnmappedPixelDepth =
  {"OfxBitDepthNone","OfxBitDepthByte","OfxBitDepthShort","OfxBitDepthHalf","OfxBitDepthFloat"};
constexpr std::array OfxImageEffectHostPropNativeOrigin =
  {"OfxImageEffectHostPropNativeOriginBottomLeft","OfxImageEffectHostPropNativeOriginTopLeft","OfxImageEffectHostPropNativeOriginCenter"};
constexpr std::array OfxImageEffectPluginRenderThreadSafety =
  {"OfxImageEffectRenderUnsafe","OfxImageEffectRenderInstanceSafe","OfxImageEffectRenderFullySafe"};
constexpr std::array OfxImageEffectPropColourManagementStyle =
  {"OfxImageEffectPropColourManagementNone","OfxImageEffectPropColourManagementBasic","OfxImageEffectPropColourManagementCore","OfxImageEffectPropColourManagementFull","OfxImageEffectPropColourManagementOCIO"};
constexpr std::array OfxImageEffectPropComponents =
  {"OfxImageComponentNone","OfxImageComponentRGBA","OfxImageComponentRGB","OfxImageComponentAlpha"};
constexpr std::array OfxImageEffectPropContext =
  {"OfxImageEffectContextGenerator","OfxImageEffectContextFilter","OfxImageEffectContextTransition","OfxImageEffectContextPaint","OfxImageEffectContextGeneral","OfxImageEffectContextRetimer"};
constexpr std::array OfxImageEffectPropCudaRenderSupported =
  {"false","true","needed"};
constexpr std::array OfxImageEffectPropCudaStreamSupported =
  {"false","true","needed"};
constexpr std::array OfxImageEffectPropFieldToRender =
  {"OfxImageFieldNone","OfxImageFieldBoth","OfxImageFieldLower","OfxImageFieldUpper"};
constexpr std::array OfxImageEffectPropMetalRenderSupported =
  {"false","true","needed"};
constexpr std::array OfxImageEffectPropNoSpatialAwareness =
  {"false","true"};
constexpr std::array OfxImageEffectPropOpenCLRenderSupported =
  {"false","true","needed"};
constexpr std::array OfxImageEffectPropOpenCLSupported =
  {"false","true"};
constexpr std::array OfxImageEffectPropOpenGLRenderSupported =
  {"false","true","needed"};
constexpr std::array OfxImageEffectPropPixelDepth =
  {"OfxBitDepthNone","OfxBitDepthByte","OfxBitDepthShort","OfxBitDepthHalf","OfxBitDepthFloat"};
constexpr std::array OfxImageEffectPropPreMultiplication =
  {"OfxImageOpaque","OfxImagePreMultiplied","OfxImageUnPreMultiplied"};
constexpr std::array OfxImageEffectPropSupportedComponents =
  {"OfxImageComponentNone","OfxImageComponentRGBA","OfxImageComponentRGB","OfxImageComponentAlpha"};
constexpr std::array OfxImageEffectPropSupportedContexts =
  {"OfxImageEffectContextGenerator","OfxImageEffectContextFilter","OfxImageEffectContextTransition","OfxImageEffectContextPaint","OfxImageEffectContextGeneral","OfxImageEffectContextRetimer"};
constexpr std::array OfxImageEffectPropSupportedPixelDepths =
  {"OfxBitDepthNone","OfxBitDepthByte","OfxBitDepthShort","OfxBitDepthHalf","OfxBitDepthFloat"};
constexpr std::array OfxImagePropField =
  {"OfxImageFieldNone","OfxImageFieldBoth","OfxImageFieldLower","OfxImageFieldUpper"};
constexpr std::array OfxOpenGLPropPixelDepth =
  {"OfxBitDepthNone","OfxBitDepthByte","OfxBitDepthShort","OfxBitDepthHalf","OfxBitDepthFloat"};
constexpr std::array OfxParamPropCacheInvalidation =
  {"OfxParamInvalidateValueChange","OfxParamInvalidateValueChangeToEnd","OfxParamInvalidateAll"};
constexpr std::array OfxParamPropDefaultCoordinateSystem =
  {"OfxParamCoordinatesCanonical","OfxParamCoordinatesNormalised"};
constexpr std::array OfxParamPropDoubleType =
  {"OfxParamDoubleTypePlain","OfxParamDoubleTypeAngle","OfxParamDoubleTypeScale","OfxParamDoubleTypeTime","OfxParamDoubleTypeAbsoluteTime","OfxParamDoubleTypeX","OfxParamDoubleTypeXAbsolute","OfxParamDoubleTypeY","OfxParamDoubleTypeYAbsolute","OfxParamDoubleTypeXY","OfxParamDoubleTypeXYAbsolute"};
constexpr std::array OfxParamPropStringMode =
  {"OfxParamStringIsSingleLine","OfxParamStringIsMultiLine","OfxParamStringIsFilePath","OfxParamStringIsDirectoryPath","OfxParamStringIsLabel","OfxParamStringIsRichTextFormat"};
constexpr std::array OfxPropChangeReason =
  {"OfxChangeUserEdited","OfxChangePluginEdited","OfxChangeTime"};
} // namespace prop_enum_values


// Property type arrays for spans (generated before PropDef)
namespace prop_type_arrays {
static constexpr PropType OfxImageClipPropColourspace_types[] = {PropType::String};
static constexpr PropType OfxImageClipPropConnected_types[] = {PropType::Bool};
static constexpr PropType OfxImageClipPropContinuousSamples_types[] = {PropType::Bool};
static constexpr PropType OfxImageClipPropFieldExtraction_types[] = {PropType::Enum};
static constexpr PropType OfxImageClipPropFieldOrder_types[] = {PropType::Enum};
static constexpr PropType OfxImageClipPropIsMask_types[] = {PropType::Bool};
static constexpr PropType OfxImageClipPropOptional_types[] = {PropType::Bool};
static constexpr PropType OfxImageClipPropPreferredColourspaces_types[] = {PropType::String};
static constexpr PropType OfxImageClipPropUnmappedComponents_types[] = {PropType::Enum};
static constexpr PropType OfxImageClipPropUnmappedPixelDepth_types[] = {PropType::Enum};
static constexpr PropType OfxImageEffectFrameVarying_types[] = {PropType::Bool};
static constexpr PropType OfxImageEffectHostPropIsBackground_types[] = {PropType::Bool};
static constexpr PropType OfxImageEffectHostPropNativeOrigin_types[] = {PropType::Enum};
static constexpr PropType OfxImageEffectInstancePropEffectDuration_types[] = {PropType::Double};
static constexpr PropType OfxImageEffectInstancePropSequentialRender_types[] = {PropType::Bool};
static constexpr PropType OfxImageEffectPluginPropFieldRenderTwiceAlways_types[] = {PropType::Bool};
static constexpr PropType OfxImageEffectPluginPropGrouping_types[] = {PropType::String};
static constexpr PropType OfxImageEffectPluginPropHostFrameThreading_types[] = {PropType::Bool};
static constexpr PropType OfxImageEffectPluginPropOverlayInteractV1_types[] = {PropType::Pointer};
static constexpr PropType OfxImageEffectPluginPropOverlayInteractV2_types[] = {PropType::Pointer};
static constexpr PropType OfxImageEffectPluginPropSingleInstance_types[] = {PropType::Bool};
static constexpr PropType OfxImageEffectPluginRenderThreadSafety_types[] = {PropType::Enum};
static constexpr PropType OfxImageEffectPropClipPreferencesSlaveParam_types[] = {PropType::String};
static constexpr PropType OfxImageEffectPropColourManagementAvailableConfigs_types[] = {PropType::String};
static constexpr PropType OfxImageEffectPropColourManagementConfig_types[] = {PropType::String};
static constexpr PropType OfxImageEffectPropColourManagementStyle_types[] = {PropType::Enum};
static constexpr PropType OfxImageEffectPropComponents_types[] = {PropType::Enum};
static constexpr PropType OfxImageEffectPropContext_types[] = {PropType::Enum};
static constexpr PropType OfxImageEffectPropCudaEnabled_types[] = {PropType::Bool};
static constexpr PropType OfxImageEffectPropCudaRenderSupported_types[] = {PropType::Enum};
static constexpr PropType OfxImageEffectPropCudaStream_types[] = {PropType::Pointer};
static constexpr PropType OfxImageEffectPropCudaStreamSupported_types[] = {PropType::Enum};
static constexpr PropType OfxImageEffectPropDisplayColourspace_types[] = {PropType::String};
static constexpr PropType OfxImageEffectPropFieldToRender_types[] = {PropType::Enum};
static constexpr PropType OfxImageEffectPropFrameRange_types[] = {PropType::Double};
static constexpr PropType OfxImageEffectPropFrameRate_types[] = {PropType::Double};
static constexpr PropType OfxImageEffectPropFrameStep_types[] = {PropType::Double};
static constexpr PropType OfxImageEffectPropInAnalysis_types[] = {PropType::Bool};
static constexpr PropType OfxImageEffectPropInteractiveRenderStatus_types[] = {PropType::Bool};
static constexpr PropType OfxImageEffectPropMetalCommandQueue_types[] = {PropType::Pointer};
static constexpr PropType OfxImageEffectPropMetalEnabled_types[] = {PropType::Bool};
static constexpr PropType OfxImageEffectPropMetalRenderSupported_types[] = {PropType::Enum};
static constexpr PropType OfxImageEffectPropMultipleClipDepths_types[] = {PropType::Bool};
static constexpr PropType OfxImageEffectPropNoSpatialAwareness_types[] = {PropType::Enum};
static constexpr PropType OfxImageEffectPropOCIOConfig_types[] = {PropType::String};
static constexpr PropType OfxImageEffectPropOCIODisplay_types[] = {PropType::String};
static constexpr PropType OfxImageEffectPropOCIOView_types[] = {PropType::String};
static constexpr PropType OfxImageEffectPropOpenCLCommandQueue_types[] = {PropType::Pointer};
static constexpr PropType OfxImageEffectPropOpenCLEnabled_types[] = {PropType::Bool};
static constexpr PropType OfxImageEffectPropOpenCLImage_types[] = {PropType::Pointer};
static constexpr PropType OfxImageEffectPropOpenCLRenderSupported_types[] = {PropType::Enum};
static constexpr PropType OfxImageEffectPropOpenCLSupported_types[] = {PropType::Enum};
static constexpr PropType OfxImageEffectPropOpenGLEnabled_types[] = {PropType::Bool};
static constexpr PropType OfxImageEffectPropOpenGLRenderSupported_types[] = {PropType::Enum};
static constexpr PropType OfxImageEffectPropOpenGLTextureIndex_types[] = {PropType::Int};
static constexpr PropType OfxImageEffectPropOpenGLTextureTarget_types[] = {PropType::Int};
static constexpr PropType OfxImageEffectPropPixelAspectRatio_types[] = {PropType::Double};
static constexpr PropType OfxImageEffectPropPixelDepth_types[] = {PropType::Enum};
static constexpr PropType OfxImageEffectPropPluginHandle_types[] = {PropType::Pointer};
static constexpr PropType OfxImageEffectPropPreMultiplication_types[] = {PropType::Enum};
static constexpr PropType OfxImageEffectPropProjectExtent_types[] = {PropType::Double};
static constexpr PropType OfxImageEffectPropProjectOffset_types[] = {PropType::Double};
static constexpr PropType OfxImageEffectPropProjectSize_types[] = {PropType::Double};
static constexpr PropType OfxImageEffectPropRegionOfDefinition_types[] = {PropType::Double};
static constexpr PropType OfxImageEffectPropRegionOfInterest_types[] = {PropType::Double};
static constexpr PropType OfxImageEffectPropRenderQualityDraft_types[] = {PropType::Bool};
static constexpr PropType OfxImageEffectPropRenderScale_types[] = {PropType::Double};
static constexpr PropType OfxImageEffectPropRenderWindow_types[] = {PropType::Int};
static constexpr PropType OfxImageEffectPropSequentialRenderStatus_types[] = {PropType::Bool};
static constexpr PropType OfxImageEffectPropSetableFielding_types[] = {PropType::Bool};
static constexpr PropType OfxImageEffectPropSetableFrameRate_types[] = {PropType::Bool};
static constexpr PropType OfxImageEffectPropSupportedComponents_types[] = {PropType::Enum};
static constexpr PropType OfxImageEffectPropSupportedContexts_types[] = {PropType::Enum};
static constexpr PropType OfxImageEffectPropSupportedPixelDepths_types[] = {PropType::Enum};
static constexpr PropType OfxImageEffectPropSupportsMultiResolution_types[] = {PropType::Bool};
static constexpr PropType OfxImageEffectPropSupportsMultipleClipPARs_types[] = {PropType::Bool};
static constexpr PropType OfxImageEffectPropSupportsOverlays_types[] = {PropType::Bool};
static constexpr PropType OfxImageEffectPropSupportsTiles_types[] = {PropType::Bool};
static constexpr PropType OfxImageEffectPropTemporalClipAccess_types[] = {PropType::Bool};
static constexpr PropType OfxImageEffectPropUnmappedFrameRange_types[] = {PropType::Double};
static constexpr PropType OfxImageEffectPropUnmappedFrameRate_types[] = {PropType::Double};
static constexpr PropType OfxImagePropBounds_types[] = {PropType::Int};
static constexpr PropType OfxImagePropData_types[] = {PropType::Pointer};
static constexpr PropType OfxImagePropField_types[] = {PropType::Enum};
static constexpr PropType OfxImagePropPixelAspectRatio_types[] = {PropType::Double};
static constexpr PropType OfxImagePropRegionOfDefinition_types[] = {PropType::Int};
static constexpr PropType OfxImagePropRowBytes_types[] = {PropType::Int};
static constexpr PropType OfxImagePropUniqueIdentifier_types[] = {PropType::String};
static constexpr PropType OfxInteractPropBackgroundColour_types[] = {PropType::Double};
static constexpr PropType OfxInteractPropBitDepth_types[] = {PropType::Int};
static constexpr PropType OfxInteractPropDrawContext_types[] = {PropType::Pointer};
static constexpr PropType OfxInteractPropHasAlpha_types[] = {PropType::Bool};
static constexpr PropType OfxInteractPropPenPosition_types[] = {PropType::Double};
static constexpr PropType OfxInteractPropPenPressure_types[] = {PropType::Double};
static constexpr PropType OfxInteractPropPenViewportPosition_types[] = {PropType::Int};
static constexpr PropType OfxInteractPropPixelScale_types[] = {PropType::Double};
static constexpr PropType OfxInteractPropSlaveToParam_types[] = {PropType::String};
static constexpr PropType OfxInteractPropSuggestedColour_types[] = {PropType::Double};
static constexpr PropType OfxInteractPropViewport_types[] = {PropType::Int};
static constexpr PropType OfxOpenGLPropPixelDepth_types[] = {PropType::Enum};
static constexpr PropType OfxParamHostPropMaxPages_types[] = {PropType::Int};
static constexpr PropType OfxParamHostPropMaxParameters_types[] = {PropType::Int};
static constexpr PropType OfxParamHostPropPageRowColumnCount_types[] = {PropType::Int};
static constexpr PropType OfxParamHostPropSupportsBooleanAnimation_types[] = {PropType::Bool};
static constexpr PropType OfxParamHostPropSupportsChoiceAnimation_types[] = {PropType::Bool};
static constexpr PropType OfxParamHostPropSupportsCustomAnimation_types[] = {PropType::Bool};
static constexpr PropType OfxParamHostPropSupportsCustomInteract_types[] = {PropType::Bool};
static constexpr PropType OfxParamHostPropSupportsParametricAnimation_types[] = {PropType::Bool};
static constexpr PropType OfxParamHostPropSupportsStrChoice_types[] = {PropType::Bool};
static constexpr PropType OfxParamHostPropSupportsStrChoiceAnimation_types[] = {PropType::Bool};
static constexpr PropType OfxParamHostPropSupportsStringAnimation_types[] = {PropType::Bool};
static constexpr PropType OfxParamPropAnimates_types[] = {PropType::Bool};
static constexpr PropType OfxParamPropCacheInvalidation_types[] = {PropType::Enum};
static constexpr PropType OfxParamPropCanUndo_types[] = {PropType::Bool};
static constexpr PropType OfxParamPropChoiceEnum_types[] = {PropType::Bool};
static constexpr PropType OfxParamPropChoiceOption_types[] = {PropType::String};
static constexpr PropType OfxParamPropChoiceOrder_types[] = {PropType::Int};
static constexpr PropType OfxParamPropCustomCallbackV1_types[] = {PropType::Pointer};
static constexpr PropType OfxParamPropCustomValue_types[] = {PropType::String};
static constexpr PropType OfxParamPropDataPtr_types[] = {PropType::Pointer};
static constexpr PropType OfxParamPropDefault_types[] = {PropType::Int,PropType::Double,PropType::String,PropType::Pointer};
static constexpr PropType OfxParamPropDefaultCoordinateSystem_types[] = {PropType::Enum};
static constexpr PropType OfxParamPropDigits_types[] = {PropType::Int};
static constexpr PropType OfxParamPropDimensionLabel_types[] = {PropType::String};
static constexpr PropType OfxParamPropDisplayMax_types[] = {PropType::Int,PropType::Double};
static constexpr PropType OfxParamPropDisplayMin_types[] = {PropType::Int,PropType::Double};
static constexpr PropType OfxParamPropDoubleType_types[] = {PropType::Enum};
static constexpr PropType OfxParamPropEnabled_types[] = {PropType::Bool};
static constexpr PropType OfxParamPropEvaluateOnChange_types[] = {PropType::Bool};
static constexpr PropType OfxParamPropGroupOpen_types[] = {PropType::Bool};
static constexpr PropType OfxParamPropHasHostOverlayHandle_types[] = {PropType::Bool};
static constexpr PropType OfxParamPropHint_types[] = {PropType::String};
static constexpr PropType OfxParamPropIncrement_types[] = {PropType::Double};
static constexpr PropType OfxParamPropInteractMinimumSize_types[] = {PropType::Double};
static constexpr PropType OfxParamPropInteractPreferedSize_types[] = {PropType::Int};
static constexpr PropType OfxParamPropInteractSize_types[] = {PropType::Double};
static constexpr PropType OfxParamPropInteractSizeAspect_types[] = {PropType::Double};
static constexpr PropType OfxParamPropInteractV1_types[] = {PropType::Pointer};
static constexpr PropType OfxParamPropInterpolationAmount_types[] = {PropType::Double};
static constexpr PropType OfxParamPropInterpolationTime_types[] = {PropType::Double};
static constexpr PropType OfxParamPropIsAnimating_types[] = {PropType::Bool};
static constexpr PropType OfxParamPropIsAutoKeying_types[] = {PropType::Bool};
static constexpr PropType OfxParamPropMax_types[] = {PropType::Int,PropType::Double};
static constexpr PropType OfxParamPropMin_types[] = {PropType::Int,PropType::Double};
static constexpr PropType OfxParamPropPageChild_types[] = {PropType::String};
static constexpr PropType OfxParamPropParametricDimension_types[] = {PropType::Int};
static constexpr PropType OfxParamPropParametricInteractBackground_types[] = {PropType::Pointer};
static constexpr PropType OfxParamPropParametricRange_types[] = {PropType::Double};
static constexpr PropType OfxParamPropParametricUIColour_types[] = {PropType::Double};
static constexpr PropType OfxParamPropParent_types[] = {PropType::String};
static constexpr PropType OfxParamPropPersistant_types[] = {PropType::Bool};
static constexpr PropType OfxParamPropPluginMayWrite_types[] = {PropType::Bool};
static constexpr PropType OfxParamPropScriptName_types[] = {PropType::String};
static constexpr PropType OfxParamPropSecret_types[] = {PropType::Bool};
static constexpr PropType OfxParamPropShowTimeMarker_types[] = {PropType::Bool};
static constexpr PropType OfxParamPropStringFilePathExists_types[] = {PropType::Bool};
static constexpr PropType OfxParamPropStringMode_types[] = {PropType::Enum};
static constexpr PropType OfxParamPropType_types[] = {PropType::String};
static constexpr PropType OfxPluginPropFilePath_types[] = {PropType::String};
static constexpr PropType OfxPluginPropParamPageOrder_types[] = {PropType::String};
static constexpr PropType OfxPropAPIVersion_types[] = {PropType::Int};
static constexpr PropType OfxPropChangeReason_types[] = {PropType::Enum};
static constexpr PropType OfxPropEffectInstance_types[] = {PropType::Pointer};
static constexpr PropType OfxPropHostOSHandle_types[] = {PropType::Pointer};
static constexpr PropType OfxPropIcon_types[] = {PropType::String};
static constexpr PropType OfxPropInstanceData_types[] = {PropType::Pointer};
static constexpr PropType OfxPropIsInteractive_types[] = {PropType::Bool};
static constexpr PropType OfxPropLabel_types[] = {PropType::String};
static constexpr PropType OfxPropLongLabel_types[] = {PropType::String};
static constexpr PropType OfxPropName_types[] = {PropType::String};
static constexpr PropType OfxPropParamSetNeedsSyncing_types[] = {PropType::Bool};
static constexpr PropType OfxPropPluginDescription_types[] = {PropType::String};
static constexpr PropType OfxPropShortLabel_types[] = {PropType::String};
static constexpr PropType OfxPropTime_types[] = {PropType::Double};
static constexpr PropType OfxPropType_types[] = {PropType::String};
static constexpr PropType OfxPropVersion_types[] = {PropType::Int};
static constexpr PropType OfxPropVersionLabel_types[] = {PropType::String};
static constexpr PropType kOfxParamPropUseHostOverlayHandle_types[] = {PropType::Bool};
static constexpr PropType kOfxPropKeyString_types[] = {PropType::String};
static constexpr PropType kOfxPropKeySym_types[] = {PropType::Int};
} // namespace prop_type_arrays


struct PropDef {
   const char* name;                    // Property name
   openfx::span<const PropType> supportedTypes; // Supported data types
   int dimension;                       // Property dimension (0 for variable)
   openfx::span<const char* const> enumValues;  // Valid values for enum properties
};

// Array type for storing all PropDefs, indexed by PropId for simplicity
template <typename T, PropId MaxValue = PropId::NProps>
struct PropDefsArray {
    static constexpr size_t Size = static_cast<size_t>(MaxValue);
    std::array<T, Size> data;

    // constexpr T& operator[](PropId index) {
    //   return data[static_cast<size_t>(index)];
    // }

    constexpr const T& operator[](PropId index) const {
        return data[static_cast<size_t>(index)];
    }
    constexpr const T& operator[](size_t index) const {
        return data[index];
    }
};

// Property definitions
static inline constexpr PropDefsArray<PropDef> prop_defs = {
  {{
{ "OfxImageClipPropColourspace",
  openfx::span(prop_type_arrays::OfxImageClipPropColourspace_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImageClipPropConnected",
  openfx::span(prop_type_arrays::OfxImageClipPropConnected_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImageClipPropContinuousSamples",
  openfx::span(prop_type_arrays::OfxImageClipPropContinuousSamples_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImageClipPropFieldExtraction",
  openfx::span(prop_type_arrays::OfxImageClipPropFieldExtraction_types, 1), 1, openfx::span(prop_enum_values::OfxImageClipPropFieldExtraction.data(), prop_enum_values::OfxImageClipPropFieldExtraction.size())},
{ "OfxImageClipPropFieldOrder",
  openfx::span(prop_type_arrays::OfxImageClipPropFieldOrder_types, 1), 1, openfx::span(prop_enum_values::OfxImageClipPropFieldOrder.data(), prop_enum_values::OfxImageClipPropFieldOrder.size())},
{ "OfxImageClipPropIsMask",
  openfx::span(prop_type_arrays::OfxImageClipPropIsMask_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImageClipPropOptional",
  openfx::span(prop_type_arrays::OfxImageClipPropOptional_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImageClipPropPreferredColourspaces",
  openfx::span(prop_type_arrays::OfxImageClipPropPreferredColourspaces_types, 1), 0, openfx::span<const char* const>()},
{ "OfxImageClipPropUnmappedComponents",
  openfx::span(prop_type_arrays::OfxImageClipPropUnmappedComponents_types, 1), 1, openfx::span(prop_enum_values::OfxImageClipPropUnmappedComponents.data(), prop_enum_values::OfxImageClipPropUnmappedComponents.size())},
{ "OfxImageClipPropUnmappedPixelDepth",
  openfx::span(prop_type_arrays::OfxImageClipPropUnmappedPixelDepth_types, 1), 1, openfx::span(prop_enum_values::OfxImageClipPropUnmappedPixelDepth.data(), prop_enum_values::OfxImageClipPropUnmappedPixelDepth.size())},
{ "OfxImageEffectFrameVarying",
  openfx::span(prop_type_arrays::OfxImageEffectFrameVarying_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImageEffectHostPropIsBackground",
  openfx::span(prop_type_arrays::OfxImageEffectHostPropIsBackground_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImageEffectHostPropNativeOrigin",
  openfx::span(prop_type_arrays::OfxImageEffectHostPropNativeOrigin_types, 1), 1, openfx::span(prop_enum_values::OfxImageEffectHostPropNativeOrigin.data(), prop_enum_values::OfxImageEffectHostPropNativeOrigin.size())},
{ "OfxImageEffectInstancePropEffectDuration",
  openfx::span(prop_type_arrays::OfxImageEffectInstancePropEffectDuration_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImageEffectInstancePropSequentialRender",
  openfx::span(prop_type_arrays::OfxImageEffectInstancePropSequentialRender_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImageEffectPluginPropFieldRenderTwiceAlways",
  openfx::span(prop_type_arrays::OfxImageEffectPluginPropFieldRenderTwiceAlways_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImageEffectPluginPropGrouping",
  openfx::span(prop_type_arrays::OfxImageEffectPluginPropGrouping_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImageEffectPluginPropHostFrameThreading",
  openfx::span(prop_type_arrays::OfxImageEffectPluginPropHostFrameThreading_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImageEffectPluginPropOverlayInteractV1",
  openfx::span(prop_type_arrays::OfxImageEffectPluginPropOverlayInteractV1_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImageEffectPluginPropOverlayInteractV2",
  openfx::span(prop_type_arrays::OfxImageEffectPluginPropOverlayInteractV2_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImageEffectPluginPropSingleInstance",
  openfx::span(prop_type_arrays::OfxImageEffectPluginPropSingleInstance_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImageEffectPluginRenderThreadSafety",
  openfx::span(prop_type_arrays::OfxImageEffectPluginRenderThreadSafety_types, 1), 1, openfx::span(prop_enum_values::OfxImageEffectPluginRenderThreadSafety.data(), prop_enum_values::OfxImageEffectPluginRenderThreadSafety.size())},
{ "OfxImageEffectPropClipPreferencesSlaveParam",
  openfx::span(prop_type_arrays::OfxImageEffectPropClipPreferencesSlaveParam_types, 1), 0, openfx::span<const char* const>()},
{ "OfxImageEffectPropColourManagementAvailableConfigs",
  openfx::span(prop_type_arrays::OfxImageEffectPropColourManagementAvailableConfigs_types, 1), 0, openfx::span<const char* const>()},
{ "OfxImageEffectPropColourManagementConfig",
  openfx::span(prop_type_arrays::OfxImageEffectPropColourManagementConfig_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImageEffectPropColourManagementStyle",
  openfx::span(prop_type_arrays::OfxImageEffectPropColourManagementStyle_types, 1), 1, openfx::span(prop_enum_values::OfxImageEffectPropColourManagementStyle.data(), prop_enum_values::OfxImageEffectPropColourManagementStyle.size())},
{ "OfxImageEffectPropComponents",
  openfx::span(prop_type_arrays::OfxImageEffectPropComponents_types, 1), 1, openfx::span(prop_enum_values::OfxImageEffectPropComponents.data(), prop_enum_values::OfxImageEffectPropComponents.size())},
{ "OfxImageEffectPropContext",
  openfx::span(prop_type_arrays::OfxImageEffectPropContext_types, 1), 1, openfx::span(prop_enum_values::OfxImageEffectPropContext.data(), prop_enum_values::OfxImageEffectPropContext.size())},
{ "OfxImageEffectPropCudaEnabled",
  openfx::span(prop_type_arrays::OfxImageEffectPropCudaEnabled_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImageEffectPropCudaRenderSupported",
  openfx::span(prop_type_arrays::OfxImageEffectPropCudaRenderSupported_types, 1), 1, openfx::span(prop_enum_values::OfxImageEffectPropCudaRenderSupported.data(), prop_enum_values::OfxImageEffectPropCudaRenderSupported.size())},
{ "OfxImageEffectPropCudaStream",
  openfx::span(prop_type_arrays::OfxImageEffectPropCudaStream_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImageEffectPropCudaStreamSupported",
  openfx::span(prop_type_arrays::OfxImageEffectPropCudaStreamSupported_types, 1), 1, openfx::span(prop_enum_values::OfxImageEffectPropCudaStreamSupported.data(), prop_enum_values::OfxImageEffectPropCudaStreamSupported.size())},
{ "OfxImageEffectPropDisplayColourspace",
  openfx::span(prop_type_arrays::OfxImageEffectPropDisplayColourspace_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImageEffectPropFieldToRender",
  openfx::span(prop_type_arrays::OfxImageEffectPropFieldToRender_types, 1), 1, openfx::span(prop_enum_values::OfxImageEffectPropFieldToRender.data(), prop_enum_values::OfxImageEffectPropFieldToRender.size())},
{ "OfxImageEffectPropFrameRange",
  openfx::span(prop_type_arrays::OfxImageEffectPropFrameRange_types, 1), 2, openfx::span<const char* const>()},
{ "OfxImageEffectPropFrameRate",
  openfx::span(prop_type_arrays::OfxImageEffectPropFrameRate_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImageEffectPropFrameStep",
  openfx::span(prop_type_arrays::OfxImageEffectPropFrameStep_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImageEffectPropInAnalysis",
  openfx::span(prop_type_arrays::OfxImageEffectPropInAnalysis_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImageEffectPropInteractiveRenderStatus",
  openfx::span(prop_type_arrays::OfxImageEffectPropInteractiveRenderStatus_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImageEffectPropMetalCommandQueue",
  openfx::span(prop_type_arrays::OfxImageEffectPropMetalCommandQueue_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImageEffectPropMetalEnabled",
  openfx::span(prop_type_arrays::OfxImageEffectPropMetalEnabled_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImageEffectPropMetalRenderSupported",
  openfx::span(prop_type_arrays::OfxImageEffectPropMetalRenderSupported_types, 1), 1, openfx::span(prop_enum_values::OfxImageEffectPropMetalRenderSupported.data(), prop_enum_values::OfxImageEffectPropMetalRenderSupported.size())},
{ "OfxImageEffectPropMultipleClipDepths",
  openfx::span(prop_type_arrays::OfxImageEffectPropMultipleClipDepths_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImageEffectPropNoSpatialAwareness",
  openfx::span(prop_type_arrays::OfxImageEffectPropNoSpatialAwareness_types, 1), 1, openfx::span(prop_enum_values::OfxImageEffectPropNoSpatialAwareness.data(), prop_enum_values::OfxImageEffectPropNoSpatialAwareness.size())},
{ "OfxImageEffectPropOCIOConfig",
  openfx::span(prop_type_arrays::OfxImageEffectPropOCIOConfig_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImageEffectPropOCIODisplay",
  openfx::span(prop_type_arrays::OfxImageEffectPropOCIODisplay_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImageEffectPropOCIOView",
  openfx::span(prop_type_arrays::OfxImageEffectPropOCIOView_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImageEffectPropOpenCLCommandQueue",
  openfx::span(prop_type_arrays::OfxImageEffectPropOpenCLCommandQueue_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImageEffectPropOpenCLEnabled",
  openfx::span(prop_type_arrays::OfxImageEffectPropOpenCLEnabled_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImageEffectPropOpenCLImage",
  openfx::span(prop_type_arrays::OfxImageEffectPropOpenCLImage_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImageEffectPropOpenCLRenderSupported",
  openfx::span(prop_type_arrays::OfxImageEffectPropOpenCLRenderSupported_types, 1), 1, openfx::span(prop_enum_values::OfxImageEffectPropOpenCLRenderSupported.data(), prop_enum_values::OfxImageEffectPropOpenCLRenderSupported.size())},
{ "OfxImageEffectPropOpenCLSupported",
  openfx::span(prop_type_arrays::OfxImageEffectPropOpenCLSupported_types, 1), 1, openfx::span(prop_enum_values::OfxImageEffectPropOpenCLSupported.data(), prop_enum_values::OfxImageEffectPropOpenCLSupported.size())},
{ "OfxImageEffectPropOpenGLEnabled",
  openfx::span(prop_type_arrays::OfxImageEffectPropOpenGLEnabled_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImageEffectPropOpenGLRenderSupported",
  openfx::span(prop_type_arrays::OfxImageEffectPropOpenGLRenderSupported_types, 1), 1, openfx::span(prop_enum_values::OfxImageEffectPropOpenGLRenderSupported.data(), prop_enum_values::OfxImageEffectPropOpenGLRenderSupported.size())},
{ "OfxImageEffectPropOpenGLTextureIndex",
  openfx::span(prop_type_arrays::OfxImageEffectPropOpenGLTextureIndex_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImageEffectPropOpenGLTextureTarget",
  openfx::span(prop_type_arrays::OfxImageEffectPropOpenGLTextureTarget_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImageEffectPropPixelAspectRatio",
  openfx::span(prop_type_arrays::OfxImageEffectPropPixelAspectRatio_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImageEffectPropPixelDepth",
  openfx::span(prop_type_arrays::OfxImageEffectPropPixelDepth_types, 1), 1, openfx::span(prop_enum_values::OfxImageEffectPropPixelDepth.data(), prop_enum_values::OfxImageEffectPropPixelDepth.size())},
{ "OfxImageEffectPropPluginHandle",
  openfx::span(prop_type_arrays::OfxImageEffectPropPluginHandle_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImageEffectPropPreMultiplication",
  openfx::span(prop_type_arrays::OfxImageEffectPropPreMultiplication_types, 1), 1, openfx::span(prop_enum_values::OfxImageEffectPropPreMultiplication.data(), prop_enum_values::OfxImageEffectPropPreMultiplication.size())},
{ "OfxImageEffectPropProjectExtent",
  openfx::span(prop_type_arrays::OfxImageEffectPropProjectExtent_types, 1), 2, openfx::span<const char* const>()},
{ "OfxImageEffectPropProjectOffset",
  openfx::span(prop_type_arrays::OfxImageEffectPropProjectOffset_types, 1), 2, openfx::span<const char* const>()},
{ "OfxImageEffectPropProjectSize",
  openfx::span(prop_type_arrays::OfxImageEffectPropProjectSize_types, 1), 2, openfx::span<const char* const>()},
{ "OfxImageEffectPropRegionOfDefinition",
  openfx::span(prop_type_arrays::OfxImageEffectPropRegionOfDefinition_types, 1), 4, openfx::span<const char* const>()},
{ "OfxImageEffectPropRegionOfInterest",
  openfx::span(prop_type_arrays::OfxImageEffectPropRegionOfInterest_types, 1), 4, openfx::span<const char* const>()},
{ "OfxImageEffectPropRenderQualityDraft",
  openfx::span(prop_type_arrays::OfxImageEffectPropRenderQualityDraft_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImageEffectPropRenderScale",
  openfx::span(prop_type_arrays::OfxImageEffectPropRenderScale_types, 1), 2, openfx::span<const char* const>()},
{ "OfxImageEffectPropRenderWindow",
  openfx::span(prop_type_arrays::OfxImageEffectPropRenderWindow_types, 1), 4, openfx::span<const char* const>()},
{ "OfxImageEffectPropSequentialRenderStatus",
  openfx::span(prop_type_arrays::OfxImageEffectPropSequentialRenderStatus_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImageEffectPropSetableFielding",
  openfx::span(prop_type_arrays::OfxImageEffectPropSetableFielding_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImageEffectPropSetableFrameRate",
  openfx::span(prop_type_arrays::OfxImageEffectPropSetableFrameRate_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImageEffectPropSupportedComponents",
  openfx::span(prop_type_arrays::OfxImageEffectPropSupportedComponents_types, 1), 0, openfx::span(prop_enum_values::OfxImageEffectPropSupportedComponents.data(), prop_enum_values::OfxImageEffectPropSupportedComponents.size())},
{ "OfxImageEffectPropSupportedContexts",
  openfx::span(prop_type_arrays::OfxImageEffectPropSupportedContexts_types, 1), 0, openfx::span(prop_enum_values::OfxImageEffectPropSupportedContexts.data(), prop_enum_values::OfxImageEffectPropSupportedContexts.size())},
{ "OfxImageEffectPropSupportedPixelDepths",
  openfx::span(prop_type_arrays::OfxImageEffectPropSupportedPixelDepths_types, 1), 0, openfx::span(prop_enum_values::OfxImageEffectPropSupportedPixelDepths.data(), prop_enum_values::OfxImageEffectPropSupportedPixelDepths.size())},
{ "OfxImageEffectPropSupportsMultiResolution",
  openfx::span(prop_type_arrays::OfxImageEffectPropSupportsMultiResolution_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImageEffectPropSupportsMultipleClipPARs",
  openfx::span(prop_type_arrays::OfxImageEffectPropSupportsMultipleClipPARs_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImageEffectPropSupportsOverlays",
  openfx::span(prop_type_arrays::OfxImageEffectPropSupportsOverlays_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImageEffectPropSupportsTiles",
  openfx::span(prop_type_arrays::OfxImageEffectPropSupportsTiles_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImageEffectPropTemporalClipAccess",
  openfx::span(prop_type_arrays::OfxImageEffectPropTemporalClipAccess_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImageEffectPropUnmappedFrameRange",
  openfx::span(prop_type_arrays::OfxImageEffectPropUnmappedFrameRange_types, 1), 2, openfx::span<const char* const>()},
{ "OfxImageEffectPropUnmappedFrameRate",
  openfx::span(prop_type_arrays::OfxImageEffectPropUnmappedFrameRate_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImagePropBounds",
  openfx::span(prop_type_arrays::OfxImagePropBounds_types, 1), 4, openfx::span<const char* const>()},
{ "OfxImagePropData",
  openfx::span(prop_type_arrays::OfxImagePropData_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImagePropField",
  openfx::span(prop_type_arrays::OfxImagePropField_types, 1), 1, openfx::span(prop_enum_values::OfxImagePropField.data(), prop_enum_values::OfxImagePropField.size())},
{ "OfxImagePropPixelAspectRatio",
  openfx::span(prop_type_arrays::OfxImagePropPixelAspectRatio_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImagePropRegionOfDefinition",
  openfx::span(prop_type_arrays::OfxImagePropRegionOfDefinition_types, 1), 4, openfx::span<const char* const>()},
{ "OfxImagePropRowBytes",
  openfx::span(prop_type_arrays::OfxImagePropRowBytes_types, 1), 1, openfx::span<const char* const>()},
{ "OfxImagePropUniqueIdentifier",
  openfx::span(prop_type_arrays::OfxImagePropUniqueIdentifier_types, 1), 1, openfx::span<const char* const>()},
{ "OfxInteractPropBackgroundColour",
  openfx::span(prop_type_arrays::OfxInteractPropBackgroundColour_types, 1), 3, openfx::span<const char* const>()},
{ "OfxInteractPropBitDepth",
  openfx::span(prop_type_arrays::OfxInteractPropBitDepth_types, 1), 1, openfx::span<const char* const>()},
{ "OfxInteractPropDrawContext",
  openfx::span(prop_type_arrays::OfxInteractPropDrawContext_types, 1), 1, openfx::span<const char* const>()},
{ "OfxInteractPropHasAlpha",
  openfx::span(prop_type_arrays::OfxInteractPropHasAlpha_types, 1), 1, openfx::span<const char* const>()},
{ "OfxInteractPropPenPosition",
  openfx::span(prop_type_arrays::OfxInteractPropPenPosition_types, 1), 2, openfx::span<const char* const>()},
{ "OfxInteractPropPenPressure",
  openfx::span(prop_type_arrays::OfxInteractPropPenPressure_types, 1), 1, openfx::span<const char* const>()},
{ "OfxInteractPropPenViewportPosition",
  openfx::span(prop_type_arrays::OfxInteractPropPenViewportPosition_types, 1), 2, openfx::span<const char* const>()},
{ "OfxInteractPropPixelScale",
  openfx::span(prop_type_arrays::OfxInteractPropPixelScale_types, 1), 2, openfx::span<const char* const>()},
{ "OfxInteractPropSlaveToParam",
  openfx::span(prop_type_arrays::OfxInteractPropSlaveToParam_types, 1), 0, openfx::span<const char* const>()},
{ "OfxInteractPropSuggestedColour",
  openfx::span(prop_type_arrays::OfxInteractPropSuggestedColour_types, 1), 3, openfx::span<const char* const>()},
{ "OfxInteractPropViewport",
  openfx::span(prop_type_arrays::OfxInteractPropViewport_types, 1), 2, openfx::span<const char* const>()},
{ "OfxOpenGLPropPixelDepth",
  openfx::span(prop_type_arrays::OfxOpenGLPropPixelDepth_types, 1), 0, openfx::span(prop_enum_values::OfxOpenGLPropPixelDepth.data(), prop_enum_values::OfxOpenGLPropPixelDepth.size())},
{ "OfxParamHostPropMaxPages",
  openfx::span(prop_type_arrays::OfxParamHostPropMaxPages_types, 1), 1, openfx::span<const char* const>()},
{ "OfxParamHostPropMaxParameters",
  openfx::span(prop_type_arrays::OfxParamHostPropMaxParameters_types, 1), 1, openfx::span<const char* const>()},
{ "OfxParamHostPropPageRowColumnCount",
  openfx::span(prop_type_arrays::OfxParamHostPropPageRowColumnCount_types, 1), 2, openfx::span<const char* const>()},
{ "OfxParamHostPropSupportsBooleanAnimation",
  openfx::span(prop_type_arrays::OfxParamHostPropSupportsBooleanAnimation_types, 1), 1, openfx::span<const char* const>()},
{ "OfxParamHostPropSupportsChoiceAnimation",
  openfx::span(prop_type_arrays::OfxParamHostPropSupportsChoiceAnimation_types, 1), 1, openfx::span<const char* const>()},
{ "OfxParamHostPropSupportsCustomAnimation",
  openfx::span(prop_type_arrays::OfxParamHostPropSupportsCustomAnimation_types, 1), 1, openfx::span<const char* const>()},
{ "OfxParamHostPropSupportsCustomInteract",
  openfx::span(prop_type_arrays::OfxParamHostPropSupportsCustomInteract_types, 1), 1, openfx::span<const char* const>()},
{ "OfxParamHostPropSupportsParametricAnimation",
  openfx::span(prop_type_arrays::OfxParamHostPropSupportsParametricAnimation_types, 1), 1, openfx::span<const char* const>()},
{ "OfxParamHostPropSupportsStrChoice",
  openfx::span(prop_type_arrays::OfxParamHostPropSupportsStrChoice_types, 1), 1, openfx::span<const char* const>()},
{ "OfxParamHostPropSupportsStrChoiceAnimation",
  openfx::span(prop_type_arrays::OfxParamHostPropSupportsStrChoiceAnimation_types, 1), 1, openfx::span<const char* const>()},
{ "OfxParamHostPropSupportsStringAnimation",
  openfx::span(prop_type_arrays::OfxParamHostPropSupportsStringAnimation_types, 1), 1, openfx::span<const char* const>()},
{ "OfxParamPropAnimates",
  openfx::span(prop_type_arrays::OfxParamPropAnimates_types, 1), 1, openfx::span<const char* const>()},
{ "OfxParamPropCacheInvalidation",
  openfx::span(prop_type_arrays::OfxParamPropCacheInvalidation_types, 1), 1, openfx::span(prop_enum_values::OfxParamPropCacheInvalidation.data(), prop_enum_values::OfxParamPropCacheInvalidation.size())},
{ "OfxParamPropCanUndo",
  openfx::span(prop_type_arrays::OfxParamPropCanUndo_types, 1), 1, openfx::span<const char* const>()},
{ "OfxParamPropChoiceEnum",
  openfx::span(prop_type_arrays::OfxParamPropChoiceEnum_types, 1), 1, openfx::span<const char* const>()},
{ "OfxParamPropChoiceOption",
  openfx::span(prop_type_arrays::OfxParamPropChoiceOption_types, 1), 0, openfx::span<const char* const>()},
{ "OfxParamPropChoiceOrder",
  openfx::span(prop_type_arrays::OfxParamPropChoiceOrder_types, 1), 0, openfx::span<const char* const>()},
{ "OfxParamPropCustomCallbackV1",
  openfx::span(prop_type_arrays::OfxParamPropCustomCallbackV1_types, 1), 1, openfx::span<const char* const>()},
{ "OfxParamPropCustomValue",
  openfx::span(prop_type_arrays::OfxParamPropCustomValue_types, 1), 2, openfx::span<const char* const>()},
{ "OfxParamPropDataPtr",
  openfx::span(prop_type_arrays::OfxParamPropDataPtr_types, 1), 1, openfx::span<const char* const>()},
{ "OfxParamPropDefault",
  openfx::span(prop_type_arrays::OfxParamPropDefault_types, 4), 0, openfx::span<const char* const>()},
{ "OfxParamPropDefaultCoordinateSystem",
  openfx::span(prop_type_arrays::OfxParamPropDefaultCoordinateSystem_types, 1), 1, openfx::span(prop_enum_values::OfxParamPropDefaultCoordinateSystem.data(), prop_enum_values::OfxParamPropDefaultCoordinateSystem.size())},
{ "OfxParamPropDigits",
  openfx::span(prop_type_arrays::OfxParamPropDigits_types, 1), 1, openfx::span<const char* const>()},
{ "OfxParamPropDimensionLabel",
  openfx::span(prop_type_arrays::OfxParamPropDimensionLabel_types, 1), 1, openfx::span<const char* const>()},
{ "OfxParamPropDisplayMax",
  openfx::span(prop_type_arrays::OfxParamPropDisplayMax_types, 2), 0, openfx::span<const char* const>()},
{ "OfxParamPropDisplayMin",
  openfx::span(prop_type_arrays::OfxParamPropDisplayMin_types, 2), 0, openfx::span<const char* const>()},
{ "OfxParamPropDoubleType",
  openfx::span(prop_type_arrays::OfxParamPropDoubleType_types, 1), 1, openfx::span(prop_enum_values::OfxParamPropDoubleType.data(), prop_enum_values::OfxParamPropDoubleType.size())},
{ "OfxParamPropEnabled",
  openfx::span(prop_type_arrays::OfxParamPropEnabled_types, 1), 1, openfx::span<const char* const>()},
{ "OfxParamPropEvaluateOnChange",
  openfx::span(prop_type_arrays::OfxParamPropEvaluateOnChange_types, 1), 1, openfx::span<const char* const>()},
{ "OfxParamPropGroupOpen",
  openfx::span(prop_type_arrays::OfxParamPropGroupOpen_types, 1), 1, openfx::span<const char* const>()},
{ "OfxParamPropHasHostOverlayHandle",
  openfx::span(prop_type_arrays::OfxParamPropHasHostOverlayHandle_types, 1), 1, openfx::span<const char* const>()},
{ "OfxParamPropHint",
  openfx::span(prop_type_arrays::OfxParamPropHint_types, 1), 1, openfx::span<const char* const>()},
{ "OfxParamPropIncrement",
  openfx::span(prop_type_arrays::OfxParamPropIncrement_types, 1), 1, openfx::span<const char* const>()},
{ "OfxParamPropInteractMinimumSize",
  openfx::span(prop_type_arrays::OfxParamPropInteractMinimumSize_types, 1), 2, openfx::span<const char* const>()},
{ "OfxParamPropInteractPreferedSize",
  openfx::span(prop_type_arrays::OfxParamPropInteractPreferedSize_types, 1), 2, openfx::span<const char* const>()},
{ "OfxParamPropInteractSize",
  openfx::span(prop_type_arrays::OfxParamPropInteractSize_types, 1), 2, openfx::span<const char* const>()},
{ "OfxParamPropInteractSizeAspect",
  openfx::span(prop_type_arrays::OfxParamPropInteractSizeAspect_types, 1), 1, openfx::span<const char* const>()},
{ "OfxParamPropInteractV1",
  openfx::span(prop_type_arrays::OfxParamPropInteractV1_types, 1), 1, openfx::span<const char* const>()},
{ "OfxParamPropInterpolationAmount",
  openfx::span(prop_type_arrays::OfxParamPropInterpolationAmount_types, 1), 1, openfx::span<const char* const>()},
{ "OfxParamPropInterpolationTime",
  openfx::span(prop_type_arrays::OfxParamPropInterpolationTime_types, 1), 2, openfx::span<const char* const>()},
{ "OfxParamPropIsAnimating",
  openfx::span(prop_type_arrays::OfxParamPropIsAnimating_types, 1), 1, openfx::span<const char* const>()},
{ "OfxParamPropIsAutoKeying",
  openfx::span(prop_type_arrays::OfxParamPropIsAutoKeying_types, 1), 1, openfx::span<const char* const>()},
{ "OfxParamPropMax",
  openfx::span(prop_type_arrays::OfxParamPropMax_types, 2), 0, openfx::span<const char* const>()},
{ "OfxParamPropMin",
  openfx::span(prop_type_arrays::OfxParamPropMin_types, 2), 0, openfx::span<const char* const>()},
{ "OfxParamPropPageChild",
  openfx::span(prop_type_arrays::OfxParamPropPageChild_types, 1), 0, openfx::span<const char* const>()},
{ "OfxParamPropParametricDimension",
  openfx::span(prop_type_arrays::OfxParamPropParametricDimension_types, 1), 1, openfx::span<const char* const>()},
{ "OfxParamPropParametricInteractBackground",
  openfx::span(prop_type_arrays::OfxParamPropParametricInteractBackground_types, 1), 1, openfx::span<const char* const>()},
{ "OfxParamPropParametricRange",
  openfx::span(prop_type_arrays::OfxParamPropParametricRange_types, 1), 2, openfx::span<const char* const>()},
{ "OfxParamPropParametricUIColour",
  openfx::span(prop_type_arrays::OfxParamPropParametricUIColour_types, 1), 0, openfx::span<const char* const>()},
{ "OfxParamPropParent",
  openfx::span(prop_type_arrays::OfxParamPropParent_types, 1), 1, openfx::span<const char* const>()},
{ "OfxParamPropPersistant",
  openfx::span(prop_type_arrays::OfxParamPropPersistant_types, 1), 1, openfx::span<const char* const>()},
{ "OfxParamPropPluginMayWrite",
  openfx::span(prop_type_arrays::OfxParamPropPluginMayWrite_types, 1), 1, openfx::span<const char* const>()},
{ "OfxParamPropScriptName",
  openfx::span(prop_type_arrays::OfxParamPropScriptName_types, 1), 1, openfx::span<const char* const>()},
{ "OfxParamPropSecret",
  openfx::span(prop_type_arrays::OfxParamPropSecret_types, 1), 1, openfx::span<const char* const>()},
{ "OfxParamPropShowTimeMarker",
  openfx::span(prop_type_arrays::OfxParamPropShowTimeMarker_types, 1), 1, openfx::span<const char* const>()},
{ "OfxParamPropStringFilePathExists",
  openfx::span(prop_type_arrays::OfxParamPropStringFilePathExists_types, 1), 1, openfx::span<const char* const>()},
{ "OfxParamPropStringMode",
  openfx::span(prop_type_arrays::OfxParamPropStringMode_types, 1), 1, openfx::span(prop_enum_values::OfxParamPropStringMode.data(), prop_enum_values::OfxParamPropStringMode.size())},
{ "OfxParamPropType",
  openfx::span(prop_type_arrays::OfxParamPropType_types, 1), 1, openfx::span<const char* const>()},
{ "OfxPluginPropFilePath",
  openfx::span(prop_type_arrays::OfxPluginPropFilePath_types, 1), 1, openfx::span<const char* const>()},
{ "OfxPluginPropParamPageOrder",
  openfx::span(prop_type_arrays::OfxPluginPropParamPageOrder_types, 1), 0, openfx::span<const char* const>()},
{ "OfxPropAPIVersion",
  openfx::span(prop_type_arrays::OfxPropAPIVersion_types, 1), 0, openfx::span<const char* const>()},
{ "OfxPropChangeReason",
  openfx::span(prop_type_arrays::OfxPropChangeReason_types, 1), 1, openfx::span(prop_enum_values::OfxPropChangeReason.data(), prop_enum_values::OfxPropChangeReason.size())},
{ "OfxPropEffectInstance",
  openfx::span(prop_type_arrays::OfxPropEffectInstance_types, 1), 1, openfx::span<const char* const>()},
{ "OfxPropHostOSHandle",
  openfx::span(prop_type_arrays::OfxPropHostOSHandle_types, 1), 1, openfx::span<const char* const>()},
{ "OfxPropIcon",
  openfx::span(prop_type_arrays::OfxPropIcon_types, 1), 2, openfx::span<const char* const>()},
{ "OfxPropInstanceData",
  openfx::span(prop_type_arrays::OfxPropInstanceData_types, 1), 1, openfx::span<const char* const>()},
{ "OfxPropIsInteractive",
  openfx::span(prop_type_arrays::OfxPropIsInteractive_types, 1), 1, openfx::span<const char* const>()},
{ "OfxPropLabel",
  openfx::span(prop_type_arrays::OfxPropLabel_types, 1), 1, openfx::span<const char* const>()},
{ "OfxPropLongLabel",
  openfx::span(prop_type_arrays::OfxPropLongLabel_types, 1), 1, openfx::span<const char* const>()},
{ "OfxPropName",
  openfx::span(prop_type_arrays::OfxPropName_types, 1), 1, openfx::span<const char* const>()},
{ "OfxPropParamSetNeedsSyncing",
  openfx::span(prop_type_arrays::OfxPropParamSetNeedsSyncing_types, 1), 1, openfx::span<const char* const>()},
{ "OfxPropPluginDescription",
  openfx::span(prop_type_arrays::OfxPropPluginDescription_types, 1), 1, openfx::span<const char* const>()},
{ "OfxPropShortLabel",
  openfx::span(prop_type_arrays::OfxPropShortLabel_types, 1), 1, openfx::span<const char* const>()},
{ "OfxPropTime",
  openfx::span(prop_type_arrays::OfxPropTime_types, 1), 1, openfx::span<const char* const>()},
{ "OfxPropType",
  openfx::span(prop_type_arrays::OfxPropType_types, 1), 1, openfx::span<const char* const>()},
{ "OfxPropVersion",
  openfx::span(prop_type_arrays::OfxPropVersion_types, 1), 0, openfx::span<const char* const>()},
{ "OfxPropVersionLabel",
  openfx::span(prop_type_arrays::OfxPropVersionLabel_types, 1), 1, openfx::span<const char* const>()},
{ "kOfxParamPropUseHostOverlayHandle",
  openfx::span(prop_type_arrays::kOfxParamPropUseHostOverlayHandle_types, 1), 1, openfx::span<const char* const>()},
{ "kOfxPropKeyString",
  openfx::span(prop_type_arrays::kOfxPropKeyString_types, 1), 1, openfx::span<const char* const>()},
{ "kOfxPropKeySym",
  openfx::span(prop_type_arrays::kOfxPropKeySym_types, 1), 1, openfx::span<const char* const>()},
 }}
};


//Template specializations for each property
namespace properties {

// Base template struct for property traits
template<PropId id>
struct PropTraits;

#define DEFINE_PROP_TRAITS(id, _type, _is_multitype) \
template<> \
struct PropTraits<PropId::id> { \
    using type = _type; \
    static constexpr bool is_multitype = _is_multitype; \
    static constexpr const PropDef& def = prop_defs[PropId::id]; \
}

DEFINE_PROP_TRAITS(OfxImageClipPropColourspace, const char *, false);
DEFINE_PROP_TRAITS(OfxImageClipPropConnected, bool, false);
DEFINE_PROP_TRAITS(OfxImageClipPropContinuousSamples, bool, false);
DEFINE_PROP_TRAITS(OfxImageClipPropFieldExtraction, const char *, false);
DEFINE_PROP_TRAITS(OfxImageClipPropFieldOrder, const char *, false);
DEFINE_PROP_TRAITS(OfxImageClipPropIsMask, bool, false);
DEFINE_PROP_TRAITS(OfxImageClipPropOptional, bool, false);
DEFINE_PROP_TRAITS(OfxImageClipPropPreferredColourspaces, const char *, false);
DEFINE_PROP_TRAITS(OfxImageClipPropUnmappedComponents, const char *, false);
DEFINE_PROP_TRAITS(OfxImageClipPropUnmappedPixelDepth, const char *, false);
DEFINE_PROP_TRAITS(OfxImageEffectFrameVarying, bool, false);
DEFINE_PROP_TRAITS(OfxImageEffectHostPropIsBackground, bool, false);
DEFINE_PROP_TRAITS(OfxImageEffectHostPropNativeOrigin, const char *, false);
DEFINE_PROP_TRAITS(OfxImageEffectInstancePropEffectDuration, double, false);
DEFINE_PROP_TRAITS(OfxImageEffectInstancePropSequentialRender, bool, false);
DEFINE_PROP_TRAITS(OfxImageEffectPluginPropFieldRenderTwiceAlways, bool, false);
DEFINE_PROP_TRAITS(OfxImageEffectPluginPropGrouping, const char *, false);
DEFINE_PROP_TRAITS(OfxImageEffectPluginPropHostFrameThreading, bool, false);
DEFINE_PROP_TRAITS(OfxImageEffectPluginPropOverlayInteractV1, void *, false);
DEFINE_PROP_TRAITS(OfxImageEffectPluginPropOverlayInteractV2, void *, false);
DEFINE_PROP_TRAITS(OfxImageEffectPluginPropSingleInstance, bool, false);
DEFINE_PROP_TRAITS(OfxImageEffectPluginRenderThreadSafety, const char *, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropClipPreferencesSlaveParam, const char *, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropColourManagementAvailableConfigs, const char *, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropColourManagementConfig, const char *, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropColourManagementStyle, const char *, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropComponents, const char *, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropContext, const char *, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropCudaEnabled, bool, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropCudaRenderSupported, const char *, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropCudaStream, void *, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropCudaStreamSupported, const char *, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropDisplayColourspace, const char *, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropFieldToRender, const char *, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropFrameRange, double, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropFrameRate, double, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropFrameStep, double, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropInAnalysis, bool, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropInteractiveRenderStatus, bool, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropMetalCommandQueue, void *, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropMetalEnabled, bool, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropMetalRenderSupported, const char *, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropMultipleClipDepths, bool, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropNoSpatialAwareness, const char *, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropOCIOConfig, const char *, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropOCIODisplay, const char *, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropOCIOView, const char *, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropOpenCLCommandQueue, void *, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropOpenCLEnabled, bool, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropOpenCLImage, void *, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropOpenCLRenderSupported, const char *, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropOpenCLSupported, const char *, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropOpenGLEnabled, bool, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropOpenGLRenderSupported, const char *, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropOpenGLTextureIndex, int, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropOpenGLTextureTarget, int, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropPixelAspectRatio, double, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropPixelDepth, const char *, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropPluginHandle, void *, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropPreMultiplication, const char *, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropProjectExtent, double, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropProjectOffset, double, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropProjectSize, double, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropRegionOfDefinition, double, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropRegionOfInterest, double, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropRenderQualityDraft, bool, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropRenderScale, double, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropRenderWindow, int, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropSequentialRenderStatus, bool, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropSetableFielding, bool, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropSetableFrameRate, bool, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropSupportedComponents, const char *, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropSupportedContexts, const char *, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropSupportedPixelDepths, const char *, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropSupportsMultiResolution, bool, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropSupportsMultipleClipPARs, bool, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropSupportsOverlays, bool, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropSupportsTiles, bool, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropTemporalClipAccess, bool, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropUnmappedFrameRange, double, false);
DEFINE_PROP_TRAITS(OfxImageEffectPropUnmappedFrameRate, double, false);
DEFINE_PROP_TRAITS(OfxImagePropBounds, int, false);
DEFINE_PROP_TRAITS(OfxImagePropData, void *, false);
DEFINE_PROP_TRAITS(OfxImagePropField, const char *, false);
DEFINE_PROP_TRAITS(OfxImagePropPixelAspectRatio, double, false);
DEFINE_PROP_TRAITS(OfxImagePropRegionOfDefinition, int, false);
DEFINE_PROP_TRAITS(OfxImagePropRowBytes, int, false);
DEFINE_PROP_TRAITS(OfxImagePropUniqueIdentifier, const char *, false);
DEFINE_PROP_TRAITS(OfxInteractPropBackgroundColour, double, false);
DEFINE_PROP_TRAITS(OfxInteractPropBitDepth, int, false);
DEFINE_PROP_TRAITS(OfxInteractPropDrawContext, void *, false);
DEFINE_PROP_TRAITS(OfxInteractPropHasAlpha, bool, false);
DEFINE_PROP_TRAITS(OfxInteractPropPenPosition, double, false);
DEFINE_PROP_TRAITS(OfxInteractPropPenPressure, double, false);
DEFINE_PROP_TRAITS(OfxInteractPropPenViewportPosition, int, false);
DEFINE_PROP_TRAITS(OfxInteractPropPixelScale, double, false);
DEFINE_PROP_TRAITS(OfxInteractPropSlaveToParam, const char *, false);
DEFINE_PROP_TRAITS(OfxInteractPropSuggestedColour, double, false);
DEFINE_PROP_TRAITS(OfxInteractPropViewport, int, false);
DEFINE_PROP_TRAITS(OfxOpenGLPropPixelDepth, const char *, false);
DEFINE_PROP_TRAITS(OfxParamHostPropMaxPages, int, false);
DEFINE_PROP_TRAITS(OfxParamHostPropMaxParameters, int, false);
DEFINE_PROP_TRAITS(OfxParamHostPropPageRowColumnCount, int, false);
DEFINE_PROP_TRAITS(OfxParamHostPropSupportsBooleanAnimation, bool, false);
DEFINE_PROP_TRAITS(OfxParamHostPropSupportsChoiceAnimation, bool, false);
DEFINE_PROP_TRAITS(OfxParamHostPropSupportsCustomAnimation, bool, false);
DEFINE_PROP_TRAITS(OfxParamHostPropSupportsCustomInteract, bool, false);
DEFINE_PROP_TRAITS(OfxParamHostPropSupportsParametricAnimation, bool, false);
DEFINE_PROP_TRAITS(OfxParamHostPropSupportsStrChoice, bool, false);
DEFINE_PROP_TRAITS(OfxParamHostPropSupportsStrChoiceAnimation, bool, false);
DEFINE_PROP_TRAITS(OfxParamHostPropSupportsStringAnimation, bool, false);
DEFINE_PROP_TRAITS(OfxParamPropAnimates, bool, false);
DEFINE_PROP_TRAITS(OfxParamPropCacheInvalidation, const char *, false);
DEFINE_PROP_TRAITS(OfxParamPropCanUndo, bool, false);
DEFINE_PROP_TRAITS(OfxParamPropChoiceEnum, bool, false);
DEFINE_PROP_TRAITS(OfxParamPropChoiceOption, const char *, false);
DEFINE_PROP_TRAITS(OfxParamPropChoiceOrder, int, false);
DEFINE_PROP_TRAITS(OfxParamPropCustomCallbackV1, void *, false);
DEFINE_PROP_TRAITS(OfxParamPropCustomValue, const char *, false);
DEFINE_PROP_TRAITS(OfxParamPropDataPtr, void *, false);
DEFINE_PROP_TRAITS(OfxParamPropDefault, int, true);
DEFINE_PROP_TRAITS(OfxParamPropDefaultCoordinateSystem, const char *, false);
DEFINE_PROP_TRAITS(OfxParamPropDigits, int, false);
DEFINE_PROP_TRAITS(OfxParamPropDimensionLabel, const char *, false);
DEFINE_PROP_TRAITS(OfxParamPropDisplayMax, int, true);
DEFINE_PROP_TRAITS(OfxParamPropDisplayMin, int, true);
DEFINE_PROP_TRAITS(OfxParamPropDoubleType, const char *, false);
DEFINE_PROP_TRAITS(OfxParamPropEnabled, bool, false);
DEFINE_PROP_TRAITS(OfxParamPropEvaluateOnChange, bool, false);
DEFINE_PROP_TRAITS(OfxParamPropGroupOpen, bool, false);
DEFINE_PROP_TRAITS(OfxParamPropHasHostOverlayHandle, bool, false);
DEFINE_PROP_TRAITS(OfxParamPropHint, const char *, false);
DEFINE_PROP_TRAITS(OfxParamPropIncrement, double, false);
DEFINE_PROP_TRAITS(OfxParamPropInteractMinimumSize, double, false);
DEFINE_PROP_TRAITS(OfxParamPropInteractPreferedSize, int, false);
DEFINE_PROP_TRAITS(OfxParamPropInteractSize, double, false);
DEFINE_PROP_TRAITS(OfxParamPropInteractSizeAspect, double, false);
DEFINE_PROP_TRAITS(OfxParamPropInteractV1, void *, false);
DEFINE_PROP_TRAITS(OfxParamPropInterpolationAmount, double, false);
DEFINE_PROP_TRAITS(OfxParamPropInterpolationTime, double, false);
DEFINE_PROP_TRAITS(OfxParamPropIsAnimating, bool, false);
DEFINE_PROP_TRAITS(OfxParamPropIsAutoKeying, bool, false);
DEFINE_PROP_TRAITS(OfxParamPropMax, int, true);
DEFINE_PROP_TRAITS(OfxParamPropMin, int, true);
DEFINE_PROP_TRAITS(OfxParamPropPageChild, const char *, false);
DEFINE_PROP_TRAITS(OfxParamPropParametricDimension, int, false);
DEFINE_PROP_TRAITS(OfxParamPropParametricInteractBackground, void *, false);
DEFINE_PROP_TRAITS(OfxParamPropParametricRange, double, false);
DEFINE_PROP_TRAITS(OfxParamPropParametricUIColour, double, false);
DEFINE_PROP_TRAITS(OfxParamPropParent, const char *, false);
DEFINE_PROP_TRAITS(OfxParamPropPersistant, bool, false);
DEFINE_PROP_TRAITS(OfxParamPropPluginMayWrite, bool, false);
DEFINE_PROP_TRAITS(OfxParamPropScriptName, const char *, false);
DEFINE_PROP_TRAITS(OfxParamPropSecret, bool, false);
DEFINE_PROP_TRAITS(OfxParamPropShowTimeMarker, bool, false);
DEFINE_PROP_TRAITS(OfxParamPropStringFilePathExists, bool, false);
DEFINE_PROP_TRAITS(OfxParamPropStringMode, const char *, false);
DEFINE_PROP_TRAITS(OfxParamPropType, const char *, false);
DEFINE_PROP_TRAITS(OfxPluginPropFilePath, const char *, false);
DEFINE_PROP_TRAITS(OfxPluginPropParamPageOrder, const char *, false);
DEFINE_PROP_TRAITS(OfxPropAPIVersion, int, false);
DEFINE_PROP_TRAITS(OfxPropChangeReason, const char *, false);
DEFINE_PROP_TRAITS(OfxPropEffectInstance, void *, false);
DEFINE_PROP_TRAITS(OfxPropHostOSHandle, void *, false);
DEFINE_PROP_TRAITS(OfxPropIcon, const char *, false);
DEFINE_PROP_TRAITS(OfxPropInstanceData, void *, false);
DEFINE_PROP_TRAITS(OfxPropIsInteractive, bool, false);
DEFINE_PROP_TRAITS(OfxPropLabel, const char *, false);
DEFINE_PROP_TRAITS(OfxPropLongLabel, const char *, false);
DEFINE_PROP_TRAITS(OfxPropName, const char *, false);
DEFINE_PROP_TRAITS(OfxPropParamSetNeedsSyncing, bool, false);
DEFINE_PROP_TRAITS(OfxPropPluginDescription, const char *, false);
DEFINE_PROP_TRAITS(OfxPropShortLabel, const char *, false);
DEFINE_PROP_TRAITS(OfxPropTime, double, false);
DEFINE_PROP_TRAITS(OfxPropType, const char *, false);
DEFINE_PROP_TRAITS(OfxPropVersion, int, false);
DEFINE_PROP_TRAITS(OfxPropVersionLabel, const char *, false);
DEFINE_PROP_TRAITS(OfxParamPropUseHostOverlayHandle, bool, false);
DEFINE_PROP_TRAITS(OfxPropKeyString, const char *, false);
DEFINE_PROP_TRAITS(OfxPropKeySym, int, false);
} // namespace properties

// Static asserts to check #define names vs. strings
namespace assertions {
using std::string_view;

static_assert(string_view("OfxImageClipPropColourspace") == string_view(kOfxImageClipPropColourspace));
static_assert(string_view("OfxImageClipPropConnected") == string_view(kOfxImageClipPropConnected));
static_assert(string_view("OfxImageClipPropContinuousSamples") == string_view(kOfxImageClipPropContinuousSamples));
static_assert(string_view("OfxImageClipPropFieldExtraction") == string_view(kOfxImageClipPropFieldExtraction));
static_assert(string_view("OfxImageClipPropFieldOrder") == string_view(kOfxImageClipPropFieldOrder));
static_assert(string_view("OfxImageClipPropIsMask") == string_view(kOfxImageClipPropIsMask));
static_assert(string_view("OfxImageClipPropOptional") == string_view(kOfxImageClipPropOptional));
static_assert(string_view("OfxImageClipPropPreferredColourspaces") == string_view(kOfxImageClipPropPreferredColourspaces));
static_assert(string_view("OfxImageClipPropUnmappedComponents") == string_view(kOfxImageClipPropUnmappedComponents));
static_assert(string_view("OfxImageClipPropUnmappedPixelDepth") == string_view(kOfxImageClipPropUnmappedPixelDepth));
static_assert(string_view("OfxImageEffectFrameVarying") == string_view(kOfxImageEffectFrameVarying));
static_assert(string_view("OfxImageEffectHostPropIsBackground") == string_view(kOfxImageEffectHostPropIsBackground));
static_assert(string_view("OfxImageEffectHostPropNativeOrigin") == string_view(kOfxImageEffectHostPropNativeOrigin));
static_assert(string_view("OfxImageEffectInstancePropEffectDuration") == string_view(kOfxImageEffectInstancePropEffectDuration));
static_assert(string_view("OfxImageEffectInstancePropSequentialRender") == string_view(kOfxImageEffectInstancePropSequentialRender));
static_assert(string_view("OfxImageEffectPluginPropFieldRenderTwiceAlways") == string_view(kOfxImageEffectPluginPropFieldRenderTwiceAlways));
static_assert(string_view("OfxImageEffectPluginPropGrouping") == string_view(kOfxImageEffectPluginPropGrouping));
static_assert(string_view("OfxImageEffectPluginPropHostFrameThreading") == string_view(kOfxImageEffectPluginPropHostFrameThreading));
static_assert(string_view("OfxImageEffectPluginPropOverlayInteractV1") == string_view(kOfxImageEffectPluginPropOverlayInteractV1));
static_assert(string_view("OfxImageEffectPluginPropOverlayInteractV2") == string_view(kOfxImageEffectPluginPropOverlayInteractV2));
static_assert(string_view("OfxImageEffectPluginPropSingleInstance") == string_view(kOfxImageEffectPluginPropSingleInstance));
static_assert(string_view("OfxImageEffectPluginRenderThreadSafety") == string_view(kOfxImageEffectPluginRenderThreadSafety));
static_assert(string_view("OfxImageEffectPropClipPreferencesSlaveParam") == string_view(kOfxImageEffectPropClipPreferencesSlaveParam));
static_assert(string_view("OfxImageEffectPropColourManagementAvailableConfigs") == string_view(kOfxImageEffectPropColourManagementAvailableConfigs));
static_assert(string_view("OfxImageEffectPropColourManagementConfig") == string_view(kOfxImageEffectPropColourManagementConfig));
static_assert(string_view("OfxImageEffectPropColourManagementStyle") == string_view(kOfxImageEffectPropColourManagementStyle));
static_assert(string_view("OfxImageEffectPropComponents") == string_view(kOfxImageEffectPropComponents));
static_assert(string_view("OfxImageEffectPropContext") == string_view(kOfxImageEffectPropContext));
static_assert(string_view("OfxImageEffectPropCudaEnabled") == string_view(kOfxImageEffectPropCudaEnabled));
static_assert(string_view("OfxImageEffectPropCudaRenderSupported") == string_view(kOfxImageEffectPropCudaRenderSupported));
static_assert(string_view("OfxImageEffectPropCudaStream") == string_view(kOfxImageEffectPropCudaStream));
static_assert(string_view("OfxImageEffectPropCudaStreamSupported") == string_view(kOfxImageEffectPropCudaStreamSupported));
static_assert(string_view("OfxImageEffectPropDisplayColourspace") == string_view(kOfxImageEffectPropDisplayColourspace));
static_assert(string_view("OfxImageEffectPropFieldToRender") == string_view(kOfxImageEffectPropFieldToRender));
static_assert(string_view("OfxImageEffectPropFrameRange") == string_view(kOfxImageEffectPropFrameRange));
static_assert(string_view("OfxImageEffectPropFrameRate") == string_view(kOfxImageEffectPropFrameRate));
static_assert(string_view("OfxImageEffectPropFrameStep") == string_view(kOfxImageEffectPropFrameStep));
static_assert(string_view("OfxImageEffectPropInAnalysis") == string_view(kOfxImageEffectPropInAnalysis));
static_assert(string_view("OfxImageEffectPropInteractiveRenderStatus") == string_view(kOfxImageEffectPropInteractiveRenderStatus));
static_assert(string_view("OfxImageEffectPropMetalCommandQueue") == string_view(kOfxImageEffectPropMetalCommandQueue));
static_assert(string_view("OfxImageEffectPropMetalEnabled") == string_view(kOfxImageEffectPropMetalEnabled));
static_assert(string_view("OfxImageEffectPropMetalRenderSupported") == string_view(kOfxImageEffectPropMetalRenderSupported));
static_assert(string_view("OfxImageEffectPropMultipleClipDepths") == string_view(kOfxImageEffectPropSupportsMultipleClipDepths));
static_assert(string_view("OfxImageEffectPropNoSpatialAwareness") == string_view(kOfxImageEffectPropNoSpatialAwareness));
static_assert(string_view("OfxImageEffectPropOCIOConfig") == string_view(kOfxImageEffectPropOCIOConfig));
static_assert(string_view("OfxImageEffectPropOCIODisplay") == string_view(kOfxImageEffectPropOCIODisplay));
static_assert(string_view("OfxImageEffectPropOCIOView") == string_view(kOfxImageEffectPropOCIOView));
static_assert(string_view("OfxImageEffectPropOpenCLCommandQueue") == string_view(kOfxImageEffectPropOpenCLCommandQueue));
static_assert(string_view("OfxImageEffectPropOpenCLEnabled") == string_view(kOfxImageEffectPropOpenCLEnabled));
static_assert(string_view("OfxImageEffectPropOpenCLImage") == string_view(kOfxImageEffectPropOpenCLImage));
static_assert(string_view("OfxImageEffectPropOpenCLRenderSupported") == string_view(kOfxImageEffectPropOpenCLRenderSupported));
static_assert(string_view("OfxImageEffectPropOpenCLSupported") == string_view(kOfxImageEffectPropOpenCLSupported));
static_assert(string_view("OfxImageEffectPropOpenGLEnabled") == string_view(kOfxImageEffectPropOpenGLEnabled));
static_assert(string_view("OfxImageEffectPropOpenGLRenderSupported") == string_view(kOfxImageEffectPropOpenGLRenderSupported));
static_assert(string_view("OfxImageEffectPropOpenGLTextureIndex") == string_view(kOfxImageEffectPropOpenGLTextureIndex));
static_assert(string_view("OfxImageEffectPropOpenGLTextureTarget") == string_view(kOfxImageEffectPropOpenGLTextureTarget));
static_assert(string_view("OfxImageEffectPropPixelAspectRatio") == string_view(kOfxImageEffectPropProjectPixelAspectRatio));
static_assert(string_view("OfxImageEffectPropPixelDepth") == string_view(kOfxImageEffectPropPixelDepth));
static_assert(string_view("OfxImageEffectPropPluginHandle") == string_view(kOfxImageEffectPropPluginHandle));
static_assert(string_view("OfxImageEffectPropPreMultiplication") == string_view(kOfxImageEffectPropPreMultiplication));
static_assert(string_view("OfxImageEffectPropProjectExtent") == string_view(kOfxImageEffectPropProjectExtent));
static_assert(string_view("OfxImageEffectPropProjectOffset") == string_view(kOfxImageEffectPropProjectOffset));
static_assert(string_view("OfxImageEffectPropProjectSize") == string_view(kOfxImageEffectPropProjectSize));
static_assert(string_view("OfxImageEffectPropRegionOfDefinition") == string_view(kOfxImageEffectPropRegionOfDefinition));
static_assert(string_view("OfxImageEffectPropRegionOfInterest") == string_view(kOfxImageEffectPropRegionOfInterest));
static_assert(string_view("OfxImageEffectPropRenderQualityDraft") == string_view(kOfxImageEffectPropRenderQualityDraft));
static_assert(string_view("OfxImageEffectPropRenderScale") == string_view(kOfxImageEffectPropRenderScale));
static_assert(string_view("OfxImageEffectPropRenderWindow") == string_view(kOfxImageEffectPropRenderWindow));
static_assert(string_view("OfxImageEffectPropSequentialRenderStatus") == string_view(kOfxImageEffectPropSequentialRenderStatus));
static_assert(string_view("OfxImageEffectPropSetableFielding") == string_view(kOfxImageEffectPropSetableFielding));
static_assert(string_view("OfxImageEffectPropSetableFrameRate") == string_view(kOfxImageEffectPropSetableFrameRate));
static_assert(string_view("OfxImageEffectPropSupportedComponents") == string_view(kOfxImageEffectPropSupportedComponents));
static_assert(string_view("OfxImageEffectPropSupportedContexts") == string_view(kOfxImageEffectPropSupportedContexts));
static_assert(string_view("OfxImageEffectPropSupportedPixelDepths") == string_view(kOfxImageEffectPropSupportedPixelDepths));
static_assert(string_view("OfxImageEffectPropSupportsMultiResolution") == string_view(kOfxImageEffectPropSupportsMultiResolution));
static_assert(string_view("OfxImageEffectPropSupportsMultipleClipPARs") == string_view(kOfxImageEffectPropSupportsMultipleClipPARs));
static_assert(string_view("OfxImageEffectPropSupportsOverlays") == string_view(kOfxImageEffectPropSupportsOverlays));
static_assert(string_view("OfxImageEffectPropSupportsTiles") == string_view(kOfxImageEffectPropSupportsTiles));
static_assert(string_view("OfxImageEffectPropTemporalClipAccess") == string_view(kOfxImageEffectPropTemporalClipAccess));
static_assert(string_view("OfxImageEffectPropUnmappedFrameRange") == string_view(kOfxImageEffectPropUnmappedFrameRange));
static_assert(string_view("OfxImageEffectPropUnmappedFrameRate") == string_view(kOfxImageEffectPropUnmappedFrameRate));
static_assert(string_view("OfxImagePropBounds") == string_view(kOfxImagePropBounds));
static_assert(string_view("OfxImagePropData") == string_view(kOfxImagePropData));
static_assert(string_view("OfxImagePropField") == string_view(kOfxImagePropField));
static_assert(string_view("OfxImagePropPixelAspectRatio") == string_view(kOfxImagePropPixelAspectRatio));
static_assert(string_view("OfxImagePropRegionOfDefinition") == string_view(kOfxImagePropRegionOfDefinition));
static_assert(string_view("OfxImagePropRowBytes") == string_view(kOfxImagePropRowBytes));
static_assert(string_view("OfxImagePropUniqueIdentifier") == string_view(kOfxImagePropUniqueIdentifier));
static_assert(string_view("OfxInteractPropBackgroundColour") == string_view(kOfxInteractPropBackgroundColour));
static_assert(string_view("OfxInteractPropBitDepth") == string_view(kOfxInteractPropBitDepth));
static_assert(string_view("OfxInteractPropDrawContext") == string_view(kOfxInteractPropDrawContext));
static_assert(string_view("OfxInteractPropHasAlpha") == string_view(kOfxInteractPropHasAlpha));
static_assert(string_view("OfxInteractPropPenPosition") == string_view(kOfxInteractPropPenPosition));
static_assert(string_view("OfxInteractPropPenPressure") == string_view(kOfxInteractPropPenPressure));
static_assert(string_view("OfxInteractPropPenViewportPosition") == string_view(kOfxInteractPropPenViewportPosition));
static_assert(string_view("OfxInteractPropPixelScale") == string_view(kOfxInteractPropPixelScale));
static_assert(string_view("OfxInteractPropSlaveToParam") == string_view(kOfxInteractPropSlaveToParam));
static_assert(string_view("OfxInteractPropSuggestedColour") == string_view(kOfxInteractPropSuggestedColour));
static_assert(string_view("OfxInteractPropViewport") == string_view(kOfxInteractPropViewportSize));
static_assert(string_view("OfxOpenGLPropPixelDepth") == string_view(kOfxOpenGLPropPixelDepth));
static_assert(string_view("OfxParamHostPropMaxPages") == string_view(kOfxParamHostPropMaxPages));
static_assert(string_view("OfxParamHostPropMaxParameters") == string_view(kOfxParamHostPropMaxParameters));
static_assert(string_view("OfxParamHostPropPageRowColumnCount") == string_view(kOfxParamHostPropPageRowColumnCount));
static_assert(string_view("OfxParamHostPropSupportsBooleanAnimation") == string_view(kOfxParamHostPropSupportsBooleanAnimation));
static_assert(string_view("OfxParamHostPropSupportsChoiceAnimation") == string_view(kOfxParamHostPropSupportsChoiceAnimation));
static_assert(string_view("OfxParamHostPropSupportsCustomAnimation") == string_view(kOfxParamHostPropSupportsCustomAnimation));
static_assert(string_view("OfxParamHostPropSupportsCustomInteract") == string_view(kOfxParamHostPropSupportsCustomInteract));
static_assert(string_view("OfxParamHostPropSupportsParametricAnimation") == string_view(kOfxParamHostPropSupportsParametricAnimation));
static_assert(string_view("OfxParamHostPropSupportsStrChoice") == string_view(kOfxParamHostPropSupportsStrChoice));
static_assert(string_view("OfxParamHostPropSupportsStrChoiceAnimation") == string_view(kOfxParamHostPropSupportsStrChoiceAnimation));
static_assert(string_view("OfxParamHostPropSupportsStringAnimation") == string_view(kOfxParamHostPropSupportsStringAnimation));
static_assert(string_view("OfxParamPropAnimates") == string_view(kOfxParamPropAnimates));
static_assert(string_view("OfxParamPropCacheInvalidation") == string_view(kOfxParamPropCacheInvalidation));
static_assert(string_view("OfxParamPropCanUndo") == string_view(kOfxParamPropCanUndo));
static_assert(string_view("OfxParamPropChoiceEnum") == string_view(kOfxParamPropChoiceEnum));
static_assert(string_view("OfxParamPropChoiceOption") == string_view(kOfxParamPropChoiceOption));
static_assert(string_view("OfxParamPropChoiceOrder") == string_view(kOfxParamPropChoiceOrder));
static_assert(string_view("OfxParamPropCustomCallbackV1") == string_view(kOfxParamPropCustomInterpCallbackV1));
static_assert(string_view("OfxParamPropCustomValue") == string_view(kOfxParamPropCustomValue));
static_assert(string_view("OfxParamPropDataPtr") == string_view(kOfxParamPropDataPtr));
static_assert(string_view("OfxParamPropDefault") == string_view(kOfxParamPropDefault));
static_assert(string_view("OfxParamPropDefaultCoordinateSystem") == string_view(kOfxParamPropDefaultCoordinateSystem));
static_assert(string_view("OfxParamPropDigits") == string_view(kOfxParamPropDigits));
static_assert(string_view("OfxParamPropDimensionLabel") == string_view(kOfxParamPropDimensionLabel));
static_assert(string_view("OfxParamPropDisplayMax") == string_view(kOfxParamPropDisplayMax));
static_assert(string_view("OfxParamPropDisplayMin") == string_view(kOfxParamPropDisplayMin));
static_assert(string_view("OfxParamPropDoubleType") == string_view(kOfxParamPropDoubleType));
static_assert(string_view("OfxParamPropEnabled") == string_view(kOfxParamPropEnabled));
static_assert(string_view("OfxParamPropEvaluateOnChange") == string_view(kOfxParamPropEvaluateOnChange));
static_assert(string_view("OfxParamPropGroupOpen") == string_view(kOfxParamPropGroupOpen));
static_assert(string_view("OfxParamPropHasHostOverlayHandle") == string_view(kOfxParamPropHasHostOverlayHandle));
static_assert(string_view("OfxParamPropHint") == string_view(kOfxParamPropHint));
static_assert(string_view("OfxParamPropIncrement") == string_view(kOfxParamPropIncrement));
static_assert(string_view("OfxParamPropInteractMinimumSize") == string_view(kOfxParamPropInteractMinimumSize));
static_assert(string_view("OfxParamPropInteractPreferedSize") == string_view(kOfxParamPropInteractPreferedSize));
static_assert(string_view("OfxParamPropInteractSize") == string_view(kOfxParamPropInteractSize));
static_assert(string_view("OfxParamPropInteractSizeAspect") == string_view(kOfxParamPropInteractSizeAspect));
static_assert(string_view("OfxParamPropInteractV1") == string_view(kOfxParamPropInteractV1));
static_assert(string_view("OfxParamPropInterpolationAmount") == string_view(kOfxParamPropInterpolationAmount));
static_assert(string_view("OfxParamPropInterpolationTime") == string_view(kOfxParamPropInterpolationTime));
static_assert(string_view("OfxParamPropIsAnimating") == string_view(kOfxParamPropIsAnimating));
static_assert(string_view("OfxParamPropIsAutoKeying") == string_view(kOfxParamPropIsAutoKeying));
static_assert(string_view("OfxParamPropMax") == string_view(kOfxParamPropMax));
static_assert(string_view("OfxParamPropMin") == string_view(kOfxParamPropMin));
static_assert(string_view("OfxParamPropPageChild") == string_view(kOfxParamPropPageChild));
static_assert(string_view("OfxParamPropParametricDimension") == string_view(kOfxParamPropParametricDimension));
static_assert(string_view("OfxParamPropParametricInteractBackground") == string_view(kOfxParamPropParametricInteractBackground));
static_assert(string_view("OfxParamPropParametricRange") == string_view(kOfxParamPropParametricRange));
static_assert(string_view("OfxParamPropParametricUIColour") == string_view(kOfxParamPropParametricUIColour));
static_assert(string_view("OfxParamPropParent") == string_view(kOfxParamPropParent));
static_assert(string_view("OfxParamPropPersistant") == string_view(kOfxParamPropPersistant));
static_assert(string_view("OfxParamPropPluginMayWrite") == string_view(kOfxParamPropPluginMayWrite));
static_assert(string_view("OfxParamPropScriptName") == string_view(kOfxParamPropScriptName));
static_assert(string_view("OfxParamPropSecret") == string_view(kOfxParamPropSecret));
static_assert(string_view("OfxParamPropShowTimeMarker") == string_view(kOfxParamPropShowTimeMarker));
static_assert(string_view("OfxParamPropStringFilePathExists") == string_view(kOfxParamPropStringFilePathExists));
static_assert(string_view("OfxParamPropStringMode") == string_view(kOfxParamPropStringMode));
static_assert(string_view("OfxParamPropType") == string_view(kOfxParamPropType));
static_assert(string_view("OfxPluginPropFilePath") == string_view(kOfxPluginPropFilePath));
static_assert(string_view("OfxPluginPropParamPageOrder") == string_view(kOfxPluginPropParamPageOrder));
static_assert(string_view("OfxPropAPIVersion") == string_view(kOfxPropAPIVersion));
static_assert(string_view("OfxPropChangeReason") == string_view(kOfxPropChangeReason));
static_assert(string_view("OfxPropEffectInstance") == string_view(kOfxPropEffectInstance));
static_assert(string_view("OfxPropHostOSHandle") == string_view(kOfxPropHostOSHandle));
static_assert(string_view("OfxPropIcon") == string_view(kOfxPropIcon));
static_assert(string_view("OfxPropInstanceData") == string_view(kOfxPropInstanceData));
static_assert(string_view("OfxPropIsInteractive") == string_view(kOfxPropIsInteractive));
static_assert(string_view("OfxPropLabel") == string_view(kOfxPropLabel));
static_assert(string_view("OfxPropLongLabel") == string_view(kOfxPropLongLabel));
static_assert(string_view("OfxPropName") == string_view(kOfxPropName));
static_assert(string_view("OfxPropParamSetNeedsSyncing") == string_view(kOfxPropParamSetNeedsSyncing));
static_assert(string_view("OfxPropPluginDescription") == string_view(kOfxPropPluginDescription));
static_assert(string_view("OfxPropShortLabel") == string_view(kOfxPropShortLabel));
static_assert(string_view("OfxPropTime") == string_view(kOfxPropTime));
static_assert(string_view("OfxPropType") == string_view(kOfxPropType));
static_assert(string_view("OfxPropVersion") == string_view(kOfxPropVersion));
static_assert(string_view("OfxPropVersionLabel") == string_view(kOfxPropVersionLabel));
static_assert(string_view("kOfxParamPropUseHostOverlayHandle") == string_view(kOfxParamPropUseHostOverlayHandle));
static_assert(string_view("kOfxPropKeyString") == string_view(kOfxPropKeyString));
static_assert(string_view("kOfxPropKeySym") == string_view(kOfxPropKeySym));
} // namespace assertions
} // namespace openfx
