// Copyright OpenFX and contributors to the OpenFX project.
// SPDX-License-Identifier: BSD-3-Clause
// NOTE: This file is auto-generated by gen-props.py. DO NOT EDIT.

#pragma once

#include <array>
#include <string_view>
#include <openfx/ofxPropsMetadata.h>
#include <openfx/ofxSpan.h>

// ============== Host-specific property definitions for myhost ==============

namespace myhost {

// Property ID enum for compile-time lookup and type safety
enum class PropId {
  MyHostViewerProcess = 0,  // MyHost viewer process name (color management display transform)
  MyHostColorConfig = 1,  // Path to MyHost's color management config file
  MyHostProjectPath = 2,  // Path to the current MyHost project file
  MyHostNodeName = 3,  // Name of the MyHost node containing this effect
  MyHostNodeColor = 4,  // RGB color of the node in MyHost's node graph (0-255)
};

namespace properties {

static constexpr openfx::PropType MyHostViewerProcess_types[] = {openfx::PropType::String};
static constexpr openfx::PropType MyHostColorConfig_types[] = {openfx::PropType::String};
static constexpr openfx::PropType MyHostProjectPath_types[] = {openfx::PropType::String};
static constexpr openfx::PropType MyHostNodeName_types[] = {openfx::PropType::String};
static constexpr openfx::PropType MyHostNodeColor_types[] = {openfx::PropType::Int};

constexpr openfx::PropDef prop_defs[] = {
  // MyHostViewerProcess - "MyHost viewer process name (color management display transform)"
  { "com.example.myhost.ViewerProcess",
    openfx::span(MyHostViewerProcess_types, 1), 1, openfx::span<const char* const>() },
  // MyHostColorConfig - "Path to MyHost's color management config file"
  { "com.example.myhost.ColorConfig",
    openfx::span(MyHostColorConfig_types, 1), 1, openfx::span<const char* const>() },
  // MyHostProjectPath - "Path to the current MyHost project file"
  { "com.example.myhost.ProjectPath",
    openfx::span(MyHostProjectPath_types, 1), 1, openfx::span<const char* const>() },
  // MyHostNodeName - "Name of the MyHost node containing this effect"
  { "com.example.myhost.NodeName",
    openfx::span(MyHostNodeName_types, 1), 1, openfx::span<const char* const>() },
  // MyHostNodeColor - "RGB color of the node in MyHost's node graph (0-255)"
  { "com.example.myhost.NodeColor",
    openfx::span(MyHostNodeColor_types, 1), 3, openfx::span<const char* const>() },
};

// Base template (leave undefined - specializations required)
template<PropId id>
struct PropTraits;

template<>
struct PropTraits<PropId::MyHostViewerProcess> {
  using type = const char*;
  static constexpr bool is_multitype = false;
  static constexpr int dimension = 1;
  static constexpr const openfx::PropDef& def = prop_defs[static_cast<size_t>(PropId::MyHostViewerProcess)];
};

template<>
struct PropTraits<PropId::MyHostColorConfig> {
  using type = const char*;
  static constexpr bool is_multitype = false;
  static constexpr int dimension = 1;
  static constexpr const openfx::PropDef& def = prop_defs[static_cast<size_t>(PropId::MyHostColorConfig)];
};

template<>
struct PropTraits<PropId::MyHostProjectPath> {
  using type = const char*;
  static constexpr bool is_multitype = false;
  static constexpr int dimension = 1;
  static constexpr const openfx::PropDef& def = prop_defs[static_cast<size_t>(PropId::MyHostProjectPath)];
};

template<>
struct PropTraits<PropId::MyHostNodeName> {
  using type = const char*;
  static constexpr bool is_multitype = false;
  static constexpr int dimension = 1;
  static constexpr const openfx::PropDef& def = prop_defs[static_cast<size_t>(PropId::MyHostNodeName)];
};

template<>
struct PropTraits<PropId::MyHostNodeColor> {
  using type = int;
  static constexpr bool is_multitype = false;
  static constexpr int dimension = 3;
  static constexpr const openfx::PropDef& def = prop_defs[static_cast<size_t>(PropId::MyHostNodeColor)];
};

}  // namespace properties

// ADL helper for openfx::PropertyAccessor lookup
template<PropId id>
properties::PropTraits<id> prop_traits_helper(std::integral_constant<PropId, id>);

}  // namespace myhost
