#! /bin/sh 

die()
{
  echo '*** ERROR ***' $*
  exit 1
}

if [ $# -lt 1 ] ; then
  echo 'USAGE : genRelease LABEL'
  echo '   LABEL is the label for the release'
  exit 1
fi


LABEL=$1; shift

set -v

if [ `git ls-files --modified | wc -l` -ne 0 ]; then
  die "You have modified files; commit to git first before building release!"
fi

git clean -f	   # start clean; remove everything not managed by git

cd include
rm -r doc

# Build the doxygen docs)
doxygen ofx.doxy  || die "building doxygen docs"

rm -rf ../doc/html
mv doc/html ../doc || die "Moving doxygen docs"

cd ..

# Build the ProgrammingGuide and ProgrammingReference
cd Documentation
make || die "building Programming Guide and Reference"

# Copy style assets to Ref and Guide directories
cp ../include/ofxStyle.css Reference/
cp ../include/ofxStyle.css Guide/
cd ..

(tar cf - doc | gzip > openfx-doc-$LABEL.tar.gz)  || die "Tarring docs"
(tar cf - Examples | gzip > openfx-examples-$LABEL.tar.gz) || die "Tarring examples"
(tar cf - include | gzip > openfx-include-$LABEL.tar.gz) || die "Tarring include"

echo YOU NOW NEED TO COPY THIS TO frs.sourceforge.net and ADD THE RELEASE VIA THE SF WEB INTERFACE
