#! /bin/sh 

die()
{
  echo '*** ERROR ***' $*
  exit 1
}

if [ $# -lt 1 ] ; then
  echo 'USAGE : genRelease LABEL'
  echo '   LABEL is the label for the release'
  exit 1
fi


LABEL=$1; shift

set -v
cd include

doxygen ofx.doxy  || die "building docs"

rm -rf ../doc/html
mv doc/html ../doc || die "Moving docs"

cd ..

(tar cf - doc | gzip > openfx-doc-$LABEL.tar.gz)  || die "Tarring docs"
(tar cf - Examples | gzip > openfx-examples-$LABEL.tar.gz) || die "Tarring examples"
(tar cf - include | gzip > openfx-include-$LABEL.tar.gz) || die "Tarring include"

echo YOU NOW NEED TO COPY THIS TO frs.sourceforge.net and ADD THE RELEASE VIA THE SF WEB INTERFACE
