#ifndef _ofx_native_v1_5_aces_v1_3_ocio_v2_3_h_
#define _ofx_native_v1_5_aces_v1_3_ocio_v2_3_h_

// Copyright OpenFX and contributors to the OpenFX project.
// SPDX-License-Identifier: BSD-3-Clause

#ifdef __cplusplus
extern "C" {
#endif

/** @file ofx-native-v1.5_aces-v1.3_ocio-v2.3.h
Contains the list of supported colourspaces.
This file was auto-generated by scripts/genColour from ofx-native-v1.5_aces-v1.3_ocio-v2.3.
*/

// For use with kOfxImageEffectPropColourManagementAvailableConfigs
#define kOfxConfigIdentifier "ofx-native-v1.5_aces-v1.3_ocio-v2.3"

// Basic Colourspaces
// These colourspaces are generic names for any colourspace with the correct attributes.

/** @brief ofx_display_hdr
Any display-referred HDR video such as Rec. 2100 HLG or PQ.
*/
#define kOfxColourspaceOfxDisplayHdr "ofx_display_hdr"
#define kOfxColourspaceOfxDisplayHdrLabel "OFX generic display HDR"
#define kOfxColourspaceOfxDisplayHdrEncoding "hdr-video"
#define kOfxColourspaceOfxDisplayHdrIsData false
#define kOfxColourspaceOfxDisplayHdrIsBasic true
#define kOfxColourspaceOfxDisplayHdrIsCore true
#define kOfxColourspaceOfxDisplayHdrIsDisplay true

/** @brief ofx_display_sdr
Any display-referred SDR video such as Rec. 709.
*/
#define kOfxColourspaceOfxDisplaySdr "ofx_display_sdr"
#define kOfxColourspaceOfxDisplaySdrLabel "OFX generic display SDR"
#define kOfxColourspaceOfxDisplaySdrEncoding "sdr-video"
#define kOfxColourspaceOfxDisplaySdrIsData false
#define kOfxColourspaceOfxDisplaySdrIsBasic true
#define kOfxColourspaceOfxDisplaySdrIsCore true
#define kOfxColourspaceOfxDisplaySdrIsDisplay true

/** @brief ofx_raw
Image values should not be treated as colour, e.g. motion vectors or masks.
*/
#define kOfxColourspaceOfxRaw "ofx_raw"
#define kOfxColourspaceOfxRawLabel "OFX generic raw"
#define kOfxColourspaceOfxRawEncoding ""
#define kOfxColourspaceOfxRawIsData true
#define kOfxColourspaceOfxRawIsBasic true
#define kOfxColourspaceOfxRawIsCore true
#define kOfxColourspaceOfxRawIsDisplay false

/** @brief ofx_scene_linear
Any scene-referred linear colourspace.
*/
#define kOfxColourspaceOfxSceneLinear "ofx_scene_linear"
#define kOfxColourspaceOfxSceneLinearLabel "OFX generic scene linear"
#define kOfxColourspaceOfxSceneLinearEncoding "scene-linear"
#define kOfxColourspaceOfxSceneLinearIsData false
#define kOfxColourspaceOfxSceneLinearIsBasic true
#define kOfxColourspaceOfxSceneLinearIsCore true
#define kOfxColourspaceOfxSceneLinearIsDisplay false

/** @brief ofx_scene_log
Any scene-referred colourspace with a log transfer function.
*/
#define kOfxColourspaceOfxSceneLog "ofx_scene_log"
#define kOfxColourspaceOfxSceneLogLabel "OFX generic scene log"
#define kOfxColourspaceOfxSceneLogEncoding "log"
#define kOfxColourspaceOfxSceneLogIsData false
#define kOfxColourspaceOfxSceneLogIsBasic true
#define kOfxColourspaceOfxSceneLogIsCore true
#define kOfxColourspaceOfxSceneLogIsDisplay false

// Core Colourspaces

// srgb_display
// Convert CIE XYZ (D65 white) to sRGB (piecewise EOTF)
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ODT.Academy.RGBmonitor_100nits_dim.a1.0.3
// ACEStransformID: urn:ampas:aces:transformId:v1.5:InvODT.Academy.RGBmonitor_100nits_dim.a1.0.3
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ODT.Academy.RGBmonitor_D60sim_100nits_dim.a1.0.3
// ACEStransformID: urn:ampas:aces:transformId:v1.5:InvODT.Academy.RGBmonitor_D60sim_100nits_dim.a1.0.3
#define kOfxColourspaceSrgbDisplay "srgb_display"
#define kOfxColourspaceSrgbDisplayLabel "sRGB - Display"
#define kOfxColourspaceSrgbDisplayEncoding "sdr-video"
#define kOfxColourspaceSrgbDisplayIsData false
#define kOfxColourspaceSrgbDisplayIsBasic false
#define kOfxColourspaceSrgbDisplayIsCore true
#define kOfxColourspaceSrgbDisplayIsDisplay true

// displayp3_display
// Convert CIE XYZ (D65 white) to Apple Display P3
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ODT.Academy.DisplayP3_dim.a1.0.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:InvODT.Academy.DisplayP3_dim.a1.0.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ODT.Academy.DisplayP3_D60sim_dim.a1.0.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:InvODT.Academy.DisplayP3_D60sim_dim.a1.0.0
#define kOfxColourspaceDisplayp3Display "displayp3_display"
#define kOfxColourspaceDisplayp3DisplayLabel "Display P3 - Display"
#define kOfxColourspaceDisplayp3DisplayEncoding "sdr-video"
#define kOfxColourspaceDisplayp3DisplayIsData false
#define kOfxColourspaceDisplayp3DisplayIsBasic false
#define kOfxColourspaceDisplayp3DisplayIsCore true
#define kOfxColourspaceDisplayp3DisplayIsDisplay true

// rec1886_rec709_display
// Convert CIE XYZ (D65 white) to Rec.1886/Rec.709 (HD video)
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ODT.Academy.Rec709_100nits_dim.a1.0.3
// ACEStransformID: urn:ampas:aces:transformId:v1.5:InvODT.Academy.Rec709_100nits_dim.a1.0.3
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ODT.Academy.Rec709_D60sim_100nits_dim.a1.0.3
// ACEStransformID: urn:ampas:aces:transformId:v1.5:InvODT.Academy.Rec709_D60sim_100nits_dim.a1.0.3
#define kOfxColourspaceRec1886Rec709Display "rec1886_rec709_display"
#define kOfxColourspaceRec1886Rec709DisplayLabel "Rec.1886 Rec.709 - Display"
#define kOfxColourspaceRec1886Rec709DisplayEncoding "sdr-video"
#define kOfxColourspaceRec1886Rec709DisplayIsData false
#define kOfxColourspaceRec1886Rec709DisplayIsBasic false
#define kOfxColourspaceRec1886Rec709DisplayIsCore true
#define kOfxColourspaceRec1886Rec709DisplayIsDisplay true

// rec1886_rec2020_display
// Convert CIE XYZ (D65 white) to Rec.1886/Rec.2020 (UHD video)
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ODT.Academy.Rec2020_100nits_dim.a1.0.3
// ACEStransformID: urn:ampas:aces:transformId:v1.5:InvODT.Academy.Rec2020_100nits_dim.a1.0.3
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ODT.Academy.Rec2020_P3D65limited_100nits_dim.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ODT.Academy.Rec2020_Rec709limited_100nits_dim.a1.1.0
#define kOfxColourspaceRec1886Rec2020Display "rec1886_rec2020_display"
#define kOfxColourspaceRec1886Rec2020DisplayLabel "Rec.1886 Rec.2020 - Display"
#define kOfxColourspaceRec1886Rec2020DisplayEncoding "sdr-video"
#define kOfxColourspaceRec1886Rec2020DisplayIsData false
#define kOfxColourspaceRec1886Rec2020DisplayIsBasic false
#define kOfxColourspaceRec1886Rec2020DisplayIsCore true
#define kOfxColourspaceRec1886Rec2020DisplayIsDisplay true

// rec2100_hlg_display
// Convert CIE XYZ (D65 white) to Rec.2100-HLG, 1000 nit
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:RRTODT.Academy.Rec2020_1000nits_15nits_HLG.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:InvRRTODT.Academy.Rec2020_1000nits_15nits_HLG.a1.1.0
#define kOfxColourspaceRec2100HlgDisplay "rec2100_hlg_display"
#define kOfxColourspaceRec2100HlgDisplayLabel "Rec.2100-HLG - Display"
#define kOfxColourspaceRec2100HlgDisplayEncoding "hdr-video"
#define kOfxColourspaceRec2100HlgDisplayIsData false
#define kOfxColourspaceRec2100HlgDisplayIsBasic false
#define kOfxColourspaceRec2100HlgDisplayIsCore true
#define kOfxColourspaceRec2100HlgDisplayIsDisplay true

// rec2100_pq_display
// Convert CIE XYZ (D65 white) to Rec.2100-PQ
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:RRTODT.Academy.Rec2020_1000nits_15nits_ST2084.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:InvRRTODT.Academy.Rec2020_1000nits_15nits_ST2084.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:RRTODT.Academy.Rec2020_2000nits_15nits_ST2084.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:InvRRTODT.Academy.Rec2020_2000nits_15nits_ST2084.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:RRTODT.Academy.Rec2020_4000nits_15nits_ST2084.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:InvRRTODT.Academy.Rec2020_4000nits_15nits_ST2084.a1.1.0
#define kOfxColourspaceRec2100PqDisplay "rec2100_pq_display"
#define kOfxColourspaceRec2100PqDisplayLabel "Rec.2100-PQ - Display"
#define kOfxColourspaceRec2100PqDisplayEncoding "hdr-video"
#define kOfxColourspaceRec2100PqDisplayIsData false
#define kOfxColourspaceRec2100PqDisplayIsBasic false
#define kOfxColourspaceRec2100PqDisplayIsCore true
#define kOfxColourspaceRec2100PqDisplayIsDisplay true

// st2084_p3d65_display
// Convert CIE XYZ (D65 white) to ST-2084 (PQ), P3-D65 primaries
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:RRTODT.Academy.P3D65_1000nits_15nits_ST2084.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:InvRRTODT.Academy.P3D65_1000nits_15nits_ST2084.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:RRTODT.Academy.P3D65_2000nits_15nits_ST2084.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:InvRRTODT.Academy.P3D65_2000nits_15nits_ST2084.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:RRTODT.Academy.P3D65_4000nits_15nits_ST2084.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:InvRRTODT.Academy.P3D65_4000nits_15nits_ST2084.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:RRTODT.Academy.P3D65_108nits_7point2nits_ST2084.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:InvRRTODT.Academy.P3D65_108nits_7point2nits_ST2084.a1.1.0
#define kOfxColourspaceSt2084P3d65Display "st2084_p3d65_display"
#define kOfxColourspaceSt2084P3d65DisplayLabel "ST2084-P3-D65 - Display"
#define kOfxColourspaceSt2084P3d65DisplayEncoding "hdr-video"
#define kOfxColourspaceSt2084P3d65DisplayIsData false
#define kOfxColourspaceSt2084P3d65DisplayIsBasic false
#define kOfxColourspaceSt2084P3d65DisplayIsCore true
#define kOfxColourspaceSt2084P3d65DisplayIsDisplay true

// p3d65_display
// Convert CIE XYZ (D65 white) to Gamma 2.6, P3-D65
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ODT.Academy.P3D65_48nits.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:InvODT.Academy.P3D65_48nits.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ODT.Academy.P3D65_Rec709limited_48nits.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ODT.Academy.P3D65_D60sim_48nits.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:InvODT.Academy.P3D65_D60sim_48nits.a1.1.0
#define kOfxColourspaceP3d65Display "p3d65_display"
#define kOfxColourspaceP3d65DisplayLabel "P3-D65 - Display"
#define kOfxColourspaceP3d65DisplayEncoding "sdr-video"
#define kOfxColourspaceP3d65DisplayIsData false
#define kOfxColourspaceP3d65DisplayIsBasic false
#define kOfxColourspaceP3d65DisplayIsCore true
#define kOfxColourspaceP3d65DisplayIsDisplay true

// ACES2065-1
// The "Academy Color Encoding System" reference colorspace.
#define kOfxColourspaceACES20651 "ACES2065-1"
#define kOfxColourspaceACES20651Label "ACES2065-1"
#define kOfxColourspaceACES20651Encoding "scene-linear"
#define kOfxColourspaceACES20651IsData false
#define kOfxColourspaceACES20651IsBasic false
#define kOfxColourspaceACES20651IsCore true
#define kOfxColourspaceACES20651IsDisplay false

// ACEScc
// Convert ACEScc to ACES2065-1
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.ACEScc_to_ACES.a1.0.3
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.ACES_to_ACEScc.a1.0.3
#define kOfxColourspaceACEScc "ACEScc"
#define kOfxColourspaceACESccLabel "ACEScc"
#define kOfxColourspaceACESccEncoding "log"
#define kOfxColourspaceACESccIsData false
#define kOfxColourspaceACESccIsBasic false
#define kOfxColourspaceACESccIsCore true
#define kOfxColourspaceACESccIsDisplay false

// ACEScct
// Convert ACEScct to ACES2065-1
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.ACEScct_to_ACES.a1.0.3
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.ACES_to_ACEScct.a1.0.3
#define kOfxColourspaceACEScct "ACEScct"
#define kOfxColourspaceACEScctLabel "ACEScct"
#define kOfxColourspaceACEScctEncoding "log"
#define kOfxColourspaceACEScctIsData false
#define kOfxColourspaceACEScctIsBasic false
#define kOfxColourspaceACEScctIsCore true
#define kOfxColourspaceACEScctIsDisplay false

// ACEScg
// Convert ACEScg to ACES2065-1
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.ACEScg_to_ACES.a1.0.3
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.ACES_to_ACEScg.a1.0.3
#define kOfxColourspaceACEScg "ACEScg"
#define kOfxColourspaceACEScgLabel "ACEScg"
#define kOfxColourspaceACEScgEncoding "scene-linear"
#define kOfxColourspaceACEScgIsData false
#define kOfxColourspaceACEScgIsBasic false
#define kOfxColourspaceACEScgIsCore true
#define kOfxColourspaceACEScgIsDisplay false

// lin_p3d65
// Convert ACES2065-1 to linear P3 primaries, D65 white point
// CLFtransformID: urn:aswf:ocio:transformId:1.0:OCIO:Utility:AP0_to_Linear_P3-D65:1.0
#define kOfxColourspaceLinP3d65 "lin_p3d65"
#define kOfxColourspaceLinP3d65Label "Linear P3-D65"
#define kOfxColourspaceLinP3d65Encoding "scene-linear"
#define kOfxColourspaceLinP3d65IsData false
#define kOfxColourspaceLinP3d65IsBasic false
#define kOfxColourspaceLinP3d65IsCore true
#define kOfxColourspaceLinP3d65IsDisplay false

// lin_rec2020
// Convert ACES2065-1 to linear Rec.2020 primaries, D65 white point
// CLFtransformID: urn:aswf:ocio:transformId:1.0:OCIO:Utility:AP0_to_Linear_Rec2020:1.0
#define kOfxColourspaceLinRec2020 "lin_rec2020"
#define kOfxColourspaceLinRec2020Label "Linear Rec.2020"
#define kOfxColourspaceLinRec2020Encoding "scene-linear"
#define kOfxColourspaceLinRec2020IsData false
#define kOfxColourspaceLinRec2020IsBasic false
#define kOfxColourspaceLinRec2020IsCore true
#define kOfxColourspaceLinRec2020IsDisplay false

// lin_rec709_srgb
// Convert ACES2065-1 to linear Rec.709 primaries, D65 white point
// CLFtransformID: urn:aswf:ocio:transformId:1.0:OCIO:Utility:AP0_to_Linear_Rec709:1.0
#define kOfxColourspaceLinRec709Srgb "lin_rec709_srgb"
#define kOfxColourspaceLinRec709SrgbLabel "Linear Rec.709 (sRGB)"
#define kOfxColourspaceLinRec709SrgbEncoding "scene-linear"
#define kOfxColourspaceLinRec709SrgbIsData false
#define kOfxColourspaceLinRec709SrgbIsBasic false
#define kOfxColourspaceLinRec709SrgbIsCore true
#define kOfxColourspaceLinRec709SrgbIsDisplay false

// g18_rec709_tx
// Convert ACES2065-1 to 1.8 gamma-corrected Rec.709 primaries, D65 white point
// CLFtransformID: urn:aswf:ocio:transformId:1.0:OCIO:Utility:AP0_to_Gamma1.8_Rec709-Texture:1.0
#define kOfxColourspaceG18Rec709Tx "g18_rec709_tx"
#define kOfxColourspaceG18Rec709TxLabel "Gamma 1.8 Rec.709 - Texture"
#define kOfxColourspaceG18Rec709TxEncoding "sdr-video"
#define kOfxColourspaceG18Rec709TxIsData false
#define kOfxColourspaceG18Rec709TxIsBasic false
#define kOfxColourspaceG18Rec709TxIsCore true
#define kOfxColourspaceG18Rec709TxIsDisplay false

// g22_ap1_tx
// Convert ACES2065-1 to 2.2 gamma-corrected AP1 primaries, ACES ~=D60 white point
// CLFtransformID: urn:aswf:ocio:transformId:1.0:OCIO:Utility:AP0_to_Gamma2.2_AP1-Texture:1.0
#define kOfxColourspaceG22Ap1Tx "g22_ap1_tx"
#define kOfxColourspaceG22Ap1TxLabel "Gamma 2.2 AP1 - Texture"
#define kOfxColourspaceG22Ap1TxEncoding "sdr-video"
#define kOfxColourspaceG22Ap1TxIsData false
#define kOfxColourspaceG22Ap1TxIsBasic false
#define kOfxColourspaceG22Ap1TxIsCore true
#define kOfxColourspaceG22Ap1TxIsDisplay false

// g22_rec709_tx
// Convert ACES2065-1 to 2.2 gamma-corrected Rec.709 primaries, D65 white point
// CLFtransformID: urn:aswf:ocio:transformId:1.0:OCIO:Utility:AP0_to_Gamma2.2_Rec709-Texture:1.0
#define kOfxColourspaceG22Rec709Tx "g22_rec709_tx"
#define kOfxColourspaceG22Rec709TxLabel "Gamma 2.2 Rec.709 - Texture"
#define kOfxColourspaceG22Rec709TxEncoding "sdr-video"
#define kOfxColourspaceG22Rec709TxIsData false
#define kOfxColourspaceG22Rec709TxIsBasic false
#define kOfxColourspaceG22Rec709TxIsCore true
#define kOfxColourspaceG22Rec709TxIsDisplay false

// g24_rec709_tx
// Convert ACES2065-1 to 2.4 gamma-corrected Rec.709 primaries, D65 white point
// CLFtransformID: urn:aswf:ocio:transformId:1.0:OCIO:Utility:AP0_to_Gamma2.4_Rec709-Texture:1.0
#define kOfxColourspaceG24Rec709Tx "g24_rec709_tx"
#define kOfxColourspaceG24Rec709TxLabel "Gamma 2.4 Rec.709 - Texture"
#define kOfxColourspaceG24Rec709TxEncoding "sdr-video"
#define kOfxColourspaceG24Rec709TxIsData false
#define kOfxColourspaceG24Rec709TxIsBasic false
#define kOfxColourspaceG24Rec709TxIsCore true
#define kOfxColourspaceG24Rec709TxIsDisplay false

// srgb_encoded_ap1_tx
// Convert ACES2065-1 to sRGB Encoded AP1 primaries, ACES ~=D60 white point
// CLFtransformID: urn:aswf:ocio:transformId:1.0:OCIO:Utility:AP0_to_sRGB_Encoded_AP1-Texture:1.0
#define kOfxColourspaceSrgbEncodedAp1Tx "srgb_encoded_ap1_tx"
#define kOfxColourspaceSrgbEncodedAp1TxLabel "sRGB Encoded AP1 - Texture"
#define kOfxColourspaceSrgbEncodedAp1TxEncoding "sdr-video"
#define kOfxColourspaceSrgbEncodedAp1TxIsData false
#define kOfxColourspaceSrgbEncodedAp1TxIsBasic false
#define kOfxColourspaceSrgbEncodedAp1TxIsCore true
#define kOfxColourspaceSrgbEncodedAp1TxIsDisplay false

// srgb_encoded_p3d65_tx
// Convert ACES2065-1 to sRGB Encoded P3-D65 primaries, D65 white point
// CLFtransformID: urn:aswf:ocio:transformId:1.0:OCIO:Utility:AP0_to_sRGB_Encoded_P3-D65-Texture:1.0
#define kOfxColourspaceSrgbEncodedP3d65Tx "srgb_encoded_p3d65_tx"
#define kOfxColourspaceSrgbEncodedP3d65TxLabel "sRGB Encoded P3-D65 - Texture"
#define kOfxColourspaceSrgbEncodedP3d65TxEncoding "sdr-video"
#define kOfxColourspaceSrgbEncodedP3d65TxIsData false
#define kOfxColourspaceSrgbEncodedP3d65TxIsBasic false
#define kOfxColourspaceSrgbEncodedP3d65TxIsCore true
#define kOfxColourspaceSrgbEncodedP3d65TxIsDisplay false

// srgb_tx
// Convert ACES2065-1 to sRGB
// CLFtransformID: urn:aswf:ocio:transformId:1.0:OCIO:Utility:AP0_to_sRGB-Texture:1.0
#define kOfxColourspaceSrgbTx "srgb_tx"
#define kOfxColourspaceSrgbTxLabel "sRGB - Texture"
#define kOfxColourspaceSrgbTxEncoding "sdr-video"
#define kOfxColourspaceSrgbTxIsData false
#define kOfxColourspaceSrgbTxIsBasic false
#define kOfxColourspaceSrgbTxIsCore true
#define kOfxColourspaceSrgbTxIsDisplay false

// Raw
// The utility "Raw" colorspace.
#define kOfxColourspaceRaw "Raw"
#define kOfxColourspaceRawLabel "Raw"
#define kOfxColourspaceRawEncoding ""
#define kOfxColourspaceRawIsData true
#define kOfxColourspaceRawIsBasic false
#define kOfxColourspaceRawIsCore true
#define kOfxColourspaceRawIsDisplay false

// Non-core Colourspaces

// CIE-XYZ-D65
// The "CIE XYZ (D65)" display connection colorspace.
#define kOfxColourspaceCIEXYZD65 "CIE-XYZ-D65"
#define kOfxColourspaceCIEXYZD65Label "CIE-XYZ-D65"
#define kOfxColourspaceCIEXYZD65Encoding ""
#define kOfxColourspaceCIEXYZD65IsData false
#define kOfxColourspaceCIEXYZD65IsBasic false
#define kOfxColourspaceCIEXYZD65IsCore false
#define kOfxColourspaceCIEXYZD65IsDisplay true

// p3d60_display
// Convert CIE XYZ (D65 white) to Gamma 2.6, P3-D60 (Bradford adaptation)
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ODT.Academy.P3D60_48nits.a1.0.3
// ACEStransformID: urn:ampas:aces:transformId:v1.5:InvODT.Academy.P3D60_48nits.a1.0.3
#define kOfxColourspaceP3d60Display "p3d60_display"
#define kOfxColourspaceP3d60DisplayLabel "P3-D60 - Display"
#define kOfxColourspaceP3d60DisplayEncoding "sdr-video"
#define kOfxColourspaceP3d60DisplayIsData false
#define kOfxColourspaceP3d60DisplayIsBasic false
#define kOfxColourspaceP3d60DisplayIsCore false
#define kOfxColourspaceP3d60DisplayIsDisplay true

// p3_dci_display
// Convert CIE XYZ (D65 white) to Gamma 2.6, P3-DCI (DCI white with Bradford adaptation)
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ODT.Academy.P3DCI_48nits.a1.0.3
// ACEStransformID: urn:ampas:aces:transformId:v1.5:InvODT.Academy.P3DCI_48nits.a1.0.3
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ODT.Academy.P3DCI_D65sim_48nits.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:InvODT.Academy.P3DCI_D65sim_48nits.a1.1.0
#define kOfxColourspaceP3DciDisplay "p3_dci_display"
#define kOfxColourspaceP3DciDisplayLabel "P3-DCI - Display"
#define kOfxColourspaceP3DciDisplayEncoding "sdr-video"
#define kOfxColourspaceP3DciDisplayIsData false
#define kOfxColourspaceP3DciDisplayIsBasic false
#define kOfxColourspaceP3DciDisplayIsCore false
#define kOfxColourspaceP3DciDisplayIsDisplay true

// ADX10
// Convert ADX10 to ACES2065-1
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.ADX10_to_ACES.a1.0.3
#define kOfxColourspaceADX10 "ADX10"
#define kOfxColourspaceADX10Label "ADX10"
#define kOfxColourspaceADX10Encoding "log"
#define kOfxColourspaceADX10IsData false
#define kOfxColourspaceADX10IsBasic false
#define kOfxColourspaceADX10IsCore false
#define kOfxColourspaceADX10IsDisplay false

// ADX16
// Convert ADX16 to ACES2065-1
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.ADX16_to_ACES.a1.0.3
#define kOfxColourspaceADX16 "ADX16"
#define kOfxColourspaceADX16Label "ADX16"
#define kOfxColourspaceADX16Encoding "log"
#define kOfxColourspaceADX16IsData false
#define kOfxColourspaceADX16IsBasic false
#define kOfxColourspaceADX16IsCore false
#define kOfxColourspaceADX16IsDisplay false

// lin_arri_wide_gamut_3
// Convert Linear ARRI Wide Gamut 3 to ACES2065-1
// CLFtransformID: urn:aswf:ocio:transformId:1.0:ARRI:Input:Linear_ARRI_Wide_Gamut_3_to_ACES2065-1:1.0
#define kOfxColourspaceLinArriWideGamut3 "lin_arri_wide_gamut_3"
#define kOfxColourspaceLinArriWideGamut3Label "Linear ARRI Wide Gamut 3"
#define kOfxColourspaceLinArriWideGamut3Encoding "scene-linear"
#define kOfxColourspaceLinArriWideGamut3IsData false
#define kOfxColourspaceLinArriWideGamut3IsBasic false
#define kOfxColourspaceLinArriWideGamut3IsCore false
#define kOfxColourspaceLinArriWideGamut3IsDisplay false

// arri_logc3_ei800
// Convert ARRI LogC3 (EI800) to ACES2065-1
// CLFtransformID: urn:aswf:ocio:transformId:1.0:ARRI:Input:ARRI_LogC3_EI800_to_ACES2065-1:1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:IDT.ARRI.Alexa-v3-logC-EI800.a1.v2
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.ACES_to_LogC_EI800_AWG.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.LogC_EI800_AWG_to_ACES.a1.1.0
#define kOfxColourspaceArriLogc3Ei800 "arri_logc3_ei800"
#define kOfxColourspaceArriLogc3Ei800Label "ARRI LogC3 (EI800)"
#define kOfxColourspaceArriLogc3Ei800Encoding "log"
#define kOfxColourspaceArriLogc3Ei800IsData false
#define kOfxColourspaceArriLogc3Ei800IsBasic false
#define kOfxColourspaceArriLogc3Ei800IsCore false
#define kOfxColourspaceArriLogc3Ei800IsDisplay false

// lin_arri_wide_gamut_4
// Convert Linear ARRI Wide Gamut 4 to ACES2065-1
// CLFtransformID: urn:aswf:ocio:transformId:1.0:ARRI:Input:Linear_ARRI_Wide_Gamut_4_to_ACES2065-1:1.0
#define kOfxColourspaceLinArriWideGamut4 "lin_arri_wide_gamut_4"
#define kOfxColourspaceLinArriWideGamut4Label "Linear ARRI Wide Gamut 4"
#define kOfxColourspaceLinArriWideGamut4Encoding "scene-linear"
#define kOfxColourspaceLinArriWideGamut4IsData false
#define kOfxColourspaceLinArriWideGamut4IsBasic false
#define kOfxColourspaceLinArriWideGamut4IsCore false
#define kOfxColourspaceLinArriWideGamut4IsDisplay false

// arri_logc4
// Convert ARRI LogC4 to ACES2065-1
// CLFtransformID: urn:aswf:ocio:transformId:1.0:ARRI:Input:ARRI_LogC4_to_ACES2065-1:1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:IDT.ARRI.ARRI-LogC4.a1.v1
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.LogC4_to_ACES.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.ACES_to_LogC4.a1.1.0
#define kOfxColourspaceArriLogc4 "arri_logc4"
#define kOfxColourspaceArriLogc4Label "ARRI LogC4"
#define kOfxColourspaceArriLogc4Encoding "log"
#define kOfxColourspaceArriLogc4IsData false
#define kOfxColourspaceArriLogc4IsBasic false
#define kOfxColourspaceArriLogc4IsCore false
#define kOfxColourspaceArriLogc4IsDisplay false

// bmdfilm_widegamut_gen5
// Convert Blackmagic Film Wide Gamut (Gen 5) to ACES2065-1
// CLFtransformID: urn:aswf:ocio:transformId:1.0:BlackmagicDesign:Input:BMDFilm_WideGamut_Gen5_to_ACES2065-1:1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:IDT.BlackmagicDesign.BMDFilm_WideGamut_Gen5.a1.v1
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.ACES_to_BMDFilm_WideGamut_Gen5.a1.v1
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.BMDFilm_WideGamut_Gen5_to_ACES.a1.v1
#define kOfxColourspaceBmdfilmWidegamutGen5 "bmdfilm_widegamut_gen5"
#define kOfxColourspaceBmdfilmWidegamutGen5Label "BMDFilm WideGamut Gen5"
#define kOfxColourspaceBmdfilmWidegamutGen5Encoding "log"
#define kOfxColourspaceBmdfilmWidegamutGen5IsData false
#define kOfxColourspaceBmdfilmWidegamutGen5IsBasic false
#define kOfxColourspaceBmdfilmWidegamutGen5IsCore false
#define kOfxColourspaceBmdfilmWidegamutGen5IsDisplay false

// davinci_intermediate_widegamut
// Convert DaVinci Intermediate Wide Gamut to ACES2065-1
// CLFtransformID: urn:aswf:ocio:transformId:1.0:BlackmagicDesign:Input:DaVinci_Intermediate_WideGamut_to_ACES2065-1:1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.DaVinci_Intermediate_WideGamut_to_ACES.a1.v1
#define kOfxColourspaceDavinciIntermediateWidegamut "davinci_intermediate_widegamut"
#define kOfxColourspaceDavinciIntermediateWidegamutLabel "DaVinci Intermediate WideGamut"
#define kOfxColourspaceDavinciIntermediateWidegamutEncoding "log"
#define kOfxColourspaceDavinciIntermediateWidegamutIsData false
#define kOfxColourspaceDavinciIntermediateWidegamutIsBasic false
#define kOfxColourspaceDavinciIntermediateWidegamutIsCore false
#define kOfxColourspaceDavinciIntermediateWidegamutIsDisplay false

// lin_bmd_widegamut_gen5
// Convert Linear Blackmagic Wide Gamut (Gen 5) to ACES2065-1
// CLFtransformID: urn:aswf:ocio:transformId:1.0:BlackmagicDesign:Input:Linear_BMD_WideGamut_Gen5_to_ACES2065-1:1.0
#define kOfxColourspaceLinBmdWidegamutGen5 "lin_bmd_widegamut_gen5"
#define kOfxColourspaceLinBmdWidegamutGen5Label "Linear BMD WideGamut Gen5"
#define kOfxColourspaceLinBmdWidegamutGen5Encoding "scene-linear"
#define kOfxColourspaceLinBmdWidegamutGen5IsData false
#define kOfxColourspaceLinBmdWidegamutGen5IsBasic false
#define kOfxColourspaceLinBmdWidegamutGen5IsCore false
#define kOfxColourspaceLinBmdWidegamutGen5IsDisplay false

// lin_davinci_widegamut
// Convert Linear DaVinci Wide Gamut to ACES2065-1
// CLFtransformID: urn:aswf:ocio:transformId:1.0:BlackmagicDesign:Input:Linear_DaVinci_WideGamut_to_ACES2065-1:1.0
#define kOfxColourspaceLinDavinciWidegamut "lin_davinci_widegamut"
#define kOfxColourspaceLinDavinciWidegamutLabel "Linear DaVinci WideGamut"
#define kOfxColourspaceLinDavinciWidegamutEncoding "scene-linear"
#define kOfxColourspaceLinDavinciWidegamutIsData false
#define kOfxColourspaceLinDavinciWidegamutIsBasic false
#define kOfxColourspaceLinDavinciWidegamutIsCore false
#define kOfxColourspaceLinDavinciWidegamutIsDisplay false

// canonlog2_cinemagamut_d55
// Convert Canon Log 2 Cinema Gamut (Daylight) to ACES2065-1
// CLFtransformID: urn:aswf:ocio:transformId:1.0:Canon:Input:CanonLog2_CinemaGamut-D55_to_ACES2065-1:1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.CLog2_CGamut_to_ACES.a1.1.0
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.ACES_to_CLog2_CGamut.a1.1.0
#define kOfxColourspaceCanonlog2CinemagamutD55 "canonlog2_cinemagamut_d55"
#define kOfxColourspaceCanonlog2CinemagamutD55Label "CanonLog2 CinemaGamut D55"
#define kOfxColourspaceCanonlog2CinemagamutD55Encoding "log"
#define kOfxColourspaceCanonlog2CinemagamutD55IsData false
#define kOfxColourspaceCanonlog2CinemagamutD55IsBasic false
#define kOfxColourspaceCanonlog2CinemagamutD55IsCore false
#define kOfxColourspaceCanonlog2CinemagamutD55IsDisplay false

// canonlog3_cinemagamut_d55
// Convert Canon Log 3 Cinema Gamut (Daylight) to ACES2065-1
// CLFtransformID: urn:aswf:ocio:transformId:1.0:Canon:Input:CanonLog3_CinemaGamut-D55_to_ACES2065-1:1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.CLog3_CGamut_to_ACES.a1.1.0
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.ACES_to_CLog3_CGamut.a1.1.0
#define kOfxColourspaceCanonlog3CinemagamutD55 "canonlog3_cinemagamut_d55"
#define kOfxColourspaceCanonlog3CinemagamutD55Label "CanonLog3 CinemaGamut D55"
#define kOfxColourspaceCanonlog3CinemagamutD55Encoding "log"
#define kOfxColourspaceCanonlog3CinemagamutD55IsData false
#define kOfxColourspaceCanonlog3CinemagamutD55IsBasic false
#define kOfxColourspaceCanonlog3CinemagamutD55IsCore false
#define kOfxColourspaceCanonlog3CinemagamutD55IsDisplay false

// lin_cinemagamut_d55
// Convert Linear Canon Cinema Gamut (Daylight) to ACES2065-1
// CLFtransformID: urn:aswf:ocio:transformId:1.0:Canon:Input:Linear-CinemaGamut-D55_to_ACES2065-1:1.0
#define kOfxColourspaceLinCinemagamutD55 "lin_cinemagamut_d55"
#define kOfxColourspaceLinCinemagamutD55Label "Linear CinemaGamut D55"
#define kOfxColourspaceLinCinemagamutD55Encoding "scene-linear"
#define kOfxColourspaceLinCinemagamutD55IsData false
#define kOfxColourspaceLinCinemagamutD55IsBasic false
#define kOfxColourspaceLinCinemagamutD55IsCore false
#define kOfxColourspaceLinCinemagamutD55IsDisplay false

// lin_vgamut
// Convert Linear Panasonic V-Gamut to ACES2065-1
// CLFtransformID: urn:aswf:ocio:transformId:1.0:Panasonic:Input:Linear_VGamut_to_ACES2065-1:1.0
#define kOfxColourspaceLinVgamut "lin_vgamut"
#define kOfxColourspaceLinVgamutLabel "Linear V-Gamut"
#define kOfxColourspaceLinVgamutEncoding "scene-linear"
#define kOfxColourspaceLinVgamutIsData false
#define kOfxColourspaceLinVgamutIsBasic false
#define kOfxColourspaceLinVgamutIsCore false
#define kOfxColourspaceLinVgamutIsDisplay false

// vlog_vgamut
// Convert Panasonic V-Log - V-Gamut to ACES2065-1
// CLFtransformID: urn:aswf:ocio:transformId:1.0:Panasonic:Input:VLog_VGamut_to_ACES2065-1:1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.VLog_VGamut_to_ACES.a1.1.0
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.ACES_to_VLog_VGamut.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:IDT.Panasonic.VLog_VGamut.a1.v1
#define kOfxColourspaceVlogVgamut "vlog_vgamut"
#define kOfxColourspaceVlogVgamutLabel "V-Log V-Gamut"
#define kOfxColourspaceVlogVgamutEncoding "log"
#define kOfxColourspaceVlogVgamutIsData false
#define kOfxColourspaceVlogVgamutIsBasic false
#define kOfxColourspaceVlogVgamutIsCore false
#define kOfxColourspaceVlogVgamutIsDisplay false

// lin_redwidegamutrgb
// Convert Linear REDWideGamutRGB to ACES2065-1
// CLFtransformID: urn:aswf:ocio:transformId:1.0:RED:Input:Linear_REDWideGamutRGB_to_ACES2065-1:1.0
#define kOfxColourspaceLinRedwidegamutrgb "lin_redwidegamutrgb"
#define kOfxColourspaceLinRedwidegamutrgbLabel "Linear REDWideGamutRGB"
#define kOfxColourspaceLinRedwidegamutrgbEncoding "scene-linear"
#define kOfxColourspaceLinRedwidegamutrgbIsData false
#define kOfxColourspaceLinRedwidegamutrgbIsBasic false
#define kOfxColourspaceLinRedwidegamutrgbIsCore false
#define kOfxColourspaceLinRedwidegamutrgbIsDisplay false

// log3g10_redwidegamutrgb
// Convert RED Log3G10 REDWideGamutRGB to ACES2065-1
// CLFtransformID: urn:aswf:ocio:transformId:1.0:RED:Input:Log3G10_REDWideGamutRGB_to_ACES2065-1:1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:IDT.RED.Log3G10_REDWideGamutRGB.a1.v1
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.ACES_to_Log3G10_RWG.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.Log3G10_RWG_to_ACES.a1.1.0
#define kOfxColourspaceLog3g10Redwidegamutrgb "log3g10_redwidegamutrgb"
#define kOfxColourspaceLog3g10RedwidegamutrgbLabel "Log3G10 REDWideGamutRGB"
#define kOfxColourspaceLog3g10RedwidegamutrgbEncoding "log"
#define kOfxColourspaceLog3g10RedwidegamutrgbIsData false
#define kOfxColourspaceLog3g10RedwidegamutrgbIsBasic false
#define kOfxColourspaceLog3g10RedwidegamutrgbIsCore false
#define kOfxColourspaceLog3g10RedwidegamutrgbIsDisplay false

// lin_sgamut3
// Convert Linear S-Gamut3 to ACES2065-1
// CLFtransformID: urn:aswf:ocio:transformId:1.0:Sony:Input:Linear_SGamut3_to_ACES2065-1:1.0
#define kOfxColourspaceLinSgamut3 "lin_sgamut3"
#define kOfxColourspaceLinSgamut3Label "Linear S-Gamut3"
#define kOfxColourspaceLinSgamut3Encoding "scene-linear"
#define kOfxColourspaceLinSgamut3IsData false
#define kOfxColourspaceLinSgamut3IsBasic false
#define kOfxColourspaceLinSgamut3IsCore false
#define kOfxColourspaceLinSgamut3IsDisplay false

// lin_sgamut3cine
// Convert Linear S-Gamut3.Cine to ACES2065-1
// CLFtransformID: urn:aswf:ocio:transformId:1.0:Sony:Input:Linear_SGamut3Cine_to_ACES2065-1:1.0
#define kOfxColourspaceLinSgamut3cine "lin_sgamut3cine"
#define kOfxColourspaceLinSgamut3cineLabel "Linear S-Gamut3.Cine"
#define kOfxColourspaceLinSgamut3cineEncoding "scene-linear"
#define kOfxColourspaceLinSgamut3cineIsData false
#define kOfxColourspaceLinSgamut3cineIsBasic false
#define kOfxColourspaceLinSgamut3cineIsCore false
#define kOfxColourspaceLinSgamut3cineIsDisplay false

// lin_venice_sgamut3
// Convert Linear Venice S-Gamut3 to ACES2065-1
// CLFtransformID: urn:aswf:ocio:transformId:1.0:Sony:Input:Linear_Venice_SGamut3_to_ACES2065-1:1.0
#define kOfxColourspaceLinVeniceSgamut3 "lin_venice_sgamut3"
#define kOfxColourspaceLinVeniceSgamut3Label "Linear Venice S-Gamut3"
#define kOfxColourspaceLinVeniceSgamut3Encoding "scene-linear"
#define kOfxColourspaceLinVeniceSgamut3IsData false
#define kOfxColourspaceLinVeniceSgamut3IsBasic false
#define kOfxColourspaceLinVeniceSgamut3IsCore false
#define kOfxColourspaceLinVeniceSgamut3IsDisplay false

// lin_venice_sgamut3cine
// Convert Linear Venice S-Gamut3.Cine to ACES2065-1
// CLFtransformID: urn:aswf:ocio:transformId:1.0:Sony:Input:Linear_Venice_SGamut3Cine_to_ACES2065-1:1.0
#define kOfxColourspaceLinVeniceSgamut3cine "lin_venice_sgamut3cine"
#define kOfxColourspaceLinVeniceSgamut3cineLabel "Linear Venice S-Gamut3.Cine"
#define kOfxColourspaceLinVeniceSgamut3cineEncoding "scene-linear"
#define kOfxColourspaceLinVeniceSgamut3cineIsData false
#define kOfxColourspaceLinVeniceSgamut3cineIsBasic false
#define kOfxColourspaceLinVeniceSgamut3cineIsCore false
#define kOfxColourspaceLinVeniceSgamut3cineIsDisplay false

// slog3_sgamut3
// Convert Sony S-Log3 S-Gamut3 to ACES2065-1
// CLFtransformID: urn:aswf:ocio:transformId:1.0:Sony:Input:SLog3_SGamut3_to_ACES2065-1:1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:IDT.Sony.SLog3_SGamut3.a1.v1
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.ACES_to_SLog3_SGamut3.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.SLog3_SGamut3_to_ACES.a1.1.0
#define kOfxColourspaceSlog3Sgamut3 "slog3_sgamut3"
#define kOfxColourspaceSlog3Sgamut3Label "S-Log3 S-Gamut3"
#define kOfxColourspaceSlog3Sgamut3Encoding "log"
#define kOfxColourspaceSlog3Sgamut3IsData false
#define kOfxColourspaceSlog3Sgamut3IsBasic false
#define kOfxColourspaceSlog3Sgamut3IsCore false
#define kOfxColourspaceSlog3Sgamut3IsDisplay false

// slog3_sgamut3cine
// Convert Sony S-Log3 S-Gamut3.Cine to ACES2065-1
// CLFtransformID: urn:aswf:ocio:transformId:1.0:Sony:Input:SLog3_SGamut3Cine_to_ACES2065-1:1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:IDT.Sony.SLog3_SGamut3Cine.a1.v1
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.ACES_to_SLog3_SGamut3Cine.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.SLog3_SGamut3Cine_to_ACES.a1.1.0
#define kOfxColourspaceSlog3Sgamut3cine "slog3_sgamut3cine"
#define kOfxColourspaceSlog3Sgamut3cineLabel "S-Log3 S-Gamut3.Cine"
#define kOfxColourspaceSlog3Sgamut3cineEncoding "log"
#define kOfxColourspaceSlog3Sgamut3cineIsData false
#define kOfxColourspaceSlog3Sgamut3cineIsBasic false
#define kOfxColourspaceSlog3Sgamut3cineIsCore false
#define kOfxColourspaceSlog3Sgamut3cineIsDisplay false

// slog3_venice_sgamut3
// Convert Sony S-Log3 Venice S-Gamut3 to ACES2065-1
// CLFtransformID: urn:aswf:ocio:transformId:1.0:Sony:Input:SLog3_Venice_SGamut3_to_ACES2065-1:1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:IDT.Sony.Venice_SLog3_SGamut3.a1.v1
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.ACES_to_SLog3_Venice_SGamut3.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.SLog3_Venice_SGamut3_to_ACES.a1.1.0
#define kOfxColourspaceSlog3VeniceSgamut3 "slog3_venice_sgamut3"
#define kOfxColourspaceSlog3VeniceSgamut3Label "S-Log3 Venice S-Gamut3"
#define kOfxColourspaceSlog3VeniceSgamut3Encoding "log"
#define kOfxColourspaceSlog3VeniceSgamut3IsData false
#define kOfxColourspaceSlog3VeniceSgamut3IsBasic false
#define kOfxColourspaceSlog3VeniceSgamut3IsCore false
#define kOfxColourspaceSlog3VeniceSgamut3IsDisplay false

// slog3_venice_sgamut3cine
// Convert Sony S-Log3 Venice S-Gamut3.Cine to ACES2065-1
// CLFtransformID: urn:aswf:ocio:transformId:1.0:Sony:Input:SLog3_Venice_SGamut3Cine_to_ACES2065-1:1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:IDT.Sony.Venice_SLog3_SGamut3Cine.a1.v1
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.ACES_to_SLog3_Venice_SGamut3Cine.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.SLog3_Venice_SGamut3Cine_to_ACES.a1.1.0
#define kOfxColourspaceSlog3VeniceSgamut3cine "slog3_venice_sgamut3cine"
#define kOfxColourspaceSlog3VeniceSgamut3cineLabel "S-Log3 Venice S-Gamut3.Cine"
#define kOfxColourspaceSlog3VeniceSgamut3cineEncoding "log"
#define kOfxColourspaceSlog3VeniceSgamut3cineIsData false
#define kOfxColourspaceSlog3VeniceSgamut3cineIsBasic false
#define kOfxColourspaceSlog3VeniceSgamut3cineIsCore false
#define kOfxColourspaceSlog3VeniceSgamut3cineIsDisplay false

// camera_rec709
// Convert ACES2065-1 to Rec.709 camera OETF Rec.709 primaries, D65 white point
// CLFtransformID: urn:aswf:ocio:transformId:1.0:ITU:Utility:AP0_to_Camera_Rec709:1.0
#define kOfxColourspaceCameraRec709 "camera_rec709"
#define kOfxColourspaceCameraRec709Label "Camera Rec.709"
#define kOfxColourspaceCameraRec709Encoding "sdr-video"
#define kOfxColourspaceCameraRec709IsData false
#define kOfxColourspaceCameraRec709IsBasic false
#define kOfxColourspaceCameraRec709IsCore false
#define kOfxColourspaceCameraRec709IsDisplay false

/** @brief Roles - standard names used for compatibility with common OCIO configs.
*/

/** @brief aces_interchange
Guaranteed to be ACES2065-1.
*/
#define kOfxColourspaceRoleAcesInterchange "aces_interchange"
#define kOfxColourspaceRoleAcesInterchangeIsBasic false
#define kOfxColourspaceRoleAcesInterchangeIsCore true

/** @brief cie_xyz_d65_interchange
CIE XYZ colorimetry with the neutral axis at D65.
*/
#define kOfxColourspaceRoleCieXyzD65Interchange "cie_xyz_d65_interchange"
#define kOfxColourspaceRoleCieXyzD65InterchangeIsBasic false
#define kOfxColourspaceRoleCieXyzD65InterchangeIsCore true

/** @brief color_picking
The colourspace to use for colour pickers, typically a display colourspace.
*/
#define kOfxColourspaceRoleColorPicking "color_picking"
#define kOfxColourspaceRoleColorPickingIsBasic false
#define kOfxColourspaceRoleColorPickingIsCore true

/** @brief color_timing
A colourspace suitable for colour grading, typically a log colourspace.
*/
#define kOfxColourspaceRoleColorTiming "color_timing"
#define kOfxColourspaceRoleColorTimingIsBasic false
#define kOfxColourspaceRoleColorTimingIsCore true

/** @brief compositing_log
Any scene-referred colourspace with a log transfer function.
*/
#define kOfxColourspaceRoleCompositingLog "compositing_log"
#define kOfxColourspaceRoleCompositingLogIsBasic false
#define kOfxColourspaceRoleCompositingLogIsCore true

/** @brief data
Image values should not be treated as colour, e.g. motion vectors or masks. Mapped to the raw colourspace.
*/
#define kOfxColourspaceRoleData "data"
#define kOfxColourspaceRoleDataIsBasic false
#define kOfxColourspaceRoleDataIsCore true

/** @brief matte_paint
A colourspace suitable for matte painting.
*/
#define kOfxColourspaceRoleMattePaint "matte_paint"
#define kOfxColourspaceRoleMattePaintIsBasic false
#define kOfxColourspaceRoleMattePaintIsCore true

/** @brief scene_linear
Any scene-referred linear colourspace.
*/
#define kOfxColourspaceRoleSceneLinear "scene_linear"
#define kOfxColourspaceRoleSceneLinearIsBasic false
#define kOfxColourspaceRoleSceneLinearIsCore true

/** @brief texture_paint
A colourspace suitable for texture painting, typically sRGB.
*/
#define kOfxColourspaceRoleTexturePaint "texture_paint"
#define kOfxColourspaceRoleTexturePaintIsBasic false
#define kOfxColourspaceRoleTexturePaintIsCore true

#ifdef __cplusplus
}
#endif

#endif

