#ifndef _ofxColourspaceList_h_
#define _ofxColourspaceList_h_

// Copyright OpenFX and contributors to the OpenFX project.
// SPDX-License-Identifier: BSD-3-Clause

#ifdef __cplusplus
extern "C" {
#endif

/** @file ofxColourspaceList.h
Contains the list of supported colourspaces.
This file was auto-generated by scripts/genColour from studio-config-v2.1.0_aces-v1.3_ocio-v2.3.
*/

// Roles

// aces_interchange
#define kOfxColourspaceRoleAcesInterchange "aces_interchange"
#define kOfxColourspaceRoleAcesInterchangeColourspace "ACES2065-1"
#define kOfxColourspaceRoleAcesInterchangeMapping { "aces_interchange", "ACES2065-1" }

// cie_xyz_d65_interchange
#define kOfxColourspaceRoleCieXyzD65Interchange "cie_xyz_d65_interchange"
#define kOfxColourspaceRoleCieXyzD65InterchangeColourspace "CIE-XYZ-D65"
#define kOfxColourspaceRoleCieXyzD65InterchangeMapping { "cie_xyz_d65_interchange", "CIE-XYZ-D65" }

// color_picking
#define kOfxColourspaceRoleColorPicking "color_picking"
#define kOfxColourspaceRoleColorPickingColourspace "srgb_tx"
#define kOfxColourspaceRoleColorPickingMapping { "color_picking", "srgb_tx" }

// color_timing
#define kOfxColourspaceRoleColorTiming "color_timing"
#define kOfxColourspaceRoleColorTimingColourspace "ACEScct"
#define kOfxColourspaceRoleColorTimingMapping { "color_timing", "ACEScct" }

// compositing_log
#define kOfxColourspaceRoleCompositingLog "compositing_log"
#define kOfxColourspaceRoleCompositingLogColourspace "ACEScct"
#define kOfxColourspaceRoleCompositingLogMapping { "compositing_log", "ACEScct" }

// data
#define kOfxColourspaceRoleData "data"
#define kOfxColourspaceRoleDataColourspace "Raw"
#define kOfxColourspaceRoleDataMapping { "data", "Raw" }

// matte_paint
#define kOfxColourspaceRoleMattePaint "matte_paint"
#define kOfxColourspaceRoleMattePaintColourspace "ACEScct"
#define kOfxColourspaceRoleMattePaintMapping { "matte_paint", "ACEScct" }

// scene_linear
#define kOfxColourspaceRoleSceneLinear "scene_linear"
#define kOfxColourspaceRoleSceneLinearColourspace "ACEScg"
#define kOfxColourspaceRoleSceneLinearMapping { "scene_linear", "ACEScg" }

// texture_paint
#define kOfxColourspaceRoleTexturePaint "texture_paint"
#define kOfxColourspaceRoleTexturePaintColourspace "srgb_tx"
#define kOfxColourspaceRoleTexturePaintMapping { "texture_paint", "srgb_tx" }

// Display Colourspaces

// srgb_display
// Convert CIE XYZ (D65 white) to sRGB (piecewise EOTF)
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ODT.Academy.RGBmonitor_100nits_dim.a1.0.3
// ACEStransformID: urn:ampas:aces:transformId:v1.5:InvODT.Academy.RGBmonitor_100nits_dim.a1.0.3
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ODT.Academy.RGBmonitor_D60sim_100nits_dim.a1.0.3
// ACEStransformID: urn:ampas:aces:transformId:v1.5:InvODT.Academy.RGBmonitor_D60sim_100nits_dim.a1.0.3
#define kOfxColourspaceSrgbDisplay "srgb_display"
#define kOfxColourspaceSrgbDisplayDisplayName "sRGB - Display"
#define kOfxColourspaceSrgbDisplayAliasSrgbDisplay "srgb_display"
#define kOfxColourspaceSrgbDisplayList { "sRGB - Display", "srgb_display" }
#define kOfxColourspaceSrgbDisplayEncoding "sdr-video"
#define kOfxColourspaceSrgbDisplayIsSceneLinear false
#define kOfxColourspaceSrgbDisplayIsData false
#define kOfxColourspaceSrgbDisplayIsCore true

// displayp3_display
// Convert CIE XYZ (D65 white) to Apple Display P3
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ODT.Academy.DisplayP3_dim.a1.0.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:InvODT.Academy.DisplayP3_dim.a1.0.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ODT.Academy.DisplayP3_D60sim_dim.a1.0.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:InvODT.Academy.DisplayP3_D60sim_dim.a1.0.0
#define kOfxColourspaceDisplayp3Display "displayp3_display"
#define kOfxColourspaceDisplayp3DisplayDisplayName "Display P3 - Display"
#define kOfxColourspaceDisplayp3DisplayAliasDisplayp3Display "displayp3_display"
#define kOfxColourspaceDisplayp3DisplayList { "Display P3 - Display", "displayp3_display" }
#define kOfxColourspaceDisplayp3DisplayEncoding "sdr-video"
#define kOfxColourspaceDisplayp3DisplayIsSceneLinear false
#define kOfxColourspaceDisplayp3DisplayIsData false
#define kOfxColourspaceDisplayp3DisplayIsCore true

// rec1886_rec709_display
// Convert CIE XYZ (D65 white) to Rec.1886/Rec.709 (HD video)
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ODT.Academy.Rec709_100nits_dim.a1.0.3
// ACEStransformID: urn:ampas:aces:transformId:v1.5:InvODT.Academy.Rec709_100nits_dim.a1.0.3
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ODT.Academy.Rec709_D60sim_100nits_dim.a1.0.3
// ACEStransformID: urn:ampas:aces:transformId:v1.5:InvODT.Academy.Rec709_D60sim_100nits_dim.a1.0.3
#define kOfxColourspaceRec1886Rec709Display "rec1886_rec709_display"
#define kOfxColourspaceRec1886Rec709DisplayDisplayName "Rec.1886 Rec.709 - Display"
#define kOfxColourspaceRec1886Rec709DisplayAliasRec1886Rec709Display "rec1886_rec709_display"
#define kOfxColourspaceRec1886Rec709DisplayList { "Rec.1886 Rec.709 - Display", "rec1886_rec709_display" }
#define kOfxColourspaceRec1886Rec709DisplayEncoding "sdr-video"
#define kOfxColourspaceRec1886Rec709DisplayIsSceneLinear false
#define kOfxColourspaceRec1886Rec709DisplayIsData false
#define kOfxColourspaceRec1886Rec709DisplayIsCore true

// rec1886_rec2020_display
// Convert CIE XYZ (D65 white) to Rec.1886/Rec.2020 (UHD video)
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ODT.Academy.Rec2020_100nits_dim.a1.0.3
// ACEStransformID: urn:ampas:aces:transformId:v1.5:InvODT.Academy.Rec2020_100nits_dim.a1.0.3
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ODT.Academy.Rec2020_P3D65limited_100nits_dim.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ODT.Academy.Rec2020_Rec709limited_100nits_dim.a1.1.0
#define kOfxColourspaceRec1886Rec2020Display "rec1886_rec2020_display"
#define kOfxColourspaceRec1886Rec2020DisplayDisplayName "Rec.1886 Rec.2020 - Display"
#define kOfxColourspaceRec1886Rec2020DisplayAliasRec1886Rec2020Display "rec1886_rec2020_display"
#define kOfxColourspaceRec1886Rec2020DisplayList { "Rec.1886 Rec.2020 - Display", "rec1886_rec2020_display" }
#define kOfxColourspaceRec1886Rec2020DisplayEncoding "sdr-video"
#define kOfxColourspaceRec1886Rec2020DisplayIsSceneLinear false
#define kOfxColourspaceRec1886Rec2020DisplayIsData false
#define kOfxColourspaceRec1886Rec2020DisplayIsCore false

// rec2100_hlg_display
// Convert CIE XYZ (D65 white) to Rec.2100-HLG, 1000 nit
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:RRTODT.Academy.Rec2020_1000nits_15nits_HLG.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:InvRRTODT.Academy.Rec2020_1000nits_15nits_HLG.a1.1.0
#define kOfxColourspaceRec2100HlgDisplay "rec2100_hlg_display"
#define kOfxColourspaceRec2100HlgDisplayDisplayName "Rec.2100-HLG - Display"
#define kOfxColourspaceRec2100HlgDisplayAliasRec2100HlgDisplay "rec2100_hlg_display"
#define kOfxColourspaceRec2100HlgDisplayList { "Rec.2100-HLG - Display", "rec2100_hlg_display" }
#define kOfxColourspaceRec2100HlgDisplayEncoding "hdr-video"
#define kOfxColourspaceRec2100HlgDisplayIsSceneLinear false
#define kOfxColourspaceRec2100HlgDisplayIsData false
#define kOfxColourspaceRec2100HlgDisplayIsCore false

// rec2100_pq_display
// Convert CIE XYZ (D65 white) to Rec.2100-PQ
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:RRTODT.Academy.Rec2020_1000nits_15nits_ST2084.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:InvRRTODT.Academy.Rec2020_1000nits_15nits_ST2084.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:RRTODT.Academy.Rec2020_2000nits_15nits_ST2084.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:InvRRTODT.Academy.Rec2020_2000nits_15nits_ST2084.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:RRTODT.Academy.Rec2020_4000nits_15nits_ST2084.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:InvRRTODT.Academy.Rec2020_4000nits_15nits_ST2084.a1.1.0
#define kOfxColourspaceRec2100PqDisplay "rec2100_pq_display"
#define kOfxColourspaceRec2100PqDisplayDisplayName "Rec.2100-PQ - Display"
#define kOfxColourspaceRec2100PqDisplayAliasRec2100PqDisplay "rec2100_pq_display"
#define kOfxColourspaceRec2100PqDisplayList { "Rec.2100-PQ - Display", "rec2100_pq_display" }
#define kOfxColourspaceRec2100PqDisplayEncoding "hdr-video"
#define kOfxColourspaceRec2100PqDisplayIsSceneLinear false
#define kOfxColourspaceRec2100PqDisplayIsData false
#define kOfxColourspaceRec2100PqDisplayIsCore false

// st2084_p3d65_display
// Convert CIE XYZ (D65 white) to ST-2084 (PQ), P3-D65 primaries
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:RRTODT.Academy.P3D65_1000nits_15nits_ST2084.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:InvRRTODT.Academy.P3D65_1000nits_15nits_ST2084.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:RRTODT.Academy.P3D65_2000nits_15nits_ST2084.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:InvRRTODT.Academy.P3D65_2000nits_15nits_ST2084.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:RRTODT.Academy.P3D65_4000nits_15nits_ST2084.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:InvRRTODT.Academy.P3D65_4000nits_15nits_ST2084.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:RRTODT.Academy.P3D65_108nits_7point2nits_ST2084.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:InvRRTODT.Academy.P3D65_108nits_7point2nits_ST2084.a1.1.0
#define kOfxColourspaceSt2084P3d65Display "st2084_p3d65_display"
#define kOfxColourspaceSt2084P3d65DisplayDisplayName "ST2084-P3-D65 - Display"
#define kOfxColourspaceSt2084P3d65DisplayAliasSt2084P3d65Display "st2084_p3d65_display"
#define kOfxColourspaceSt2084P3d65DisplayList { "ST2084-P3-D65 - Display", "st2084_p3d65_display" }
#define kOfxColourspaceSt2084P3d65DisplayEncoding "hdr-video"
#define kOfxColourspaceSt2084P3d65DisplayIsSceneLinear false
#define kOfxColourspaceSt2084P3d65DisplayIsData false
#define kOfxColourspaceSt2084P3d65DisplayIsCore false

// p3d60_display
// Convert CIE XYZ (D65 white) to Gamma 2.6, P3-D60 (Bradford adaptation)
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ODT.Academy.P3D60_48nits.a1.0.3
// ACEStransformID: urn:ampas:aces:transformId:v1.5:InvODT.Academy.P3D60_48nits.a1.0.3
#define kOfxColourspaceP3d60Display "p3d60_display"
#define kOfxColourspaceP3d60DisplayDisplayName "P3-D60 - Display"
#define kOfxColourspaceP3d60DisplayAliasP3d60Display "p3d60_display"
#define kOfxColourspaceP3d60DisplayList { "P3-D60 - Display", "p3d60_display" }
#define kOfxColourspaceP3d60DisplayEncoding "sdr-video"
#define kOfxColourspaceP3d60DisplayIsSceneLinear false
#define kOfxColourspaceP3d60DisplayIsData false
#define kOfxColourspaceP3d60DisplayIsCore false

// p3d65_display
// Convert CIE XYZ (D65 white) to Gamma 2.6, P3-D65
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ODT.Academy.P3D65_48nits.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:InvODT.Academy.P3D65_48nits.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ODT.Academy.P3D65_Rec709limited_48nits.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ODT.Academy.P3D65_D60sim_48nits.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:InvODT.Academy.P3D65_D60sim_48nits.a1.1.0
#define kOfxColourspaceP3d65Display "p3d65_display"
#define kOfxColourspaceP3d65DisplayDisplayName "P3-D65 - Display"
#define kOfxColourspaceP3d65DisplayAliasP3d65Display "p3d65_display"
#define kOfxColourspaceP3d65DisplayList { "P3-D65 - Display", "p3d65_display" }
#define kOfxColourspaceP3d65DisplayEncoding "sdr-video"
#define kOfxColourspaceP3d65DisplayIsSceneLinear false
#define kOfxColourspaceP3d65DisplayIsData false
#define kOfxColourspaceP3d65DisplayIsCore false

// p3_dci_display
// Convert CIE XYZ (D65 white) to Gamma 2.6, P3-DCI (DCI white with Bradford adaptation)
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ODT.Academy.P3DCI_48nits.a1.0.3
// ACEStransformID: urn:ampas:aces:transformId:v1.5:InvODT.Academy.P3DCI_48nits.a1.0.3
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ODT.Academy.P3DCI_D65sim_48nits.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:InvODT.Academy.P3DCI_D65sim_48nits.a1.1.0
#define kOfxColourspaceP3DciDisplay "p3_dci_display"
#define kOfxColourspaceP3DciDisplayDisplayName "P3-DCI - Display"
#define kOfxColourspaceP3DciDisplayAliasP3DciDisplay "p3_dci_display"
#define kOfxColourspaceP3DciDisplayList { "P3-DCI - Display", "p3_dci_display" }
#define kOfxColourspaceP3DciDisplayEncoding "sdr-video"
#define kOfxColourspaceP3DciDisplayIsSceneLinear false
#define kOfxColourspaceP3DciDisplayIsData false
#define kOfxColourspaceP3DciDisplayIsCore false

// Scene Colourspaces

// ACES2065-1
// The "Academy Color Encoding System" reference colorspace.
#define kOfxColourspaceACES20651 "ACES2065-1"
#define kOfxColourspaceACES20651DisplayName "ACES2065-1"
#define kOfxColourspaceACES20651AliasAces20651 "aces2065_1"
#define kOfxColourspaceACES20651AliasACESACES20651 "ACES - ACES2065-1"
#define kOfxColourspaceACES20651AliasLinAp0 "lin_ap0"
#define kOfxColourspaceACES20651List { "ACES2065-1", "aces2065_1", "ACES - ACES2065-1", "lin_ap0" }
#define kOfxColourspaceACES20651Encoding "scene-linear"
#define kOfxColourspaceACES20651IsSceneLinear true
#define kOfxColourspaceACES20651IsData false
#define kOfxColourspaceACES20651IsCore true

// ACEScc
// Convert ACEScc to ACES2065-1
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.ACEScc_to_ACES.a1.0.3
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.ACES_to_ACEScc.a1.0.3
#define kOfxColourspaceACEScc "ACEScc"
#define kOfxColourspaceACESccDisplayName "ACEScc"
#define kOfxColourspaceACESccAliasACESACEScc "ACES - ACEScc"
#define kOfxColourspaceACESccAliasAcesccAp1 "acescc_ap1"
#define kOfxColourspaceACESccList { "ACEScc", "ACES - ACEScc", "acescc_ap1" }
#define kOfxColourspaceACESccEncoding "log"
#define kOfxColourspaceACESccIsSceneLinear false
#define kOfxColourspaceACESccIsData false
#define kOfxColourspaceACESccIsCore true

// ACEScct
// Convert ACEScct to ACES2065-1
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.ACEScct_to_ACES.a1.0.3
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.ACES_to_ACEScct.a1.0.3
#define kOfxColourspaceACEScct "ACEScct"
#define kOfxColourspaceACEScctDisplayName "ACEScct"
#define kOfxColourspaceACEScctAliasACESACEScct "ACES - ACEScct"
#define kOfxColourspaceACEScctAliasAcescctAp1 "acescct_ap1"
#define kOfxColourspaceACEScctList { "ACEScct", "ACES - ACEScct", "acescct_ap1" }
#define kOfxColourspaceACEScctEncoding "log"
#define kOfxColourspaceACEScctIsSceneLinear false
#define kOfxColourspaceACEScctIsData false
#define kOfxColourspaceACEScctIsCore true

// ACEScg
// Convert ACEScg to ACES2065-1
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.ACEScg_to_ACES.a1.0.3
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.ACES_to_ACEScg.a1.0.3
#define kOfxColourspaceACEScg "ACEScg"
#define kOfxColourspaceACEScgDisplayName "ACEScg"
#define kOfxColourspaceACEScgAliasACESACEScg "ACES - ACEScg"
#define kOfxColourspaceACEScgAliasLinAp1 "lin_ap1"
#define kOfxColourspaceACEScgList { "ACEScg", "ACES - ACEScg", "lin_ap1" }
#define kOfxColourspaceACEScgEncoding "scene-linear"
#define kOfxColourspaceACEScgIsSceneLinear true
#define kOfxColourspaceACEScgIsData false
#define kOfxColourspaceACEScgIsCore true

// ADX10
// Convert ADX10 to ACES2065-1
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.ADX10_to_ACES.a1.0.3
#define kOfxColourspaceADX10 "ADX10"
#define kOfxColourspaceADX10DisplayName "ADX10"
#define kOfxColourspaceADX10AliasInputADXADX10 "Input - ADX - ADX10"
#define kOfxColourspaceADX10List { "ADX10", "Input - ADX - ADX10" }
#define kOfxColourspaceADX10Encoding "log"
#define kOfxColourspaceADX10IsSceneLinear false
#define kOfxColourspaceADX10IsData false
#define kOfxColourspaceADX10IsCore false

// ADX16
// Convert ADX16 to ACES2065-1
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.ADX16_to_ACES.a1.0.3
#define kOfxColourspaceADX16 "ADX16"
#define kOfxColourspaceADX16DisplayName "ADX16"
#define kOfxColourspaceADX16AliasInputADXADX16 "Input - ADX - ADX16"
#define kOfxColourspaceADX16List { "ADX16", "Input - ADX - ADX16" }
#define kOfxColourspaceADX16Encoding "log"
#define kOfxColourspaceADX16IsSceneLinear false
#define kOfxColourspaceADX16IsData false
#define kOfxColourspaceADX16IsCore false

// lin_arri_wide_gamut_3
// Convert Linear ARRI Wide Gamut 3 to ACES2065-1
// CLFtransformID: urn:aswf:ocio:transformId:1.0:ARRI:Input:Linear_ARRI_Wide_Gamut_3_to_ACES2065-1:1.0
#define kOfxColourspaceLinArriWideGamut3 "lin_arri_wide_gamut_3"
#define kOfxColourspaceLinArriWideGamut3DisplayName "Linear ARRI Wide Gamut 3"
#define kOfxColourspaceLinArriWideGamut3AliasLinArriWideGamut3 "lin_arri_wide_gamut_3"
#define kOfxColourspaceLinArriWideGamut3AliasInputARRILinearALEXAWideGamut "Input - ARRI - Linear - ALEXA Wide Gamut"
#define kOfxColourspaceLinArriWideGamut3AliasLinAlexawide "lin_alexawide"
#define kOfxColourspaceLinArriWideGamut3List { "Linear ARRI Wide Gamut 3", "lin_arri_wide_gamut_3", "Input - ARRI - Linear - ALEXA Wide Gamut", "lin_alexawide" }
#define kOfxColourspaceLinArriWideGamut3Encoding "scene-linear"
#define kOfxColourspaceLinArriWideGamut3IsSceneLinear true
#define kOfxColourspaceLinArriWideGamut3IsData false
#define kOfxColourspaceLinArriWideGamut3IsCore false

// arri_logc3_ei800
// Convert ARRI LogC3 (EI800) to ACES2065-1
// CLFtransformID: urn:aswf:ocio:transformId:1.0:ARRI:Input:ARRI_LogC3_EI800_to_ACES2065-1:1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:IDT.ARRI.Alexa-v3-logC-EI800.a1.v2
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.ACES_to_LogC_EI800_AWG.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.LogC_EI800_AWG_to_ACES.a1.1.0
#define kOfxColourspaceArriLogc3Ei800 "arri_logc3_ei800"
#define kOfxColourspaceArriLogc3Ei800DisplayName "ARRI LogC3 (EI800)"
#define kOfxColourspaceArriLogc3Ei800AliasArriLogc3Ei800 "arri_logc3_ei800"
#define kOfxColourspaceArriLogc3Ei800AliasInputARRIV3LogCEI800WideGamut "Input - ARRI - V3 LogC (EI800) - Wide Gamut"
#define kOfxColourspaceArriLogc3Ei800AliasLogc3ei800Alexawide "logc3ei800_alexawide"
#define kOfxColourspaceArriLogc3Ei800List { "ARRI LogC3 (EI800)", "arri_logc3_ei800", "Input - ARRI - V3 LogC (EI800) - Wide Gamut", "logc3ei800_alexawide" }
#define kOfxColourspaceArriLogc3Ei800Encoding "log"
#define kOfxColourspaceArriLogc3Ei800IsSceneLinear false
#define kOfxColourspaceArriLogc3Ei800IsData false
#define kOfxColourspaceArriLogc3Ei800IsCore false

// lin_arri_wide_gamut_4
// Convert Linear ARRI Wide Gamut 4 to ACES2065-1
// CLFtransformID: urn:aswf:ocio:transformId:1.0:ARRI:Input:Linear_ARRI_Wide_Gamut_4_to_ACES2065-1:1.0
#define kOfxColourspaceLinArriWideGamut4 "lin_arri_wide_gamut_4"
#define kOfxColourspaceLinArriWideGamut4DisplayName "Linear ARRI Wide Gamut 4"
#define kOfxColourspaceLinArriWideGamut4AliasLinArriWideGamut4 "lin_arri_wide_gamut_4"
#define kOfxColourspaceLinArriWideGamut4AliasLinAwg4 "lin_awg4"
#define kOfxColourspaceLinArriWideGamut4List { "Linear ARRI Wide Gamut 4", "lin_arri_wide_gamut_4", "lin_awg4" }
#define kOfxColourspaceLinArriWideGamut4Encoding "scene-linear"
#define kOfxColourspaceLinArriWideGamut4IsSceneLinear true
#define kOfxColourspaceLinArriWideGamut4IsData false
#define kOfxColourspaceLinArriWideGamut4IsCore false

// arri_logc4
// Convert ARRI LogC4 to ACES2065-1
// CLFtransformID: urn:aswf:ocio:transformId:1.0:ARRI:Input:ARRI_LogC4_to_ACES2065-1:1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:IDT.ARRI.ARRI-LogC4.a1.v1
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.LogC4_to_ACES.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.ACES_to_LogC4.a1.1.0
#define kOfxColourspaceArriLogc4 "arri_logc4"
#define kOfxColourspaceArriLogc4DisplayName "ARRI LogC4"
#define kOfxColourspaceArriLogc4AliasArriLogc4 "arri_logc4"
#define kOfxColourspaceArriLogc4List { "ARRI LogC4", "arri_logc4" }
#define kOfxColourspaceArriLogc4Encoding "log"
#define kOfxColourspaceArriLogc4IsSceneLinear false
#define kOfxColourspaceArriLogc4IsData false
#define kOfxColourspaceArriLogc4IsCore false

// bmdfilm_widegamut_gen5
// Convert Blackmagic Film Wide Gamut (Gen 5) to ACES2065-1
// CLFtransformID: urn:aswf:ocio:transformId:1.0:BlackmagicDesign:Input:BMDFilm_WideGamut_Gen5_to_ACES2065-1:1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:IDT.BlackmagicDesign.BMDFilm_WideGamut_Gen5.a1.v1
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.ACES_to_BMDFilm_WideGamut_Gen5.a1.v1
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.BMDFilm_WideGamut_Gen5_to_ACES.a1.v1
#define kOfxColourspaceBmdfilmWidegamutGen5 "bmdfilm_widegamut_gen5"
#define kOfxColourspaceBmdfilmWidegamutGen5DisplayName "BMDFilm WideGamut Gen5"
#define kOfxColourspaceBmdfilmWidegamutGen5AliasBmdfilmWidegamutGen5 "bmdfilm_widegamut_gen5"
#define kOfxColourspaceBmdfilmWidegamutGen5List { "BMDFilm WideGamut Gen5", "bmdfilm_widegamut_gen5" }
#define kOfxColourspaceBmdfilmWidegamutGen5Encoding "log"
#define kOfxColourspaceBmdfilmWidegamutGen5IsSceneLinear false
#define kOfxColourspaceBmdfilmWidegamutGen5IsData false
#define kOfxColourspaceBmdfilmWidegamutGen5IsCore false

// davinci_intermediate_widegamut
// Convert DaVinci Intermediate Wide Gamut to ACES2065-1
// CLFtransformID: urn:aswf:ocio:transformId:1.0:BlackmagicDesign:Input:DaVinci_Intermediate_WideGamut_to_ACES2065-1:1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.DaVinci_Intermediate_WideGamut_to_ACES.a1.v1
#define kOfxColourspaceDavinciIntermediateWidegamut "davinci_intermediate_widegamut"
#define kOfxColourspaceDavinciIntermediateWidegamutDisplayName "DaVinci Intermediate WideGamut"
#define kOfxColourspaceDavinciIntermediateWidegamutAliasDavinciIntermediateWidegamut "davinci_intermediate_widegamut"
#define kOfxColourspaceDavinciIntermediateWidegamutList { "DaVinci Intermediate WideGamut", "davinci_intermediate_widegamut" }
#define kOfxColourspaceDavinciIntermediateWidegamutEncoding "log"
#define kOfxColourspaceDavinciIntermediateWidegamutIsSceneLinear false
#define kOfxColourspaceDavinciIntermediateWidegamutIsData false
#define kOfxColourspaceDavinciIntermediateWidegamutIsCore false

// lin_bmd_widegamut_gen5
// Convert Linear Blackmagic Wide Gamut (Gen 5) to ACES2065-1
// CLFtransformID: urn:aswf:ocio:transformId:1.0:BlackmagicDesign:Input:Linear_BMD_WideGamut_Gen5_to_ACES2065-1:1.0
#define kOfxColourspaceLinBmdWidegamutGen5 "lin_bmd_widegamut_gen5"
#define kOfxColourspaceLinBmdWidegamutGen5DisplayName "Linear BMD WideGamut Gen5"
#define kOfxColourspaceLinBmdWidegamutGen5AliasLinBmdWidegamutGen5 "lin_bmd_widegamut_gen5"
#define kOfxColourspaceLinBmdWidegamutGen5List { "Linear BMD WideGamut Gen5", "lin_bmd_widegamut_gen5" }
#define kOfxColourspaceLinBmdWidegamutGen5Encoding "scene-linear"
#define kOfxColourspaceLinBmdWidegamutGen5IsSceneLinear true
#define kOfxColourspaceLinBmdWidegamutGen5IsData false
#define kOfxColourspaceLinBmdWidegamutGen5IsCore false

// lin_davinci_widegamut
// Convert Linear DaVinci Wide Gamut to ACES2065-1
// CLFtransformID: urn:aswf:ocio:transformId:1.0:BlackmagicDesign:Input:Linear_DaVinci_WideGamut_to_ACES2065-1:1.0
#define kOfxColourspaceLinDavinciWidegamut "lin_davinci_widegamut"
#define kOfxColourspaceLinDavinciWidegamutDisplayName "Linear DaVinci WideGamut"
#define kOfxColourspaceLinDavinciWidegamutAliasLinDavinciWidegamut "lin_davinci_widegamut"
#define kOfxColourspaceLinDavinciWidegamutList { "Linear DaVinci WideGamut", "lin_davinci_widegamut" }
#define kOfxColourspaceLinDavinciWidegamutEncoding "scene-linear"
#define kOfxColourspaceLinDavinciWidegamutIsSceneLinear true
#define kOfxColourspaceLinDavinciWidegamutIsData false
#define kOfxColourspaceLinDavinciWidegamutIsCore false

// canonlog2_cinemagamut_d55
// Convert Canon Log 2 Cinema Gamut (Daylight) to ACES2065-1
// CLFtransformID: urn:aswf:ocio:transformId:1.0:Canon:Input:CanonLog2_CinemaGamut-D55_to_ACES2065-1:1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.CLog2_CGamut_to_ACES.a1.1.0
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.ACES_to_CLog2_CGamut.a1.1.0
#define kOfxColourspaceCanonlog2CinemagamutD55 "canonlog2_cinemagamut_d55"
#define kOfxColourspaceCanonlog2CinemagamutD55DisplayName "CanonLog2 CinemaGamut D55"
#define kOfxColourspaceCanonlog2CinemagamutD55AliasCanonlog2CinemagamutD55 "canonlog2_cinemagamut_d55"
#define kOfxColourspaceCanonlog2CinemagamutD55AliasInputCanonCanonLog2CinemaGamutDaylight "Input - Canon - Canon-Log2 - Cinema Gamut Daylight"
#define kOfxColourspaceCanonlog2CinemagamutD55AliasCanonlog2Cgamutday "canonlog2_cgamutday"
#define kOfxColourspaceCanonlog2CinemagamutD55List { "CanonLog2 CinemaGamut D55", "canonlog2_cinemagamut_d55", "Input - Canon - Canon-Log2 - Cinema Gamut Daylight", "canonlog2_cgamutday" }
#define kOfxColourspaceCanonlog2CinemagamutD55Encoding "log"
#define kOfxColourspaceCanonlog2CinemagamutD55IsSceneLinear false
#define kOfxColourspaceCanonlog2CinemagamutD55IsData false
#define kOfxColourspaceCanonlog2CinemagamutD55IsCore false

// canonlog3_cinemagamut_d55
// Convert Canon Log 3 Cinema Gamut (Daylight) to ACES2065-1
// CLFtransformID: urn:aswf:ocio:transformId:1.0:Canon:Input:CanonLog3_CinemaGamut-D55_to_ACES2065-1:1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.CLog3_CGamut_to_ACES.a1.1.0
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.ACES_to_CLog3_CGamut.a1.1.0
#define kOfxColourspaceCanonlog3CinemagamutD55 "canonlog3_cinemagamut_d55"
#define kOfxColourspaceCanonlog3CinemagamutD55DisplayName "CanonLog3 CinemaGamut D55"
#define kOfxColourspaceCanonlog3CinemagamutD55AliasCanonlog3CinemagamutD55 "canonlog3_cinemagamut_d55"
#define kOfxColourspaceCanonlog3CinemagamutD55AliasInputCanonCanonLog3CinemaGamutDaylight "Input - Canon - Canon-Log3 - Cinema Gamut Daylight"
#define kOfxColourspaceCanonlog3CinemagamutD55AliasCanonlog3Cgamutday "canonlog3_cgamutday"
#define kOfxColourspaceCanonlog3CinemagamutD55List { "CanonLog3 CinemaGamut D55", "canonlog3_cinemagamut_d55", "Input - Canon - Canon-Log3 - Cinema Gamut Daylight", "canonlog3_cgamutday" }
#define kOfxColourspaceCanonlog3CinemagamutD55Encoding "log"
#define kOfxColourspaceCanonlog3CinemagamutD55IsSceneLinear false
#define kOfxColourspaceCanonlog3CinemagamutD55IsData false
#define kOfxColourspaceCanonlog3CinemagamutD55IsCore false

// lin_cinemagamut_d55
// Convert Linear Canon Cinema Gamut (Daylight) to ACES2065-1
// CLFtransformID: urn:aswf:ocio:transformId:1.0:Canon:Input:Linear-CinemaGamut-D55_to_ACES2065-1:1.0
#define kOfxColourspaceLinCinemagamutD55 "lin_cinemagamut_d55"
#define kOfxColourspaceLinCinemagamutD55DisplayName "Linear CinemaGamut D55"
#define kOfxColourspaceLinCinemagamutD55AliasLinCinemagamutD55 "lin_cinemagamut_d55"
#define kOfxColourspaceLinCinemagamutD55AliasInputCanonLinearCanonCinemaGamutDaylight "Input - Canon - Linear - Canon Cinema Gamut Daylight"
#define kOfxColourspaceLinCinemagamutD55AliasLinCanoncgamutday "lin_canoncgamutday"
#define kOfxColourspaceLinCinemagamutD55List { "Linear CinemaGamut D55", "lin_cinemagamut_d55", "Input - Canon - Linear - Canon Cinema Gamut Daylight", "lin_canoncgamutday" }
#define kOfxColourspaceLinCinemagamutD55Encoding "scene-linear"
#define kOfxColourspaceLinCinemagamutD55IsSceneLinear true
#define kOfxColourspaceLinCinemagamutD55IsData false
#define kOfxColourspaceLinCinemagamutD55IsCore false

// lin_vgamut
// Convert Linear Panasonic V-Gamut to ACES2065-1
// CLFtransformID: urn:aswf:ocio:transformId:1.0:Panasonic:Input:Linear_VGamut_to_ACES2065-1:1.0
#define kOfxColourspaceLinVgamut "lin_vgamut"
#define kOfxColourspaceLinVgamutDisplayName "Linear V-Gamut"
#define kOfxColourspaceLinVgamutAliasLinVgamut "lin_vgamut"
#define kOfxColourspaceLinVgamutAliasInputPanasonicLinearVGamut "Input - Panasonic - Linear - V-Gamut"
#define kOfxColourspaceLinVgamutList { "Linear V-Gamut", "lin_vgamut", "Input - Panasonic - Linear - V-Gamut" }
#define kOfxColourspaceLinVgamutEncoding "scene-linear"
#define kOfxColourspaceLinVgamutIsSceneLinear true
#define kOfxColourspaceLinVgamutIsData false
#define kOfxColourspaceLinVgamutIsCore false

// vlog_vgamut
// Convert Panasonic V-Log - V-Gamut to ACES2065-1
// CLFtransformID: urn:aswf:ocio:transformId:1.0:Panasonic:Input:VLog_VGamut_to_ACES2065-1:1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.VLog_VGamut_to_ACES.a1.1.0
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.ACES_to_VLog_VGamut.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:IDT.Panasonic.VLog_VGamut.a1.v1
#define kOfxColourspaceVlogVgamut "vlog_vgamut"
#define kOfxColourspaceVlogVgamutDisplayName "V-Log V-Gamut"
#define kOfxColourspaceVlogVgamutAliasVlogVgamut "vlog_vgamut"
#define kOfxColourspaceVlogVgamutAliasInputPanasonicVLogVGamut "Input - Panasonic - V-Log - V-Gamut"
#define kOfxColourspaceVlogVgamutList { "V-Log V-Gamut", "vlog_vgamut", "Input - Panasonic - V-Log - V-Gamut" }
#define kOfxColourspaceVlogVgamutEncoding "log"
#define kOfxColourspaceVlogVgamutIsSceneLinear false
#define kOfxColourspaceVlogVgamutIsData false
#define kOfxColourspaceVlogVgamutIsCore false

// lin_redwidegamutrgb
// Convert Linear REDWideGamutRGB to ACES2065-1
// CLFtransformID: urn:aswf:ocio:transformId:1.0:RED:Input:Linear_REDWideGamutRGB_to_ACES2065-1:1.0
#define kOfxColourspaceLinRedwidegamutrgb "lin_redwidegamutrgb"
#define kOfxColourspaceLinRedwidegamutrgbDisplayName "Linear REDWideGamutRGB"
#define kOfxColourspaceLinRedwidegamutrgbAliasLinRedwidegamutrgb "lin_redwidegamutrgb"
#define kOfxColourspaceLinRedwidegamutrgbAliasInputREDLinearREDWideGamutRGB "Input - RED - Linear - REDWideGamutRGB"
#define kOfxColourspaceLinRedwidegamutrgbAliasLinRwg "lin_rwg"
#define kOfxColourspaceLinRedwidegamutrgbList { "Linear REDWideGamutRGB", "lin_redwidegamutrgb", "Input - RED - Linear - REDWideGamutRGB", "lin_rwg" }
#define kOfxColourspaceLinRedwidegamutrgbEncoding "scene-linear"
#define kOfxColourspaceLinRedwidegamutrgbIsSceneLinear true
#define kOfxColourspaceLinRedwidegamutrgbIsData false
#define kOfxColourspaceLinRedwidegamutrgbIsCore false

// log3g10_redwidegamutrgb
// Convert RED Log3G10 REDWideGamutRGB to ACES2065-1
// CLFtransformID: urn:aswf:ocio:transformId:1.0:RED:Input:Log3G10_REDWideGamutRGB_to_ACES2065-1:1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:IDT.RED.Log3G10_REDWideGamutRGB.a1.v1
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.ACES_to_Log3G10_RWG.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.Log3G10_RWG_to_ACES.a1.1.0
#define kOfxColourspaceLog3g10Redwidegamutrgb "log3g10_redwidegamutrgb"
#define kOfxColourspaceLog3g10RedwidegamutrgbDisplayName "Log3G10 REDWideGamutRGB"
#define kOfxColourspaceLog3g10RedwidegamutrgbAliasLog3g10Redwidegamutrgb "log3g10_redwidegamutrgb"
#define kOfxColourspaceLog3g10RedwidegamutrgbAliasInputREDREDLog3G10REDWideGamutRGB "Input - RED - REDLog3G10 - REDWideGamutRGB"
#define kOfxColourspaceLog3g10RedwidegamutrgbAliasRl3g10Rwg "rl3g10_rwg"
#define kOfxColourspaceLog3g10RedwidegamutrgbList { "Log3G10 REDWideGamutRGB", "log3g10_redwidegamutrgb", "Input - RED - REDLog3G10 - REDWideGamutRGB", "rl3g10_rwg" }
#define kOfxColourspaceLog3g10RedwidegamutrgbEncoding "log"
#define kOfxColourspaceLog3g10RedwidegamutrgbIsSceneLinear false
#define kOfxColourspaceLog3g10RedwidegamutrgbIsData false
#define kOfxColourspaceLog3g10RedwidegamutrgbIsCore false

// lin_sgamut3
// Convert Linear S-Gamut3 to ACES2065-1
// CLFtransformID: urn:aswf:ocio:transformId:1.0:Sony:Input:Linear_SGamut3_to_ACES2065-1:1.0
#define kOfxColourspaceLinSgamut3 "lin_sgamut3"
#define kOfxColourspaceLinSgamut3DisplayName "Linear S-Gamut3"
#define kOfxColourspaceLinSgamut3AliasLinSgamut3 "lin_sgamut3"
#define kOfxColourspaceLinSgamut3AliasInputSonyLinearSGamut3 "Input - Sony - Linear - S-Gamut3"
#define kOfxColourspaceLinSgamut3List { "Linear S-Gamut3", "lin_sgamut3", "Input - Sony - Linear - S-Gamut3" }
#define kOfxColourspaceLinSgamut3Encoding "scene-linear"
#define kOfxColourspaceLinSgamut3IsSceneLinear true
#define kOfxColourspaceLinSgamut3IsData false
#define kOfxColourspaceLinSgamut3IsCore false

// lin_sgamut3cine
// Convert Linear S-Gamut3.Cine to ACES2065-1
// CLFtransformID: urn:aswf:ocio:transformId:1.0:Sony:Input:Linear_SGamut3Cine_to_ACES2065-1:1.0
#define kOfxColourspaceLinSgamut3cine "lin_sgamut3cine"
#define kOfxColourspaceLinSgamut3cineDisplayName "Linear S-Gamut3.Cine"
#define kOfxColourspaceLinSgamut3cineAliasLinSgamut3cine "lin_sgamut3cine"
#define kOfxColourspaceLinSgamut3cineAliasInputSonyLinearSGamut3Cine "Input - Sony - Linear - S-Gamut3.Cine"
#define kOfxColourspaceLinSgamut3cineList { "Linear S-Gamut3.Cine", "lin_sgamut3cine", "Input - Sony - Linear - S-Gamut3.Cine" }
#define kOfxColourspaceLinSgamut3cineEncoding "scene-linear"
#define kOfxColourspaceLinSgamut3cineIsSceneLinear true
#define kOfxColourspaceLinSgamut3cineIsData false
#define kOfxColourspaceLinSgamut3cineIsCore false

// lin_venice_sgamut3
// Convert Linear Venice S-Gamut3 to ACES2065-1
// CLFtransformID: urn:aswf:ocio:transformId:1.0:Sony:Input:Linear_Venice_SGamut3_to_ACES2065-1:1.0
#define kOfxColourspaceLinVeniceSgamut3 "lin_venice_sgamut3"
#define kOfxColourspaceLinVeniceSgamut3DisplayName "Linear Venice S-Gamut3"
#define kOfxColourspaceLinVeniceSgamut3AliasLinVeniceSgamut3 "lin_venice_sgamut3"
#define kOfxColourspaceLinVeniceSgamut3AliasInputSonyLinearVeniceSGamut3 "Input - Sony - Linear - Venice S-Gamut3"
#define kOfxColourspaceLinVeniceSgamut3List { "Linear Venice S-Gamut3", "lin_venice_sgamut3", "Input - Sony - Linear - Venice S-Gamut3" }
#define kOfxColourspaceLinVeniceSgamut3Encoding "scene-linear"
#define kOfxColourspaceLinVeniceSgamut3IsSceneLinear true
#define kOfxColourspaceLinVeniceSgamut3IsData false
#define kOfxColourspaceLinVeniceSgamut3IsCore false

// lin_venice_sgamut3cine
// Convert Linear Venice S-Gamut3.Cine to ACES2065-1
// CLFtransformID: urn:aswf:ocio:transformId:1.0:Sony:Input:Linear_Venice_SGamut3Cine_to_ACES2065-1:1.0
#define kOfxColourspaceLinVeniceSgamut3cine "lin_venice_sgamut3cine"
#define kOfxColourspaceLinVeniceSgamut3cineDisplayName "Linear Venice S-Gamut3.Cine"
#define kOfxColourspaceLinVeniceSgamut3cineAliasLinVeniceSgamut3cine "lin_venice_sgamut3cine"
#define kOfxColourspaceLinVeniceSgamut3cineAliasInputSonyLinearVeniceSGamut3Cine "Input - Sony - Linear - Venice S-Gamut3.Cine"
#define kOfxColourspaceLinVeniceSgamut3cineList { "Linear Venice S-Gamut3.Cine", "lin_venice_sgamut3cine", "Input - Sony - Linear - Venice S-Gamut3.Cine" }
#define kOfxColourspaceLinVeniceSgamut3cineEncoding "scene-linear"
#define kOfxColourspaceLinVeniceSgamut3cineIsSceneLinear true
#define kOfxColourspaceLinVeniceSgamut3cineIsData false
#define kOfxColourspaceLinVeniceSgamut3cineIsCore false

// slog3_sgamut3
// Convert Sony S-Log3 S-Gamut3 to ACES2065-1
// CLFtransformID: urn:aswf:ocio:transformId:1.0:Sony:Input:SLog3_SGamut3_to_ACES2065-1:1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:IDT.Sony.SLog3_SGamut3.a1.v1
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.ACES_to_SLog3_SGamut3.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.SLog3_SGamut3_to_ACES.a1.1.0
#define kOfxColourspaceSlog3Sgamut3 "slog3_sgamut3"
#define kOfxColourspaceSlog3Sgamut3DisplayName "S-Log3 S-Gamut3"
#define kOfxColourspaceSlog3Sgamut3AliasSlog3Sgamut3 "slog3_sgamut3"
#define kOfxColourspaceSlog3Sgamut3AliasInputSonySLog3SGamut3 "Input - Sony - S-Log3 - S-Gamut3"
#define kOfxColourspaceSlog3Sgamut3List { "S-Log3 S-Gamut3", "slog3_sgamut3", "Input - Sony - S-Log3 - S-Gamut3" }
#define kOfxColourspaceSlog3Sgamut3Encoding "log"
#define kOfxColourspaceSlog3Sgamut3IsSceneLinear false
#define kOfxColourspaceSlog3Sgamut3IsData false
#define kOfxColourspaceSlog3Sgamut3IsCore false

// slog3_sgamut3cine
// Convert Sony S-Log3 S-Gamut3.Cine to ACES2065-1
// CLFtransformID: urn:aswf:ocio:transformId:1.0:Sony:Input:SLog3_SGamut3Cine_to_ACES2065-1:1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:IDT.Sony.SLog3_SGamut3Cine.a1.v1
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.ACES_to_SLog3_SGamut3Cine.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.SLog3_SGamut3Cine_to_ACES.a1.1.0
#define kOfxColourspaceSlog3Sgamut3cine "slog3_sgamut3cine"
#define kOfxColourspaceSlog3Sgamut3cineDisplayName "S-Log3 S-Gamut3.Cine"
#define kOfxColourspaceSlog3Sgamut3cineAliasSlog3Sgamut3cine "slog3_sgamut3cine"
#define kOfxColourspaceSlog3Sgamut3cineAliasInputSonySLog3SGamut3Cine "Input - Sony - S-Log3 - S-Gamut3.Cine"
#define kOfxColourspaceSlog3Sgamut3cineAliasSlog3Sgamutcine "slog3_sgamutcine"
#define kOfxColourspaceSlog3Sgamut3cineList { "S-Log3 S-Gamut3.Cine", "slog3_sgamut3cine", "Input - Sony - S-Log3 - S-Gamut3.Cine", "slog3_sgamutcine" }
#define kOfxColourspaceSlog3Sgamut3cineEncoding "log"
#define kOfxColourspaceSlog3Sgamut3cineIsSceneLinear false
#define kOfxColourspaceSlog3Sgamut3cineIsData false
#define kOfxColourspaceSlog3Sgamut3cineIsCore false

// slog3_venice_sgamut3
// Convert Sony S-Log3 Venice S-Gamut3 to ACES2065-1
// CLFtransformID: urn:aswf:ocio:transformId:1.0:Sony:Input:SLog3_Venice_SGamut3_to_ACES2065-1:1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:IDT.Sony.Venice_SLog3_SGamut3.a1.v1
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.ACES_to_SLog3_Venice_SGamut3.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.SLog3_Venice_SGamut3_to_ACES.a1.1.0
#define kOfxColourspaceSlog3VeniceSgamut3 "slog3_venice_sgamut3"
#define kOfxColourspaceSlog3VeniceSgamut3DisplayName "S-Log3 Venice S-Gamut3"
#define kOfxColourspaceSlog3VeniceSgamut3AliasSlog3VeniceSgamut3 "slog3_venice_sgamut3"
#define kOfxColourspaceSlog3VeniceSgamut3AliasInputSonySLog3VeniceSGamut3 "Input - Sony - S-Log3 - Venice S-Gamut3"
#define kOfxColourspaceSlog3VeniceSgamut3List { "S-Log3 Venice S-Gamut3", "slog3_venice_sgamut3", "Input - Sony - S-Log3 - Venice S-Gamut3" }
#define kOfxColourspaceSlog3VeniceSgamut3Encoding "log"
#define kOfxColourspaceSlog3VeniceSgamut3IsSceneLinear false
#define kOfxColourspaceSlog3VeniceSgamut3IsData false
#define kOfxColourspaceSlog3VeniceSgamut3IsCore false

// slog3_venice_sgamut3cine
// Convert Sony S-Log3 Venice S-Gamut3.Cine to ACES2065-1
// CLFtransformID: urn:aswf:ocio:transformId:1.0:Sony:Input:SLog3_Venice_SGamut3Cine_to_ACES2065-1:1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:IDT.Sony.Venice_SLog3_SGamut3Cine.a1.v1
// AMF Components
// --------------
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.ACES_to_SLog3_Venice_SGamut3Cine.a1.1.0
// ACEStransformID: urn:ampas:aces:transformId:v1.5:ACEScsc.Academy.SLog3_Venice_SGamut3Cine_to_ACES.a1.1.0
#define kOfxColourspaceSlog3VeniceSgamut3cine "slog3_venice_sgamut3cine"
#define kOfxColourspaceSlog3VeniceSgamut3cineDisplayName "S-Log3 Venice S-Gamut3.Cine"
#define kOfxColourspaceSlog3VeniceSgamut3cineAliasSlog3VeniceSgamut3cine "slog3_venice_sgamut3cine"
#define kOfxColourspaceSlog3VeniceSgamut3cineAliasInputSonySLog3VeniceSGamut3Cine "Input - Sony - S-Log3 - Venice S-Gamut3.Cine"
#define kOfxColourspaceSlog3VeniceSgamut3cineAliasSlog3VeniceSgamutcine "slog3_venice_sgamutcine"
#define kOfxColourspaceSlog3VeniceSgamut3cineList { "S-Log3 Venice S-Gamut3.Cine", "slog3_venice_sgamut3cine", "Input - Sony - S-Log3 - Venice S-Gamut3.Cine", "slog3_venice_sgamutcine" }
#define kOfxColourspaceSlog3VeniceSgamut3cineEncoding "log"
#define kOfxColourspaceSlog3VeniceSgamut3cineIsSceneLinear false
#define kOfxColourspaceSlog3VeniceSgamut3cineIsData false
#define kOfxColourspaceSlog3VeniceSgamut3cineIsCore false

// camera_rec709
// Convert ACES2065-1 to Rec.709 camera OETF Rec.709 primaries, D65 white point
// CLFtransformID: urn:aswf:ocio:transformId:1.0:ITU:Utility:AP0_to_Camera_Rec709:1.0
#define kOfxColourspaceCameraRec709 "camera_rec709"
#define kOfxColourspaceCameraRec709DisplayName "Camera Rec.709"
#define kOfxColourspaceCameraRec709AliasCameraRec709 "camera_rec709"
#define kOfxColourspaceCameraRec709AliasUtilityRec709Camera "Utility - Rec.709 - Camera"
#define kOfxColourspaceCameraRec709AliasRec709Camera "rec709_camera"
#define kOfxColourspaceCameraRec709List { "Camera Rec.709", "camera_rec709", "Utility - Rec.709 - Camera", "rec709_camera" }
#define kOfxColourspaceCameraRec709Encoding "sdr-video"
#define kOfxColourspaceCameraRec709IsSceneLinear false
#define kOfxColourspaceCameraRec709IsData false
#define kOfxColourspaceCameraRec709IsCore false

// lin_p3d65
// Convert ACES2065-1 to linear P3 primaries, D65 white point
// CLFtransformID: urn:aswf:ocio:transformId:1.0:OCIO:Utility:AP0_to_Linear_P3-D65:1.0
#define kOfxColourspaceLinP3d65 "lin_p3d65"
#define kOfxColourspaceLinP3d65DisplayName "Linear P3-D65"
#define kOfxColourspaceLinP3d65AliasLinP3d65 "lin_p3d65"
#define kOfxColourspaceLinP3d65AliasUtilityLinearP3D65 "Utility - Linear - P3-D65"
#define kOfxColourspaceLinP3d65AliasLinDisplayp3 "lin_displayp3"
#define kOfxColourspaceLinP3d65AliasLinearDisplayP3 "Linear Display P3"
#define kOfxColourspaceLinP3d65List { "Linear P3-D65", "lin_p3d65", "Utility - Linear - P3-D65", "lin_displayp3", "Linear Display P3" }
#define kOfxColourspaceLinP3d65Encoding "scene-linear"
#define kOfxColourspaceLinP3d65IsSceneLinear true
#define kOfxColourspaceLinP3d65IsData false
#define kOfxColourspaceLinP3d65IsCore false

// lin_rec2020
// Convert ACES2065-1 to linear Rec.2020 primaries, D65 white point
// CLFtransformID: urn:aswf:ocio:transformId:1.0:OCIO:Utility:AP0_to_Linear_Rec2020:1.0
#define kOfxColourspaceLinRec2020 "lin_rec2020"
#define kOfxColourspaceLinRec2020DisplayName "Linear Rec.2020"
#define kOfxColourspaceLinRec2020AliasLinRec2020 "lin_rec2020"
#define kOfxColourspaceLinRec2020AliasUtilityLinearRec2020 "Utility - Linear - Rec.2020"
#define kOfxColourspaceLinRec2020List { "Linear Rec.2020", "lin_rec2020", "Utility - Linear - Rec.2020" }
#define kOfxColourspaceLinRec2020Encoding "scene-linear"
#define kOfxColourspaceLinRec2020IsSceneLinear true
#define kOfxColourspaceLinRec2020IsData false
#define kOfxColourspaceLinRec2020IsCore false

// lin_rec709_srgb
// Convert ACES2065-1 to linear Rec.709 primaries, D65 white point
// CLFtransformID: urn:aswf:ocio:transformId:1.0:OCIO:Utility:AP0_to_Linear_Rec709:1.0
#define kOfxColourspaceLinRec709Srgb "lin_rec709_srgb"
#define kOfxColourspaceLinRec709SrgbDisplayName "Linear Rec.709 (sRGB)"
#define kOfxColourspaceLinRec709SrgbAliasLinRec709Srgb "lin_rec709_srgb"
#define kOfxColourspaceLinRec709SrgbAliasUtilityLinearRec709 "Utility - Linear - Rec.709"
#define kOfxColourspaceLinRec709SrgbAliasLinRec709 "lin_rec709"
#define kOfxColourspaceLinRec709SrgbAliasLinSrgb "lin_srgb"
#define kOfxColourspaceLinRec709SrgbAliasUtilityLinearSRGB "Utility - Linear - sRGB"
#define kOfxColourspaceLinRec709SrgbList { "Linear Rec.709 (sRGB)", "lin_rec709_srgb", "Utility - Linear - Rec.709", "lin_rec709", "lin_srgb", "Utility - Linear - sRGB" }
#define kOfxColourspaceLinRec709SrgbEncoding "scene-linear"
#define kOfxColourspaceLinRec709SrgbIsSceneLinear true
#define kOfxColourspaceLinRec709SrgbIsData false
#define kOfxColourspaceLinRec709SrgbIsCore false

// g18_rec709_tx
// Convert ACES2065-1 to 1.8 gamma-corrected Rec.709 primaries, D65 white point
// CLFtransformID: urn:aswf:ocio:transformId:1.0:OCIO:Utility:AP0_to_Gamma1.8_Rec709-Texture:1.0
#define kOfxColourspaceG18Rec709Tx "g18_rec709_tx"
#define kOfxColourspaceG18Rec709TxDisplayName "Gamma 1.8 Rec.709 - Texture"
#define kOfxColourspaceG18Rec709TxAliasG18Rec709Tx "g18_rec709_tx"
#define kOfxColourspaceG18Rec709TxAliasUtilityGamma18Rec709Texture "Utility - Gamma 1.8 - Rec.709 - Texture"
#define kOfxColourspaceG18Rec709TxAliasG18Rec709 "g18_rec709"
#define kOfxColourspaceG18Rec709TxList { "Gamma 1.8 Rec.709 - Texture", "g18_rec709_tx", "Utility - Gamma 1.8 - Rec.709 - Texture", "g18_rec709" }
#define kOfxColourspaceG18Rec709TxEncoding "sdr-video"
#define kOfxColourspaceG18Rec709TxIsSceneLinear false
#define kOfxColourspaceG18Rec709TxIsData false
#define kOfxColourspaceG18Rec709TxIsCore false

// g22_ap1_tx
// Convert ACES2065-1 to 2.2 gamma-corrected AP1 primaries, ACES ~=D60 white point
// CLFtransformID: urn:aswf:ocio:transformId:1.0:OCIO:Utility:AP0_to_Gamma2.2_AP1-Texture:1.0
#define kOfxColourspaceG22Ap1Tx "g22_ap1_tx"
#define kOfxColourspaceG22Ap1TxDisplayName "Gamma 2.2 AP1 - Texture"
#define kOfxColourspaceG22Ap1TxAliasG22Ap1Tx "g22_ap1_tx"
#define kOfxColourspaceG22Ap1TxAliasG22Ap1 "g22_ap1"
#define kOfxColourspaceG22Ap1TxList { "Gamma 2.2 AP1 - Texture", "g22_ap1_tx", "g22_ap1" }
#define kOfxColourspaceG22Ap1TxEncoding "sdr-video"
#define kOfxColourspaceG22Ap1TxIsSceneLinear false
#define kOfxColourspaceG22Ap1TxIsData false
#define kOfxColourspaceG22Ap1TxIsCore false

// g22_rec709_tx
// Convert ACES2065-1 to 2.2 gamma-corrected Rec.709 primaries, D65 white point
// CLFtransformID: urn:aswf:ocio:transformId:1.0:OCIO:Utility:AP0_to_Gamma2.2_Rec709-Texture:1.0
#define kOfxColourspaceG22Rec709Tx "g22_rec709_tx"
#define kOfxColourspaceG22Rec709TxDisplayName "Gamma 2.2 Rec.709 - Texture"
#define kOfxColourspaceG22Rec709TxAliasG22Rec709Tx "g22_rec709_tx"
#define kOfxColourspaceG22Rec709TxAliasUtilityGamma22Rec709Texture "Utility - Gamma 2.2 - Rec.709 - Texture"
#define kOfxColourspaceG22Rec709TxAliasG22Rec709 "g22_rec709"
#define kOfxColourspaceG22Rec709TxList { "Gamma 2.2 Rec.709 - Texture", "g22_rec709_tx", "Utility - Gamma 2.2 - Rec.709 - Texture", "g22_rec709" }
#define kOfxColourspaceG22Rec709TxEncoding "sdr-video"
#define kOfxColourspaceG22Rec709TxIsSceneLinear false
#define kOfxColourspaceG22Rec709TxIsData false
#define kOfxColourspaceG22Rec709TxIsCore false

// g24_rec709_tx
// Convert ACES2065-1 to 2.4 gamma-corrected Rec.709 primaries, D65 white point
// CLFtransformID: urn:aswf:ocio:transformId:1.0:OCIO:Utility:AP0_to_Gamma2.4_Rec709-Texture:1.0
#define kOfxColourspaceG24Rec709Tx "g24_rec709_tx"
#define kOfxColourspaceG24Rec709TxDisplayName "Gamma 2.4 Rec.709 - Texture"
#define kOfxColourspaceG24Rec709TxAliasG24Rec709Tx "g24_rec709_tx"
#define kOfxColourspaceG24Rec709TxAliasG24Rec709 "g24_rec709"
#define kOfxColourspaceG24Rec709TxAliasRec709Display "rec709_display"
#define kOfxColourspaceG24Rec709TxAliasUtilityRec709Display "Utility - Rec.709 - Display"
#define kOfxColourspaceG24Rec709TxList { "Gamma 2.4 Rec.709 - Texture", "g24_rec709_tx", "g24_rec709", "rec709_display", "Utility - Rec.709 - Display" }
#define kOfxColourspaceG24Rec709TxEncoding "sdr-video"
#define kOfxColourspaceG24Rec709TxIsSceneLinear false
#define kOfxColourspaceG24Rec709TxIsData false
#define kOfxColourspaceG24Rec709TxIsCore false

// srgb_encoded_ap1_tx
// Convert ACES2065-1 to sRGB Encoded AP1 primaries, ACES ~=D60 white point
// CLFtransformID: urn:aswf:ocio:transformId:1.0:OCIO:Utility:AP0_to_sRGB_Encoded_AP1-Texture:1.0
#define kOfxColourspaceSrgbEncodedAp1Tx "srgb_encoded_ap1_tx"
#define kOfxColourspaceSrgbEncodedAp1TxDisplayName "sRGB Encoded AP1 - Texture"
#define kOfxColourspaceSrgbEncodedAp1TxAliasSrgbEncodedAp1Tx "srgb_encoded_ap1_tx"
#define kOfxColourspaceSrgbEncodedAp1TxAliasSrgbAp1 "srgb_ap1"
#define kOfxColourspaceSrgbEncodedAp1TxList { "sRGB Encoded AP1 - Texture", "srgb_encoded_ap1_tx", "srgb_ap1" }
#define kOfxColourspaceSrgbEncodedAp1TxEncoding "sdr-video"
#define kOfxColourspaceSrgbEncodedAp1TxIsSceneLinear false
#define kOfxColourspaceSrgbEncodedAp1TxIsData false
#define kOfxColourspaceSrgbEncodedAp1TxIsCore false

// srgb_encoded_p3d65_tx
// Convert ACES2065-1 to sRGB Encoded P3-D65 primaries, D65 white point
// CLFtransformID: urn:aswf:ocio:transformId:1.0:OCIO:Utility:AP0_to_sRGB_Encoded_P3-D65-Texture:1.0
#define kOfxColourspaceSrgbEncodedP3d65Tx "srgb_encoded_p3d65_tx"
#define kOfxColourspaceSrgbEncodedP3d65TxDisplayName "sRGB Encoded P3-D65 - Texture"
#define kOfxColourspaceSrgbEncodedP3d65TxAliasSrgbEncodedP3d65Tx "srgb_encoded_p3d65_tx"
#define kOfxColourspaceSrgbEncodedP3d65TxAliasSrgbP3d65 "srgb_p3d65"
#define kOfxColourspaceSrgbEncodedP3d65TxAliasSrgbDisplayp3 "srgb_displayp3"
#define kOfxColourspaceSrgbEncodedP3d65TxList { "sRGB Encoded P3-D65 - Texture", "srgb_encoded_p3d65_tx", "srgb_p3d65", "srgb_displayp3" }
#define kOfxColourspaceSrgbEncodedP3d65TxEncoding "sdr-video"
#define kOfxColourspaceSrgbEncodedP3d65TxIsSceneLinear false
#define kOfxColourspaceSrgbEncodedP3d65TxIsData false
#define kOfxColourspaceSrgbEncodedP3d65TxIsCore false

// srgb_tx
// Convert ACES2065-1 to sRGB
// CLFtransformID: urn:aswf:ocio:transformId:1.0:OCIO:Utility:AP0_to_sRGB-Texture:1.0
#define kOfxColourspaceSrgbTx "srgb_tx"
#define kOfxColourspaceSrgbTxDisplayName "sRGB - Texture"
#define kOfxColourspaceSrgbTxAliasSrgbTx "srgb_tx"
#define kOfxColourspaceSrgbTxAliasUtilitySRGBTexture "Utility - sRGB - Texture"
#define kOfxColourspaceSrgbTxAliasSrgbTexture "srgb_texture"
#define kOfxColourspaceSrgbTxAliasInputGenericSRGBTexture "Input - Generic - sRGB - Texture"
#define kOfxColourspaceSrgbTxList { "sRGB - Texture", "srgb_tx", "Utility - sRGB - Texture", "srgb_texture", "Input - Generic - sRGB - Texture" }
#define kOfxColourspaceSrgbTxEncoding ""
#define kOfxColourspaceSrgbTxIsSceneLinear false
#define kOfxColourspaceSrgbTxIsData false
#define kOfxColourspaceSrgbTxIsCore false

// Raw
// The utility "Raw" colorspace.
#define kOfxColourspaceRaw "Raw"
#define kOfxColourspaceRawDisplayName "Raw"
#define kOfxColourspaceRawAliasUtilityRaw "Utility - Raw"
#define kOfxColourspaceRawList { "Raw", "Utility - Raw" }
#define kOfxColourspaceRawEncoding ""
#define kOfxColourspaceRawIsSceneLinear false
#define kOfxColourspaceRawIsData true
#define kOfxColourspaceRawIsCore false

#ifdef __cplusplus
}
#endif

#endif

